// @generated by gen_namespaces; do not edit by hand.

pub(crate) mod as_reported;
pub(crate) mod balance;
pub(crate) mod cash_flow;
pub(crate) mod growth;
pub(crate) mod income;
pub(crate) mod metrics;
pub(crate) mod ratios;
pub(crate) mod reports;
pub(crate) mod segmentation;
pub(crate) mod summaries;

use std::sync::Arc;

use pyo3::prelude::*;
use pyo3_stub_gen::derive::{gen_stub_pyclass, gen_stub_pymethods};

use crate::runtime::ClientHandle;

use self::as_reported::StatementsAsReportedNamespace;
use self::balance::StatementsBalanceNamespace;
use self::cash_flow::StatementsCashFlowNamespace;
use self::growth::StatementsGrowthNamespace;
use self::income::StatementsIncomeNamespace;
use self::metrics::StatementsMetricsNamespace;
use self::ratios::StatementsRatiosNamespace;
use self::reports::StatementsReportsNamespace;
use self::segmentation::StatementsSegmentationNamespace;
use self::summaries::StatementsSummariesNamespace;

/// Statements endpoints for a single client, exposed as `client.statements`.
#[gen_stub_pyclass]
#[pyclass(module = "fmp._native.statements", frozen)]
pub(crate) struct StatementsNamespace {
    builder: Arc<ClientHandle>,
}

impl StatementsNamespace {
    pub(crate) fn new(builder: Arc<ClientHandle>) -> Self {
        Self { builder }
    }
}

#[gen_stub_pymethods]
#[pymethods]
impl StatementsNamespace {
    /// The `statements.as_reported` endpoints, reached as `client.statements.as_reported`.
    #[getter]
    fn as_reported(&self) -> StatementsAsReportedNamespace {
        StatementsAsReportedNamespace::new(self.builder.clone())
    }

    /// The `statements.balance` endpoints, reached as `client.statements.balance`.
    #[getter]
    fn balance(&self) -> StatementsBalanceNamespace {
        StatementsBalanceNamespace::new(self.builder.clone())
    }

    /// The `statements.cash_flow` endpoints, reached as `client.statements.cash_flow`.
    #[getter]
    fn cash_flow(&self) -> StatementsCashFlowNamespace {
        StatementsCashFlowNamespace::new(self.builder.clone())
    }

    /// The `statements.growth` endpoints, reached as `client.statements.growth`.
    #[getter]
    fn growth(&self) -> StatementsGrowthNamespace {
        StatementsGrowthNamespace::new(self.builder.clone())
    }

    /// The `statements.income` endpoints, reached as `client.statements.income`.
    #[getter]
    fn income(&self) -> StatementsIncomeNamespace {
        StatementsIncomeNamespace::new(self.builder.clone())
    }

    /// The `statements.metrics` endpoints, reached as `client.statements.metrics`.
    #[getter]
    fn metrics(&self) -> StatementsMetricsNamespace {
        StatementsMetricsNamespace::new(self.builder.clone())
    }

    /// The `statements.ratios` endpoints, reached as `client.statements.ratios`.
    #[getter]
    fn ratios(&self) -> StatementsRatiosNamespace {
        StatementsRatiosNamespace::new(self.builder.clone())
    }

    /// The `statements.reports` endpoints, reached as `client.statements.reports`.
    #[getter]
    fn reports(&self) -> StatementsReportsNamespace {
        StatementsReportsNamespace::new(self.builder.clone())
    }

    /// The `statements.segmentation` endpoints, reached as `client.statements.segmentation`.
    #[getter]
    fn segmentation(&self) -> StatementsSegmentationNamespace {
        StatementsSegmentationNamespace::new(self.builder.clone())
    }

    /// The `statements.summaries` endpoints, reached as `client.statements.summaries`.
    #[getter]
    fn summaries(&self) -> StatementsSummariesNamespace {
        StatementsSummariesNamespace::new(self.builder.clone())
    }
}
