// Code generated by fmp-py-gen gen_go. DO NOT EDIT.

package fmp

// Response models of the funds domain, generated from the
// crates/libfmp/src/responses/funds module with the ADR 0030 type table.

import (
	"encoding/json/jsontext"
	"encoding/json/v2"
)

// EtfFundHolding is one asset held by an ETF or mutual fund.
type EtfFundHolding struct {
	Symbol           string   `json:"symbol"`
	Asset            string   `json:"asset"`
	Name             string   `json:"name"`
	Isin             string   `json:"isin"`
	SecurityCusip    string   `json:"securityCusip"`
	SharesNumber     uint64   `json:"sharesNumber"`
	WeightPercentage float64  `json:"weightPercentage"`
	MarketValue      float64  `json:"marketValue"`
	UpdatedAt        DateTime `json:"updatedAt"`
}

// etfFundHoldingShadow mirrors EtfFundHolding with a pointer or raw value for
// every required member so a missing or null member is observable after
// decoding.
type etfFundHoldingShadow struct {
	Symbol           *string   `json:"symbol"`
	Asset            *string   `json:"asset"`
	Name             *string   `json:"name"`
	Isin             *string   `json:"isin"`
	SecurityCusip    *string   `json:"securityCusip"`
	SharesNumber     *uint64   `json:"sharesNumber"`
	WeightPercentage *float64  `json:"weightPercentage"`
	MarketValue      *float64  `json:"marketValue"`
	UpdatedAt        *DateTime `json:"updatedAt"`
}

// UnmarshalJSONFrom decodes one JSON object and rejects it with a Decode
// error naming the first required member that is missing or null, as the
// Rust decoder does. Unknown members are ignored.
func (m *EtfFundHolding) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	var shadow etfFundHoldingShadow
	if err := json.UnmarshalDecode(dec, &shadow); err != nil {
		return err
	}
	switch {
	case shadow.Symbol == nil:
		return missingMemberError("EtfFundHolding", "symbol")
	case shadow.Asset == nil:
		return missingMemberError("EtfFundHolding", "asset")
	case shadow.Name == nil:
		return missingMemberError("EtfFundHolding", "name")
	case shadow.Isin == nil:
		return missingMemberError("EtfFundHolding", "isin")
	case shadow.SecurityCusip == nil:
		return missingMemberError("EtfFundHolding", "securityCusip")
	case shadow.SharesNumber == nil:
		return missingMemberError("EtfFundHolding", "sharesNumber")
	case shadow.WeightPercentage == nil:
		return missingMemberError("EtfFundHolding", "weightPercentage")
	case shadow.MarketValue == nil:
		return missingMemberError("EtfFundHolding", "marketValue")
	case shadow.UpdatedAt == nil:
		return missingMemberError("EtfFundHolding", "updatedAt")
	}
	*m = EtfFundHolding{
		Symbol:           *shadow.Symbol,
		Asset:            *shadow.Asset,
		Name:             *shadow.Name,
		Isin:             *shadow.Isin,
		SecurityCusip:    *shadow.SecurityCusip,
		SharesNumber:     *shadow.SharesNumber,
		WeightPercentage: *shadow.WeightPercentage,
		MarketValue:      *shadow.MarketValue,
		UpdatedAt:        *shadow.UpdatedAt,
	}
	return nil
}

// EtfSectorExposure is one sector exposure nested within a fund-information
// row.
type EtfSectorExposure struct {
	Industry string  `json:"industry"`
	Exposure float64 `json:"exposure"`
}

// etfSectorExposureShadow mirrors EtfSectorExposure with a pointer or raw
// value for every required member so a missing or null member is observable
// after decoding.
type etfSectorExposureShadow struct {
	Industry *string  `json:"industry"`
	Exposure *float64 `json:"exposure"`
}

// UnmarshalJSONFrom decodes one JSON object and rejects it with a Decode
// error naming the first required member that is missing or null, as the
// Rust decoder does. Unknown members are ignored.
func (m *EtfSectorExposure) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	var shadow etfSectorExposureShadow
	if err := json.UnmarshalDecode(dec, &shadow); err != nil {
		return err
	}
	switch {
	case shadow.Industry == nil:
		return missingMemberError("EtfSectorExposure", "industry")
	case shadow.Exposure == nil:
		return missingMemberError("EtfSectorExposure", "exposure")
	}
	*m = EtfSectorExposure{
		Industry: *shadow.Industry,
		Exposure: *shadow.Exposure,
	}
	return nil
}

// EtfFundInfo is descriptive, structural, and trading information for an ETF
// or mutual fund.
type EtfFundInfo struct {
	Symbol                string              `json:"symbol"`
	Name                  string              `json:"name"`
	Description           string              `json:"description"`
	Isin                  string              `json:"isin"`
	AssetClass            string              `json:"assetClass"`
	SecurityCusip         string              `json:"securityCusip"`
	Domicile              string              `json:"domicile"`
	Website               string              `json:"website"`
	EtfCompany            string              `json:"etfCompany"`
	ExpenseRatio          float64             `json:"expenseRatio"`
	AssetsUnderManagement uint64              `json:"assetsUnderManagement"`
	AvgVolume             float64             `json:"avgVolume"`
	InceptionDate         Date                `json:"inceptionDate"`
	Nav                   float64             `json:"nav"`
	NavCurrency           string              `json:"navCurrency"`
	HoldingsCount         uint64              `json:"holdingsCount"`
	IsActivelyTrading     bool                `json:"isActivelyTrading"`
	UpdatedAt             string              `json:"updatedAt"`
	SectorsList           []EtfSectorExposure `json:"sectorsList"`
}

// etfFundInfoShadow mirrors EtfFundInfo with a pointer or raw value for every
// required member so a missing or null member is observable after decoding.
type etfFundInfoShadow struct {
	Symbol                *string              `json:"symbol"`
	Name                  *string              `json:"name"`
	Description           *string              `json:"description"`
	Isin                  *string              `json:"isin"`
	AssetClass            *string              `json:"assetClass"`
	SecurityCusip         *string              `json:"securityCusip"`
	Domicile              *string              `json:"domicile"`
	Website               *string              `json:"website"`
	EtfCompany            *string              `json:"etfCompany"`
	ExpenseRatio          *float64             `json:"expenseRatio"`
	AssetsUnderManagement *uint64              `json:"assetsUnderManagement"`
	AvgVolume             *float64             `json:"avgVolume"`
	InceptionDate         *Date                `json:"inceptionDate"`
	Nav                   *float64             `json:"nav"`
	NavCurrency           *string              `json:"navCurrency"`
	HoldingsCount         *uint64              `json:"holdingsCount"`
	IsActivelyTrading     *bool                `json:"isActivelyTrading"`
	UpdatedAt             *string              `json:"updatedAt"`
	SectorsList           *[]EtfSectorExposure `json:"sectorsList"`
}

// UnmarshalJSONFrom decodes one JSON object and rejects it with a Decode
// error naming the first required member that is missing or null, as the
// Rust decoder does. Unknown members are ignored.
func (m *EtfFundInfo) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	var shadow etfFundInfoShadow
	if err := json.UnmarshalDecode(dec, &shadow); err != nil {
		return err
	}
	switch {
	case shadow.Symbol == nil:
		return missingMemberError("EtfFundInfo", "symbol")
	case shadow.Name == nil:
		return missingMemberError("EtfFundInfo", "name")
	case shadow.Description == nil:
		return missingMemberError("EtfFundInfo", "description")
	case shadow.Isin == nil:
		return missingMemberError("EtfFundInfo", "isin")
	case shadow.AssetClass == nil:
		return missingMemberError("EtfFundInfo", "assetClass")
	case shadow.SecurityCusip == nil:
		return missingMemberError("EtfFundInfo", "securityCusip")
	case shadow.Domicile == nil:
		return missingMemberError("EtfFundInfo", "domicile")
	case shadow.Website == nil:
		return missingMemberError("EtfFundInfo", "website")
	case shadow.EtfCompany == nil:
		return missingMemberError("EtfFundInfo", "etfCompany")
	case shadow.ExpenseRatio == nil:
		return missingMemberError("EtfFundInfo", "expenseRatio")
	case shadow.AssetsUnderManagement == nil:
		return missingMemberError("EtfFundInfo", "assetsUnderManagement")
	case shadow.AvgVolume == nil:
		return missingMemberError("EtfFundInfo", "avgVolume")
	case shadow.InceptionDate == nil:
		return missingMemberError("EtfFundInfo", "inceptionDate")
	case shadow.Nav == nil:
		return missingMemberError("EtfFundInfo", "nav")
	case shadow.NavCurrency == nil:
		return missingMemberError("EtfFundInfo", "navCurrency")
	case shadow.HoldingsCount == nil:
		return missingMemberError("EtfFundInfo", "holdingsCount")
	case shadow.IsActivelyTrading == nil:
		return missingMemberError("EtfFundInfo", "isActivelyTrading")
	case shadow.UpdatedAt == nil:
		return missingMemberError("EtfFundInfo", "updatedAt")
	case shadow.SectorsList == nil:
		return missingMemberError("EtfFundInfo", "sectorsList")
	}
	*m = EtfFundInfo{
		Symbol:                *shadow.Symbol,
		Name:                  *shadow.Name,
		Description:           *shadow.Description,
		Isin:                  *shadow.Isin,
		AssetClass:            *shadow.AssetClass,
		SecurityCusip:         *shadow.SecurityCusip,
		Domicile:              *shadow.Domicile,
		Website:               *shadow.Website,
		EtfCompany:            *shadow.EtfCompany,
		ExpenseRatio:          *shadow.ExpenseRatio,
		AssetsUnderManagement: *shadow.AssetsUnderManagement,
		AvgVolume:             *shadow.AvgVolume,
		InceptionDate:         *shadow.InceptionDate,
		Nav:                   *shadow.Nav,
		NavCurrency:           *shadow.NavCurrency,
		HoldingsCount:         *shadow.HoldingsCount,
		IsActivelyTrading:     *shadow.IsActivelyTrading,
		UpdatedAt:             *shadow.UpdatedAt,
		SectorsList:           *shadow.SectorsList,
	}
	return nil
}

// EtfCountryWeighting is one country allocation reported as an exact
// percent-bearing string.
type EtfCountryWeighting struct {
	Country          string `json:"country"`
	WeightPercentage string `json:"weightPercentage"`
}

// etfCountryWeightingShadow mirrors EtfCountryWeighting with a pointer or raw
// value for every required member so a missing or null member is observable
// after decoding.
type etfCountryWeightingShadow struct {
	Country          *string `json:"country"`
	WeightPercentage *string `json:"weightPercentage"`
}

// UnmarshalJSONFrom decodes one JSON object and rejects it with a Decode
// error naming the first required member that is missing or null, as the
// Rust decoder does. Unknown members are ignored.
func (m *EtfCountryWeighting) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	var shadow etfCountryWeightingShadow
	if err := json.UnmarshalDecode(dec, &shadow); err != nil {
		return err
	}
	switch {
	case shadow.Country == nil:
		return missingMemberError("EtfCountryWeighting", "country")
	case shadow.WeightPercentage == nil:
		return missingMemberError("EtfCountryWeighting", "weightPercentage")
	}
	*m = EtfCountryWeighting{
		Country:          *shadow.Country,
		WeightPercentage: *shadow.WeightPercentage,
	}
	return nil
}

// EtfAssetExposure is one ETF's exposure to a requested asset.
type EtfAssetExposure struct {
	Symbol           string  `json:"symbol"`
	Asset            string  `json:"asset"`
	SharesNumber     uint64  `json:"sharesNumber"`
	WeightPercentage float64 `json:"weightPercentage"`
	MarketValue      float64 `json:"marketValue"`
}

// etfAssetExposureShadow mirrors EtfAssetExposure with a pointer or raw value
// for every required member so a missing or null member is observable after
// decoding.
type etfAssetExposureShadow struct {
	Symbol           *string  `json:"symbol"`
	Asset            *string  `json:"asset"`
	SharesNumber     *uint64  `json:"sharesNumber"`
	WeightPercentage *float64 `json:"weightPercentage"`
	MarketValue      *float64 `json:"marketValue"`
}

// UnmarshalJSONFrom decodes one JSON object and rejects it with a Decode
// error naming the first required member that is missing or null, as the
// Rust decoder does. Unknown members are ignored.
func (m *EtfAssetExposure) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	var shadow etfAssetExposureShadow
	if err := json.UnmarshalDecode(dec, &shadow); err != nil {
		return err
	}
	switch {
	case shadow.Symbol == nil:
		return missingMemberError("EtfAssetExposure", "symbol")
	case shadow.Asset == nil:
		return missingMemberError("EtfAssetExposure", "asset")
	case shadow.SharesNumber == nil:
		return missingMemberError("EtfAssetExposure", "sharesNumber")
	case shadow.WeightPercentage == nil:
		return missingMemberError("EtfAssetExposure", "weightPercentage")
	case shadow.MarketValue == nil:
		return missingMemberError("EtfAssetExposure", "marketValue")
	}
	*m = EtfAssetExposure{
		Symbol:           *shadow.Symbol,
		Asset:            *shadow.Asset,
		SharesNumber:     *shadow.SharesNumber,
		WeightPercentage: *shadow.WeightPercentage,
		MarketValue:      *shadow.MarketValue,
	}
	return nil
}

// EtfSectorWeighting is one numeric sector allocation for an ETF or mutual
// fund.
type EtfSectorWeighting struct {
	Symbol           string  `json:"symbol"`
	Sector           string  `json:"sector"`
	WeightPercentage float64 `json:"weightPercentage"`
}

// etfSectorWeightingShadow mirrors EtfSectorWeighting with a pointer or raw
// value for every required member so a missing or null member is observable
// after decoding.
type etfSectorWeightingShadow struct {
	Symbol           *string  `json:"symbol"`
	Sector           *string  `json:"sector"`
	WeightPercentage *float64 `json:"weightPercentage"`
}

// UnmarshalJSONFrom decodes one JSON object and rejects it with a Decode
// error naming the first required member that is missing or null, as the
// Rust decoder does. Unknown members are ignored.
func (m *EtfSectorWeighting) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	var shadow etfSectorWeightingShadow
	if err := json.UnmarshalDecode(dec, &shadow); err != nil {
		return err
	}
	switch {
	case shadow.Symbol == nil:
		return missingMemberError("EtfSectorWeighting", "symbol")
	case shadow.Sector == nil:
		return missingMemberError("EtfSectorWeighting", "sector")
	case shadow.WeightPercentage == nil:
		return missingMemberError("EtfSectorWeighting", "weightPercentage")
	}
	*m = EtfSectorWeighting{
		Symbol:           *shadow.Symbol,
		Sector:           *shadow.Sector,
		WeightPercentage: *shadow.WeightPercentage,
	}
	return nil
}

// FundDisclosureHolder is one fund holder from the latest disclosure for a
// security.
type FundDisclosureHolder struct {
	Cik           string  `json:"cik"`
	Holder        string  `json:"holder"`
	SecurityCusip string  `json:"securityCusip"`
	Shares        uint64  `json:"shares"`
	DateReported  Date    `json:"dateReported"`
	Change        int64   `json:"change"`
	WeightPercent float64 `json:"weightPercent"`
}

// fundDisclosureHolderShadow mirrors FundDisclosureHolder with a pointer or
// raw value for every required member so a missing or null member is
// observable after decoding.
type fundDisclosureHolderShadow struct {
	Cik           *string  `json:"cik"`
	Holder        *string  `json:"holder"`
	SecurityCusip *string  `json:"securityCusip"`
	Shares        *uint64  `json:"shares"`
	DateReported  *Date    `json:"dateReported"`
	Change        *int64   `json:"change"`
	WeightPercent *float64 `json:"weightPercent"`
}

// UnmarshalJSONFrom decodes one JSON object and rejects it with a Decode
// error naming the first required member that is missing or null, as the
// Rust decoder does. Unknown members are ignored.
func (m *FundDisclosureHolder) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	var shadow fundDisclosureHolderShadow
	if err := json.UnmarshalDecode(dec, &shadow); err != nil {
		return err
	}
	switch {
	case shadow.Cik == nil:
		return missingMemberError("FundDisclosureHolder", "cik")
	case shadow.Holder == nil:
		return missingMemberError("FundDisclosureHolder", "holder")
	case shadow.SecurityCusip == nil:
		return missingMemberError("FundDisclosureHolder", "securityCusip")
	case shadow.Shares == nil:
		return missingMemberError("FundDisclosureHolder", "shares")
	case shadow.DateReported == nil:
		return missingMemberError("FundDisclosureHolder", "dateReported")
	case shadow.Change == nil:
		return missingMemberError("FundDisclosureHolder", "change")
	case shadow.WeightPercent == nil:
		return missingMemberError("FundDisclosureHolder", "weightPercent")
	}
	*m = FundDisclosureHolder{
		Cik:           *shadow.Cik,
		Holder:        *shadow.Holder,
		SecurityCusip: *shadow.SecurityCusip,
		Shares:        *shadow.Shares,
		DateReported:  *shadow.DateReported,
		Change:        *shadow.Change,
		WeightPercent: *shadow.WeightPercent,
	}
	return nil
}

// FundDisclosure is one position in a mutual-fund disclosure filing.
type FundDisclosure struct {
	Cik                 string   `json:"cik"`
	Date                Date     `json:"date"`
	AcceptedDate        DateTime `json:"acceptedDate"`
	Symbol              string   `json:"symbol"`
	Name                string   `json:"name"`
	Lei                 string   `json:"lei"`
	Title               string   `json:"title"`
	Cusip               string   `json:"cusip"`
	Isin                string   `json:"isin"`
	Balance             uint64   `json:"balance"`
	Units               string   `json:"units"`
	CurrencyCode        string   `json:"cur_cd"`
	ValUsd              float64  `json:"valUsd"`
	PctVal              float64  `json:"pctVal"`
	PayoffProfile       string   `json:"payoffProfile"`
	AssetCat            string   `json:"assetCat"`
	IssuerCat           string   `json:"issuerCat"`
	InvCountry          string   `json:"invCountry"`
	IsRestrictedSec     string   `json:"isRestrictedSec"`
	FairValLevel        string   `json:"fairValLevel"`
	IsCashCollateral    string   `json:"isCashCollateral"`
	IsNonCashCollateral string   `json:"isNonCashCollateral"`
	IsLoanByFund        string   `json:"isLoanByFund"`
}

// fundDisclosureShadow mirrors FundDisclosure with a pointer or raw value for
// every required member so a missing or null member is observable after
// decoding.
type fundDisclosureShadow struct {
	Cik                 *string   `json:"cik"`
	Date                *Date     `json:"date"`
	AcceptedDate        *DateTime `json:"acceptedDate"`
	Symbol              *string   `json:"symbol"`
	Name                *string   `json:"name"`
	Lei                 *string   `json:"lei"`
	Title               *string   `json:"title"`
	Cusip               *string   `json:"cusip"`
	Isin                *string   `json:"isin"`
	Balance             *uint64   `json:"balance"`
	Units               *string   `json:"units"`
	CurrencyCode        *string   `json:"cur_cd"`
	ValUsd              *float64  `json:"valUsd"`
	PctVal              *float64  `json:"pctVal"`
	PayoffProfile       *string   `json:"payoffProfile"`
	AssetCat            *string   `json:"assetCat"`
	IssuerCat           *string   `json:"issuerCat"`
	InvCountry          *string   `json:"invCountry"`
	IsRestrictedSec     *string   `json:"isRestrictedSec"`
	FairValLevel        *string   `json:"fairValLevel"`
	IsCashCollateral    *string   `json:"isCashCollateral"`
	IsNonCashCollateral *string   `json:"isNonCashCollateral"`
	IsLoanByFund        *string   `json:"isLoanByFund"`
}

// UnmarshalJSONFrom decodes one JSON object and rejects it with a Decode
// error naming the first required member that is missing or null, as the
// Rust decoder does. Unknown members are ignored.
func (m *FundDisclosure) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	var shadow fundDisclosureShadow
	if err := json.UnmarshalDecode(dec, &shadow); err != nil {
		return err
	}
	switch {
	case shadow.Cik == nil:
		return missingMemberError("FundDisclosure", "cik")
	case shadow.Date == nil:
		return missingMemberError("FundDisclosure", "date")
	case shadow.AcceptedDate == nil:
		return missingMemberError("FundDisclosure", "acceptedDate")
	case shadow.Symbol == nil:
		return missingMemberError("FundDisclosure", "symbol")
	case shadow.Name == nil:
		return missingMemberError("FundDisclosure", "name")
	case shadow.Lei == nil:
		return missingMemberError("FundDisclosure", "lei")
	case shadow.Title == nil:
		return missingMemberError("FundDisclosure", "title")
	case shadow.Cusip == nil:
		return missingMemberError("FundDisclosure", "cusip")
	case shadow.Isin == nil:
		return missingMemberError("FundDisclosure", "isin")
	case shadow.Balance == nil:
		return missingMemberError("FundDisclosure", "balance")
	case shadow.Units == nil:
		return missingMemberError("FundDisclosure", "units")
	case shadow.CurrencyCode == nil:
		return missingMemberError("FundDisclosure", "cur_cd")
	case shadow.ValUsd == nil:
		return missingMemberError("FundDisclosure", "valUsd")
	case shadow.PctVal == nil:
		return missingMemberError("FundDisclosure", "pctVal")
	case shadow.PayoffProfile == nil:
		return missingMemberError("FundDisclosure", "payoffProfile")
	case shadow.AssetCat == nil:
		return missingMemberError("FundDisclosure", "assetCat")
	case shadow.IssuerCat == nil:
		return missingMemberError("FundDisclosure", "issuerCat")
	case shadow.InvCountry == nil:
		return missingMemberError("FundDisclosure", "invCountry")
	case shadow.IsRestrictedSec == nil:
		return missingMemberError("FundDisclosure", "isRestrictedSec")
	case shadow.FairValLevel == nil:
		return missingMemberError("FundDisclosure", "fairValLevel")
	case shadow.IsCashCollateral == nil:
		return missingMemberError("FundDisclosure", "isCashCollateral")
	case shadow.IsNonCashCollateral == nil:
		return missingMemberError("FundDisclosure", "isNonCashCollateral")
	case shadow.IsLoanByFund == nil:
		return missingMemberError("FundDisclosure", "isLoanByFund")
	}
	*m = FundDisclosure{
		Cik:                 *shadow.Cik,
		Date:                *shadow.Date,
		AcceptedDate:        *shadow.AcceptedDate,
		Symbol:              *shadow.Symbol,
		Name:                *shadow.Name,
		Lei:                 *shadow.Lei,
		Title:               *shadow.Title,
		Cusip:               *shadow.Cusip,
		Isin:                *shadow.Isin,
		Balance:             *shadow.Balance,
		Units:               *shadow.Units,
		CurrencyCode:        *shadow.CurrencyCode,
		ValUsd:              *shadow.ValUsd,
		PctVal:              *shadow.PctVal,
		PayoffProfile:       *shadow.PayoffProfile,
		AssetCat:            *shadow.AssetCat,
		IssuerCat:           *shadow.IssuerCat,
		InvCountry:          *shadow.InvCountry,
		IsRestrictedSec:     *shadow.IsRestrictedSec,
		FairValLevel:        *shadow.FairValLevel,
		IsCashCollateral:    *shadow.IsCashCollateral,
		IsNonCashCollateral: *shadow.IsNonCashCollateral,
		IsLoanByFund:        *shadow.IsLoanByFund,
	}
	return nil
}

// FundDisclosureSearchResult is one result from searching disclosure holders
// by fund or ETF name.
type FundDisclosureSearchResult struct {
	Symbol              string `json:"symbol"`
	Cik                 string `json:"cik"`
	ClassId             string `json:"classId"`
	SeriesId            string `json:"seriesId"`
	EntityName          string `json:"entityName"`
	EntityOrgType       string `json:"entityOrgType"`
	SeriesName          string `json:"seriesName"`
	ClassName           string `json:"className"`
	ReportingFileNumber string `json:"reportingFileNumber"`
	Address             string `json:"address"`
	City                string `json:"city"`
	ZipCode             string `json:"zipCode"`
	State               string `json:"state"`
}

// fundDisclosureSearchResultShadow mirrors FundDisclosureSearchResult with a
// pointer or raw value for every required member so a missing or null member
// is observable after decoding.
type fundDisclosureSearchResultShadow struct {
	Symbol              *string `json:"symbol"`
	Cik                 *string `json:"cik"`
	ClassId             *string `json:"classId"`
	SeriesId            *string `json:"seriesId"`
	EntityName          *string `json:"entityName"`
	EntityOrgType       *string `json:"entityOrgType"`
	SeriesName          *string `json:"seriesName"`
	ClassName           *string `json:"className"`
	ReportingFileNumber *string `json:"reportingFileNumber"`
	Address             *string `json:"address"`
	City                *string `json:"city"`
	ZipCode             *string `json:"zipCode"`
	State               *string `json:"state"`
}

// UnmarshalJSONFrom decodes one JSON object and rejects it with a Decode
// error naming the first required member that is missing or null, as the
// Rust decoder does. Unknown members are ignored.
func (m *FundDisclosureSearchResult) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	var shadow fundDisclosureSearchResultShadow
	if err := json.UnmarshalDecode(dec, &shadow); err != nil {
		return err
	}
	switch {
	case shadow.Symbol == nil:
		return missingMemberError("FundDisclosureSearchResult", "symbol")
	case shadow.Cik == nil:
		return missingMemberError("FundDisclosureSearchResult", "cik")
	case shadow.ClassId == nil:
		return missingMemberError("FundDisclosureSearchResult", "classId")
	case shadow.SeriesId == nil:
		return missingMemberError("FundDisclosureSearchResult", "seriesId")
	case shadow.EntityName == nil:
		return missingMemberError("FundDisclosureSearchResult", "entityName")
	case shadow.EntityOrgType == nil:
		return missingMemberError("FundDisclosureSearchResult", "entityOrgType")
	case shadow.SeriesName == nil:
		return missingMemberError("FundDisclosureSearchResult", "seriesName")
	case shadow.ClassName == nil:
		return missingMemberError("FundDisclosureSearchResult", "className")
	case shadow.ReportingFileNumber == nil:
		return missingMemberError("FundDisclosureSearchResult", "reportingFileNumber")
	case shadow.Address == nil:
		return missingMemberError("FundDisclosureSearchResult", "address")
	case shadow.City == nil:
		return missingMemberError("FundDisclosureSearchResult", "city")
	case shadow.ZipCode == nil:
		return missingMemberError("FundDisclosureSearchResult", "zipCode")
	case shadow.State == nil:
		return missingMemberError("FundDisclosureSearchResult", "state")
	}
	*m = FundDisclosureSearchResult{
		Symbol:              *shadow.Symbol,
		Cik:                 *shadow.Cik,
		ClassId:             *shadow.ClassId,
		SeriesId:            *shadow.SeriesId,
		EntityName:          *shadow.EntityName,
		EntityOrgType:       *shadow.EntityOrgType,
		SeriesName:          *shadow.SeriesName,
		ClassName:           *shadow.ClassName,
		ReportingFileNumber: *shadow.ReportingFileNumber,
		Address:             *shadow.Address,
		City:                *shadow.City,
		ZipCode:             *shadow.ZipCode,
		State:               *shadow.State,
	}
	return nil
}
