// Code generated by fmp-py-gen gen_go. DO NOT EDIT.

package fmp

// The namespace fields promoted onto Client, one per generated registry
// domain.

// Namespaces groups the generated endpoint namespaces, one field per registry
// domain. Client embeds it, so client.Quote.Full is the call shape; the fields
// are valid only on a Client built by NewClient.
type Namespaces struct {
	// Analyst holds the analyst endpoints.
	Analyst AnalystNamespace
	// Calendar holds the calendar endpoints.
	Calendar CalendarNamespace
	// Chart holds the chart endpoints.
	Chart ChartNamespace
	// Company holds the company endpoints.
	Company CompanyNamespace
	// Quote holds the quote endpoints.
	Quote QuoteNamespace
}

// bindNamespaces points every namespace at its client.
func (c *Client) bindNamespaces() {
	c.Analyst = newAnalystNamespace(c)
	c.Calendar = newCalendarNamespace(c)
	c.Chart = newChartNamespace(c)
	c.Company = newCompanyNamespace(c)
	c.Quote = newQuoteNamespace(c)
}
