// Code generated by fmp-py-gen gen_go. DO NOT EDIT.

package fmp

// Endpoint methods of the quote domain, generated from
// crates/fmp-py-gen/registry/quote.toml and the wire contract read from
// crates/libfmp/src/endpoints (ADR 0030).

import (
	"context"
	"slices"
)

// QuoteNamespace groups the quote endpoints. It is reached as Client.Quote and
// is valid only when obtained from a Client built by NewClient.
type QuoteNamespace struct {
	client *Client
}

func newQuoteNamespace(client *Client) QuoteNamespace {
	return QuoteNamespace{
		client: client,
	}
}

// AftermarketQuoteQuery holds the query parameters of the endpoints that take
// it: NewAftermarketQuoteQuery takes the required arguments and each With
// method sets an optional one. Values are validated when the request is built.
type AftermarketQuoteQuery struct {
	symbol string
}

// NewAftermarketQuoteQuery creates the query from its required arguments.
func NewAftermarketQuoteQuery(symbol string) AftermarketQuoteQuery {
	return AftermarketQuoteQuery{symbol: symbol}
}

// Symbol returns the symbol argument as given.
func (q AftermarketQuoteQuery) Symbol() string {
	return q.symbol
}

func (q AftermarketQuoteQuery) params() ([]queryParam, error) {
	symbol, err := tickerParam("symbol", q.symbol)
	if err != nil {
		return nil, err
	}
	return []queryParam{symbol}, nil
}

// AftermarketTradeQuery holds the query parameters of the endpoints that take
// it: NewAftermarketTradeQuery takes the required arguments and each With
// method sets an optional one. Values are validated when the request is built.
type AftermarketTradeQuery struct {
	symbol string
}

// NewAftermarketTradeQuery creates the query from its required arguments.
func NewAftermarketTradeQuery(symbol string) AftermarketTradeQuery {
	return AftermarketTradeQuery{symbol: symbol}
}

// Symbol returns the symbol argument as given.
func (q AftermarketTradeQuery) Symbol() string {
	return q.symbol
}

func (q AftermarketTradeQuery) params() ([]queryParam, error) {
	symbol, err := tickerParam("symbol", q.symbol)
	if err != nil {
		return nil, err
	}
	return []queryParam{symbol}, nil
}

// BatchAftermarketQuoteQuery holds the query parameters of the endpoints that
// take it: NewBatchAftermarketQuoteQuery takes the required arguments and each
// With method sets an optional one. Values are validated when the request is
// built.
type BatchAftermarketQuoteQuery struct {
	symbols []string
}

// NewBatchAftermarketQuoteQuery creates the query from its required arguments.
func NewBatchAftermarketQuoteQuery(symbols []string) BatchAftermarketQuoteQuery {
	return BatchAftermarketQuoteQuery{symbols: slices.Clone(symbols)}
}

// Symbols returns the symbols argument as given.
func (q BatchAftermarketQuoteQuery) Symbols() []string {
	return q.symbols
}

func (q BatchAftermarketQuoteQuery) params() ([]queryParam, error) {
	symbols, err := tickerListParam("symbols", q.symbols)
	if err != nil {
		return nil, err
	}
	return []queryParam{symbols}, nil
}

// BatchAftermarketTradeQuery holds the query parameters of the endpoints that
// take it: NewBatchAftermarketTradeQuery takes the required arguments and each
// With method sets an optional one. Values are validated when the request is
// built.
type BatchAftermarketTradeQuery struct {
	symbols []string
}

// NewBatchAftermarketTradeQuery creates the query from its required arguments.
func NewBatchAftermarketTradeQuery(symbols []string) BatchAftermarketTradeQuery {
	return BatchAftermarketTradeQuery{symbols: slices.Clone(symbols)}
}

// Symbols returns the symbols argument as given.
func (q BatchAftermarketTradeQuery) Symbols() []string {
	return q.symbols
}

func (q BatchAftermarketTradeQuery) params() ([]queryParam, error) {
	symbols, err := tickerListParam("symbols", q.symbols)
	if err != nil {
		return nil, err
	}
	return []queryParam{symbols}, nil
}

// BatchQuoteQuery holds the query parameters of the endpoints that take it:
// NewBatchQuoteQuery takes the required arguments and each With method sets an
// optional one. Values are validated when the request is built.
type BatchQuoteQuery struct {
	symbols []string
}

// NewBatchQuoteQuery creates the query from its required arguments.
func NewBatchQuoteQuery(symbols []string) BatchQuoteQuery {
	return BatchQuoteQuery{symbols: slices.Clone(symbols)}
}

// Symbols returns the symbols argument as given.
func (q BatchQuoteQuery) Symbols() []string {
	return q.symbols
}

func (q BatchQuoteQuery) params() ([]queryParam, error) {
	symbols, err := tickerListParam("symbols", q.symbols)
	if err != nil {
		return nil, err
	}
	return []queryParam{symbols}, nil
}

// BatchQuoteShortQuery holds the query parameters of the endpoints that take
// it: NewBatchQuoteShortQuery takes the required arguments and each With
// method sets an optional one. Values are validated when the request is built.
type BatchQuoteShortQuery struct {
	symbols []string
}

// NewBatchQuoteShortQuery creates the query from its required arguments.
func NewBatchQuoteShortQuery(symbols []string) BatchQuoteShortQuery {
	return BatchQuoteShortQuery{symbols: slices.Clone(symbols)}
}

// Symbols returns the symbols argument as given.
func (q BatchQuoteShortQuery) Symbols() []string {
	return q.symbols
}

func (q BatchQuoteShortQuery) params() ([]queryParam, error) {
	symbols, err := tickerListParam("symbols", q.symbols)
	if err != nil {
		return nil, err
	}
	return []queryParam{symbols}, nil
}

// ExchangeQuotesQuery holds the query parameters of the endpoints that take
// it: NewExchangeQuotesQuery takes the required arguments and each With method
// sets an optional one. Values are validated when the request is built.
type ExchangeQuotesQuery struct {
	exchange string
}

// NewExchangeQuotesQuery creates the query from its required arguments.
func NewExchangeQuotesQuery(exchange string) ExchangeQuotesQuery {
	return ExchangeQuotesQuery{exchange: exchange}
}

// Exchange returns the exchange argument as given.
func (q ExchangeQuotesQuery) Exchange() string {
	return q.exchange
}

func (q ExchangeQuotesQuery) params() ([]queryParam, error) {
	params := make([]queryParam, 0, 2)
	exchange, err := stringParam("exchange", q.exchange)
	if err != nil {
		return nil, err
	}
	params = append(params, exchange)
	params = append(params, queryParam{Name: "short", Value: "true"})
	return params, nil
}

// StockPriceChangeQuery holds the query parameters of the endpoints that take
// it: NewStockPriceChangeQuery takes the required arguments and each With
// method sets an optional one. Values are validated when the request is built.
type StockPriceChangeQuery struct {
	symbol string
}

// NewStockPriceChangeQuery creates the query from its required arguments.
func NewStockPriceChangeQuery(symbol string) StockPriceChangeQuery {
	return StockPriceChangeQuery{symbol: symbol}
}

// Symbol returns the symbol argument as given.
func (q StockPriceChangeQuery) Symbol() string {
	return q.symbol
}

func (q StockPriceChangeQuery) params() ([]queryParam, error) {
	symbol, err := tickerParam("symbol", q.symbol)
	if err != nil {
		return nil, err
	}
	return []queryParam{symbol}, nil
}

// shortOnlyParams is the fixed query of the endpoints that encode
// ShortOnlyQuery in the Rust crate; it exposes no choice.
var shortOnlyParams = []queryParam{{Name: "short", Value: "true"}}

// Full returns the full quote for a symbol.
//
// GET quote?symbol=
func (n *QuoteNamespace) Full(ctx context.Context, q QuoteQuery) ([]Quote, error) {
	params, err := q.params()
	if err != nil {
		return nil, err
	}
	var out []Quote
	if err := n.client.getJSON(ctx, "quote", "quote", params, &out); err != nil {
		return nil, err
	}
	return out, nil
}

// Short returns the compact quote array for a symbol.
//
// GET quote-short?symbol=
func (n *QuoteNamespace) Short(ctx context.Context, q QuoteShortQuery) ([]QuoteShort, error) {
	params, err := q.params()
	if err != nil {
		return nil, err
	}
	var out []QuoteShort
	if err := n.client.getJSON(ctx, "quote-short", "quote-short", params, &out); err != nil {
		return nil, err
	}
	return out, nil
}

// MutualFunds returns compact quotes for every mutual fund, without a query.
//
// GET batch-mutualfund-quotes?short=true
func (n *QuoteNamespace) MutualFunds(ctx context.Context) ([]QuoteShort, error) {
	var out []QuoteShort
	if err := n.client.getJSON(ctx, "batch-mutualfund-quotes", "batch-mutualfund-quotes", shortOnlyParams, &out); err != nil {
		return nil, err
	}
	return out, nil
}

// AftermarketTrade retrieves US aftermarket trades for one ticker.
//
// GET aftermarket-trade?symbol=
func (n *QuoteNamespace) AftermarketTrade(ctx context.Context, q AftermarketTradeQuery) ([]AftermarketTrade, error) {
	params, err := q.params()
	if err != nil {
		return nil, err
	}
	var out []AftermarketTrade
	if err := n.client.getJSON(ctx, "aftermarket-trade", "aftermarket-trade", params, &out); err != nil {
		return nil, err
	}
	return out, nil
}

// AftermarketQuote retrieves US aftermarket bid-and-ask quotes for one ticker.
//
// GET aftermarket-quote?symbol=
func (n *QuoteNamespace) AftermarketQuote(ctx context.Context, q AftermarketQuoteQuery) ([]AftermarketQuote, error) {
	params, err := q.params()
	if err != nil {
		return nil, err
	}
	var out []AftermarketQuote
	if err := n.client.getJSON(ctx, "aftermarket-quote", "aftermarket-quote", params, &out); err != nil {
		return nil, err
	}
	return out, nil
}

// StockPriceChange retrieves worldwide percentage price changes for one stock.
//
// GET stock-price-change?symbol=
func (n *QuoteNamespace) StockPriceChange(ctx context.Context, q StockPriceChangeQuery) ([]StockPriceChange, error) {
	params, err := q.params()
	if err != nil {
		return nil, err
	}
	var out []StockPriceChange
	if err := n.client.getJSON(ctx, "stock-price-change", "stock-price-change", params, &out); err != nil {
		return nil, err
	}
	return out, nil
}

// Batch retrieves detailed worldwide stock quotes for multiple tickers.
//
// GET batch-quote?symbols=
func (n *QuoteNamespace) Batch(ctx context.Context, q BatchQuoteQuery) ([]Quote, error) {
	params, err := q.params()
	if err != nil {
		return nil, err
	}
	var out []Quote
	if err := n.client.getJSON(ctx, "batch-quote", "batch-quote", params, &out); err != nil {
		return nil, err
	}
	return out, nil
}

// BatchShort retrieves compact worldwide stock quotes for multiple tickers.
//
// GET batch-quote-short?symbols=
func (n *QuoteNamespace) BatchShort(ctx context.Context, q BatchQuoteShortQuery) ([]QuoteShort, error) {
	params, err := q.params()
	if err != nil {
		return nil, err
	}
	var out []QuoteShort
	if err := n.client.getJSON(ctx, "batch-quote-short", "batch-quote-short", params, &out); err != nil {
		return nil, err
	}
	return out, nil
}

// BatchAftermarketTrade retrieves US aftermarket trades for multiple tickers.
//
// GET batch-aftermarket-trade?symbols=
func (n *QuoteNamespace) BatchAftermarketTrade(ctx context.Context, q BatchAftermarketTradeQuery) ([]AftermarketTrade, error) {
	params, err := q.params()
	if err != nil {
		return nil, err
	}
	var out []AftermarketTrade
	if err := n.client.getJSON(ctx, "batch-aftermarket-trade", "batch-aftermarket-trade", params, &out); err != nil {
		return nil, err
	}
	return out, nil
}

// BatchAftermarketQuote retrieves US aftermarket bid-and-ask quotes for
// multiple tickers.
//
// GET batch-aftermarket-quote?symbols=
func (n *QuoteNamespace) BatchAftermarketQuote(ctx context.Context, q BatchAftermarketQuoteQuery) ([]AftermarketQuote, error) {
	params, err := q.params()
	if err != nil {
		return nil, err
	}
	var out []AftermarketQuote
	if err := n.client.getJSON(ctx, "batch-aftermarket-quote", "batch-aftermarket-quote", params, &out); err != nil {
		return nil, err
	}
	return out, nil
}

// Exchange retrieves compact quotes for every stock on one exchange.
//
// GET batch-exchange-quote?exchange=&short=true
func (n *QuoteNamespace) Exchange(ctx context.Context, q ExchangeQuotesQuery) ([]QuoteShort, error) {
	params, err := q.params()
	if err != nil {
		return nil, err
	}
	var out []QuoteShort
	if err := n.client.getJSON(ctx, "batch-exchange-quote", "batch-exchange-quote", params, &out); err != nil {
		return nil, err
	}
	return out, nil
}

// Etfs retrieves compact quotes for the documented ETF universe.
//
// GET batch-etf-quotes?short=true
func (n *QuoteNamespace) Etfs(ctx context.Context) ([]QuoteShort, error) {
	var out []QuoteShort
	if err := n.client.getJSON(ctx, "batch-etf-quotes", "batch-etf-quotes", shortOnlyParams, &out); err != nil {
		return nil, err
	}
	return out, nil
}

// Commodities retrieves compact quotes for the documented commodity universe.
//
// GET batch-commodity-quotes?short=true
func (n *QuoteNamespace) Commodities(ctx context.Context) ([]QuoteShort, error) {
	var out []QuoteShort
	if err := n.client.getJSON(ctx, "batch-commodity-quotes", "batch-commodity-quotes", shortOnlyParams, &out); err != nil {
		return nil, err
	}
	return out, nil
}

// Cryptocurrencies retrieves compact quotes for the documented cryptocurrency
// universe.
//
// GET batch-crypto-quotes?short=true
func (n *QuoteNamespace) Cryptocurrencies(ctx context.Context) ([]QuoteShort, error) {
	var out []QuoteShort
	if err := n.client.getJSON(ctx, "batch-crypto-quotes", "batch-crypto-quotes", shortOnlyParams, &out); err != nil {
		return nil, err
	}
	return out, nil
}

// Forex retrieves compact quotes for the documented forex universe.
//
// GET batch-forex-quotes?short=true
func (n *QuoteNamespace) Forex(ctx context.Context) ([]QuoteShort, error) {
	var out []QuoteShort
	if err := n.client.getJSON(ctx, "batch-forex-quotes", "batch-forex-quotes", shortOnlyParams, &out); err != nil {
		return nil, err
	}
	return out, nil
}

// Indexes retrieves compact quotes for the documented index universe.
//
// GET batch-index-quotes?short=true
func (n *QuoteNamespace) Indexes(ctx context.Context) ([]QuoteShort, error) {
	var out []QuoteShort
	if err := n.client.getJSON(ctx, "batch-index-quotes", "batch-index-quotes", shortOnlyParams, &out); err != nil {
		return nil, err
	}
	return out, nil
}
