// Code generated by fmp-py-gen gen_go. DO NOT EDIT.

package fmp

// Endpoint methods of the sec_filings domain, generated from
// crates/fmp-py-gen/registry/sec_filings.toml and the wire contract read from
// crates/libfmp/src/endpoints (ADR 0030).

import (
	"context"
	"encoding/json/jsontext"
)

// SecFilingsNamespace groups the sec_filings endpoints. It is reached as
// Client.SecFilings and is valid only when obtained from a Client built by
// NewClient.
type SecFilingsNamespace struct {
	client *Client
}

func newSecFilingsNamespace(client *Client) SecFilingsNamespace {
	return SecFilingsNamespace{
		client: client,
	}
}

// AllIndustryClassificationsQuery holds the query parameters of the endpoints
// that take it: NewAllIndustryClassificationsQuery takes the required
// arguments and each With method sets an optional one. Values are validated
// when the request is built.
type AllIndustryClassificationsQuery struct {
	page  *uint32
	limit *uint32
}

// NewAllIndustryClassificationsQuery creates the query from its required
// arguments.
func NewAllIndustryClassificationsQuery() AllIndustryClassificationsQuery {
	return AllIndustryClassificationsQuery{}
}

// WithPage sets the optional page parameter and returns the updated query.
func (q AllIndustryClassificationsQuery) WithPage(page uint32) AllIndustryClassificationsQuery {
	q.page = &page
	return q
}

// Page returns the optional page parameter, or nil when it is unset.
func (q AllIndustryClassificationsQuery) Page() *uint32 {
	return q.page
}

// WithLimit sets the optional limit parameter and returns the updated query.
func (q AllIndustryClassificationsQuery) WithLimit(limit uint32) AllIndustryClassificationsQuery {
	q.limit = &limit
	return q
}

// Limit returns the optional limit parameter, or nil when it is unset.
func (q AllIndustryClassificationsQuery) Limit() *uint32 {
	return q.limit
}

func (q AllIndustryClassificationsQuery) params() ([]queryParam, error) {
	params := make([]queryParam, 0, 2)
	if q.page != nil {
		page, err := uint32Param("page", *q.page)
		if err != nil {
			return nil, err
		}
		params = append(params, page)
	}
	if q.limit != nil {
		limit, err := uint32Param("limit", *q.limit)
		if err != nil {
			return nil, err
		}
		params = append(params, limit)
	}
	return params, nil
}

// IndustryClassificationSearchQuery holds the query parameters of the
// endpoints that take it: NewIndustryClassificationSearchQuery takes the
// required arguments and each With method sets an optional one. Values are
// validated when the request is built.
type IndustryClassificationSearchQuery struct {
	symbol  *string
	cik     *string
	sicCode *string
}

// NewIndustryClassificationSearchQuery creates the query from its required
// arguments.
func NewIndustryClassificationSearchQuery() IndustryClassificationSearchQuery {
	return IndustryClassificationSearchQuery{}
}

// WithSymbol sets the optional symbol parameter and returns the updated query.
func (q IndustryClassificationSearchQuery) WithSymbol(symbol string) IndustryClassificationSearchQuery {
	q.symbol = &symbol
	return q
}

// Symbol returns the optional symbol parameter, or nil when it is unset.
func (q IndustryClassificationSearchQuery) Symbol() *string {
	return q.symbol
}

// WithCIK sets the optional cik parameter and returns the updated query.
func (q IndustryClassificationSearchQuery) WithCIK(cik string) IndustryClassificationSearchQuery {
	q.cik = &cik
	return q
}

// CIK returns the optional cik parameter, or nil when it is unset.
func (q IndustryClassificationSearchQuery) CIK() *string {
	return q.cik
}

// WithSicCode sets the optional sic_code parameter and returns the updated
// query.
func (q IndustryClassificationSearchQuery) WithSicCode(sicCode string) IndustryClassificationSearchQuery {
	q.sicCode = &sicCode
	return q
}

// SicCode returns the optional sic_code parameter, or nil when it is unset.
func (q IndustryClassificationSearchQuery) SicCode() *string {
	return q.sicCode
}

func (q IndustryClassificationSearchQuery) params() ([]queryParam, error) {
	params := make([]queryParam, 0, 3)
	if q.symbol != nil {
		symbol, err := tickerParam("symbol", *q.symbol)
		if err != nil {
			return nil, err
		}
		params = append(params, symbol)
	}
	if q.cik != nil {
		cik, err := stringParam("cik", *q.cik)
		if err != nil {
			return nil, err
		}
		params = append(params, cik)
	}
	if q.sicCode != nil {
		sicCode, err := stringParam("sicCode", *q.sicCode)
		if err != nil {
			return nil, err
		}
		params = append(params, sicCode)
	}
	return params, nil
}

// IndustryClassificationsQuery holds the query parameters of the endpoints
// that take it: NewIndustryClassificationsQuery takes the required arguments
// and each With method sets an optional one. Values are validated when the
// request is built.
type IndustryClassificationsQuery struct {
	industryTitle *string
	sicCode       *string
}

// NewIndustryClassificationsQuery creates the query from its required
// arguments.
func NewIndustryClassificationsQuery() IndustryClassificationsQuery {
	return IndustryClassificationsQuery{}
}

// WithIndustryTitle sets the optional industry_title parameter and returns the
// updated query.
func (q IndustryClassificationsQuery) WithIndustryTitle(industryTitle string) IndustryClassificationsQuery {
	q.industryTitle = &industryTitle
	return q
}

// IndustryTitle returns the optional industry_title parameter, or nil when it
// is unset.
func (q IndustryClassificationsQuery) IndustryTitle() *string {
	return q.industryTitle
}

// WithSicCode sets the optional sic_code parameter and returns the updated
// query.
func (q IndustryClassificationsQuery) WithSicCode(sicCode string) IndustryClassificationsQuery {
	q.sicCode = &sicCode
	return q
}

// SicCode returns the optional sic_code parameter, or nil when it is unset.
func (q IndustryClassificationsQuery) SicCode() *string {
	return q.sicCode
}

func (q IndustryClassificationsQuery) params() ([]queryParam, error) {
	params := make([]queryParam, 0, 2)
	if q.industryTitle != nil {
		industryTitle, err := stringParam("industryTitle", *q.industryTitle)
		if err != nil {
			return nil, err
		}
		params = append(params, industryTitle)
	}
	if q.sicCode != nil {
		sicCode, err := stringParam("sicCode", *q.sicCode)
		if err != nil {
			return nil, err
		}
		params = append(params, sicCode)
	}
	return params, nil
}

// Latest8kSecFilingsQuery holds the query parameters of the endpoints that
// take it: NewLatest8kSecFilingsQuery takes the required arguments and each
// With method sets an optional one. Values are validated when the request is
// built.
type Latest8kSecFilingsQuery struct {
	from  Date
	to    Date
	page  *uint32
	limit *uint32
}

// NewLatest8kSecFilingsQuery creates the query from its required arguments.
func NewLatest8kSecFilingsQuery(from Date, to Date) Latest8kSecFilingsQuery {
	return Latest8kSecFilingsQuery{from: from, to: to}
}

// From returns the from argument as given.
func (q Latest8kSecFilingsQuery) From() Date {
	return q.from
}

// To returns the to argument as given.
func (q Latest8kSecFilingsQuery) To() Date {
	return q.to
}

// WithPage sets the optional page parameter and returns the updated query.
func (q Latest8kSecFilingsQuery) WithPage(page uint32) Latest8kSecFilingsQuery {
	q.page = &page
	return q
}

// Page returns the optional page parameter, or nil when it is unset.
func (q Latest8kSecFilingsQuery) Page() *uint32 {
	return q.page
}

// WithLimit sets the optional limit parameter and returns the updated query.
func (q Latest8kSecFilingsQuery) WithLimit(limit uint32) Latest8kSecFilingsQuery {
	q.limit = &limit
	return q
}

// Limit returns the optional limit parameter, or nil when it is unset.
func (q Latest8kSecFilingsQuery) Limit() *uint32 {
	return q.limit
}

func (q Latest8kSecFilingsQuery) params() ([]queryParam, error) {
	params := make([]queryParam, 0, 4)
	from, err := dateParam("from", q.from)
	if err != nil {
		return nil, err
	}
	params = append(params, from)
	to, err := dateParam("to", q.to)
	if err != nil {
		return nil, err
	}
	params = append(params, to)
	if q.page != nil {
		page, err := uint32Param("page", *q.page)
		if err != nil {
			return nil, err
		}
		params = append(params, page)
	}
	if q.limit != nil {
		limit, err := uint32Param("limit", *q.limit)
		if err != nil {
			return nil, err
		}
		params = append(params, limit)
	}
	return params, nil
}

// LatestSecFilingsQuery holds the query parameters of the endpoints that take
// it: NewLatestSecFilingsQuery takes the required arguments and each With
// method sets an optional one. Values are validated when the request is built.
type LatestSecFilingsQuery struct {
	from  Date
	to    Date
	page  *uint32
	limit *uint32
}

// NewLatestSecFilingsQuery creates the query from its required arguments.
func NewLatestSecFilingsQuery(from Date, to Date) LatestSecFilingsQuery {
	return LatestSecFilingsQuery{from: from, to: to}
}

// From returns the from argument as given.
func (q LatestSecFilingsQuery) From() Date {
	return q.from
}

// To returns the to argument as given.
func (q LatestSecFilingsQuery) To() Date {
	return q.to
}

// WithPage sets the optional page parameter and returns the updated query.
func (q LatestSecFilingsQuery) WithPage(page uint32) LatestSecFilingsQuery {
	q.page = &page
	return q
}

// Page returns the optional page parameter, or nil when it is unset.
func (q LatestSecFilingsQuery) Page() *uint32 {
	return q.page
}

// WithLimit sets the optional limit parameter and returns the updated query.
func (q LatestSecFilingsQuery) WithLimit(limit uint32) LatestSecFilingsQuery {
	q.limit = &limit
	return q
}

// Limit returns the optional limit parameter, or nil when it is unset.
func (q LatestSecFilingsQuery) Limit() *uint32 {
	return q.limit
}

func (q LatestSecFilingsQuery) params() ([]queryParam, error) {
	params := make([]queryParam, 0, 4)
	from, err := dateParam("from", q.from)
	if err != nil {
		return nil, err
	}
	params = append(params, from)
	to, err := dateParam("to", q.to)
	if err != nil {
		return nil, err
	}
	params = append(params, to)
	if q.page != nil {
		page, err := uint32Param("page", *q.page)
		if err != nil {
			return nil, err
		}
		params = append(params, page)
	}
	if q.limit != nil {
		limit, err := uint32Param("limit", *q.limit)
		if err != nil {
			return nil, err
		}
		params = append(params, limit)
	}
	return params, nil
}

// SecCompaniesByCIKQuery holds the query parameters of the endpoints that take
// it: NewSecCompaniesByCIKQuery takes the required arguments and each With
// method sets an optional one. Values are validated when the request is built.
type SecCompaniesByCIKQuery struct {
	cik string
}

// NewSecCompaniesByCIKQuery creates the query from its required arguments.
func NewSecCompaniesByCIKQuery(cik string) SecCompaniesByCIKQuery {
	return SecCompaniesByCIKQuery{cik: cik}
}

// CIK returns the cik argument as given.
func (q SecCompaniesByCIKQuery) CIK() string {
	return q.cik
}

func (q SecCompaniesByCIKQuery) params() ([]queryParam, error) {
	cik, err := stringParam("cik", q.cik)
	if err != nil {
		return nil, err
	}
	return []queryParam{cik}, nil
}

// SecCompaniesByNameQuery holds the query parameters of the endpoints that
// take it: NewSecCompaniesByNameQuery takes the required arguments and each
// With method sets an optional one. Values are validated when the request is
// built.
type SecCompaniesByNameQuery struct {
	company string
}

// NewSecCompaniesByNameQuery creates the query from its required arguments.
func NewSecCompaniesByNameQuery(company string) SecCompaniesByNameQuery {
	return SecCompaniesByNameQuery{company: company}
}

// Company returns the company argument as given.
func (q SecCompaniesByNameQuery) Company() string {
	return q.company
}

func (q SecCompaniesByNameQuery) params() ([]queryParam, error) {
	company, err := stringParam("company", q.company)
	if err != nil {
		return nil, err
	}
	return []queryParam{company}, nil
}

// SecCompaniesBySymbolQuery holds the query parameters of the endpoints that
// take it: NewSecCompaniesBySymbolQuery takes the required arguments and each
// With method sets an optional one. Values are validated when the request is
// built.
type SecCompaniesBySymbolQuery struct {
	symbol string
}

// NewSecCompaniesBySymbolQuery creates the query from its required arguments.
func NewSecCompaniesBySymbolQuery(symbol string) SecCompaniesBySymbolQuery {
	return SecCompaniesBySymbolQuery{symbol: symbol}
}

// Symbol returns the symbol argument as given.
func (q SecCompaniesBySymbolQuery) Symbol() string {
	return q.symbol
}

func (q SecCompaniesBySymbolQuery) params() ([]queryParam, error) {
	symbol, err := tickerParam("symbol", q.symbol)
	if err != nil {
		return nil, err
	}
	return []queryParam{symbol}, nil
}

// SecCompanyProfileQuery holds the query parameters of the endpoints that take
// it: NewSecCompanyProfileQuery takes the required arguments and each With
// method sets an optional one. Values are validated when the request is built.
type SecCompanyProfileQuery struct {
	symbol string
	cikA   *string
}

// NewSecCompanyProfileQuery creates the query from its required arguments.
func NewSecCompanyProfileQuery(symbol string) SecCompanyProfileQuery {
	return SecCompanyProfileQuery{symbol: symbol}
}

// Symbol returns the symbol argument as given.
func (q SecCompanyProfileQuery) Symbol() string {
	return q.symbol
}

// WithCIKA sets the optional cik_a parameter and returns the updated query.
func (q SecCompanyProfileQuery) WithCIKA(cikA string) SecCompanyProfileQuery {
	q.cikA = &cikA
	return q
}

// CIKA returns the optional cik_a parameter, or nil when it is unset.
func (q SecCompanyProfileQuery) CIKA() *string {
	return q.cikA
}

func (q SecCompanyProfileQuery) params() ([]queryParam, error) {
	params := make([]queryParam, 0, 2)
	symbol, err := tickerParam("symbol", q.symbol)
	if err != nil {
		return nil, err
	}
	params = append(params, symbol)
	if q.cikA != nil {
		cikA, err := stringParam("cik-A", *q.cikA)
		if err != nil {
			return nil, err
		}
		params = append(params, cikA)
	}
	return params, nil
}

// SecFilingsByCIKQuery holds the query parameters of the endpoints that take
// it: NewSecFilingsByCIKQuery takes the required arguments and each With
// method sets an optional one. Values are validated when the request is built.
type SecFilingsByCIKQuery struct {
	cik   string
	from  Date
	to    Date
	page  *uint32
	limit *uint32
}

// NewSecFilingsByCIKQuery creates the query from its required arguments.
func NewSecFilingsByCIKQuery(cik string, from Date, to Date) SecFilingsByCIKQuery {
	return SecFilingsByCIKQuery{cik: cik, from: from, to: to}
}

// CIK returns the cik argument as given.
func (q SecFilingsByCIKQuery) CIK() string {
	return q.cik
}

// From returns the from argument as given.
func (q SecFilingsByCIKQuery) From() Date {
	return q.from
}

// To returns the to argument as given.
func (q SecFilingsByCIKQuery) To() Date {
	return q.to
}

// WithPage sets the optional page parameter and returns the updated query.
func (q SecFilingsByCIKQuery) WithPage(page uint32) SecFilingsByCIKQuery {
	q.page = &page
	return q
}

// Page returns the optional page parameter, or nil when it is unset.
func (q SecFilingsByCIKQuery) Page() *uint32 {
	return q.page
}

// WithLimit sets the optional limit parameter and returns the updated query.
func (q SecFilingsByCIKQuery) WithLimit(limit uint32) SecFilingsByCIKQuery {
	q.limit = &limit
	return q
}

// Limit returns the optional limit parameter, or nil when it is unset.
func (q SecFilingsByCIKQuery) Limit() *uint32 {
	return q.limit
}

func (q SecFilingsByCIKQuery) params() ([]queryParam, error) {
	params := make([]queryParam, 0, 5)
	cik, err := stringParam("cik", q.cik)
	if err != nil {
		return nil, err
	}
	params = append(params, cik)
	from, err := dateParam("from", q.from)
	if err != nil {
		return nil, err
	}
	params = append(params, from)
	to, err := dateParam("to", q.to)
	if err != nil {
		return nil, err
	}
	params = append(params, to)
	if q.page != nil {
		page, err := uint32Param("page", *q.page)
		if err != nil {
			return nil, err
		}
		params = append(params, page)
	}
	if q.limit != nil {
		limit, err := uint32Param("limit", *q.limit)
		if err != nil {
			return nil, err
		}
		params = append(params, limit)
	}
	return params, nil
}

// SecFilingsByFormTypeQuery holds the query parameters of the endpoints that
// take it: NewSecFilingsByFormTypeQuery takes the required arguments and each
// With method sets an optional one. Values are validated when the request is
// built.
type SecFilingsByFormTypeQuery struct {
	formType string
	from     Date
	to       Date
	page     *uint32
	limit    *uint32
}

// NewSecFilingsByFormTypeQuery creates the query from its required arguments.
func NewSecFilingsByFormTypeQuery(formType string, from Date, to Date) SecFilingsByFormTypeQuery {
	return SecFilingsByFormTypeQuery{formType: formType, from: from, to: to}
}

// FormType returns the form_type argument as given.
func (q SecFilingsByFormTypeQuery) FormType() string {
	return q.formType
}

// From returns the from argument as given.
func (q SecFilingsByFormTypeQuery) From() Date {
	return q.from
}

// To returns the to argument as given.
func (q SecFilingsByFormTypeQuery) To() Date {
	return q.to
}

// WithPage sets the optional page parameter and returns the updated query.
func (q SecFilingsByFormTypeQuery) WithPage(page uint32) SecFilingsByFormTypeQuery {
	q.page = &page
	return q
}

// Page returns the optional page parameter, or nil when it is unset.
func (q SecFilingsByFormTypeQuery) Page() *uint32 {
	return q.page
}

// WithLimit sets the optional limit parameter and returns the updated query.
func (q SecFilingsByFormTypeQuery) WithLimit(limit uint32) SecFilingsByFormTypeQuery {
	q.limit = &limit
	return q
}

// Limit returns the optional limit parameter, or nil when it is unset.
func (q SecFilingsByFormTypeQuery) Limit() *uint32 {
	return q.limit
}

func (q SecFilingsByFormTypeQuery) params() ([]queryParam, error) {
	params := make([]queryParam, 0, 5)
	formType, err := stringParam("formType", q.formType)
	if err != nil {
		return nil, err
	}
	params = append(params, formType)
	from, err := dateParam("from", q.from)
	if err != nil {
		return nil, err
	}
	params = append(params, from)
	to, err := dateParam("to", q.to)
	if err != nil {
		return nil, err
	}
	params = append(params, to)
	if q.page != nil {
		page, err := uint32Param("page", *q.page)
		if err != nil {
			return nil, err
		}
		params = append(params, page)
	}
	if q.limit != nil {
		limit, err := uint32Param("limit", *q.limit)
		if err != nil {
			return nil, err
		}
		params = append(params, limit)
	}
	return params, nil
}

// SecFilingsBySymbolQuery holds the query parameters of the endpoints that
// take it: NewSecFilingsBySymbolQuery takes the required arguments and each
// With method sets an optional one. Values are validated when the request is
// built.
type SecFilingsBySymbolQuery struct {
	symbol string
	from   Date
	to     Date
	page   *uint32
	limit  *uint32
}

// NewSecFilingsBySymbolQuery creates the query from its required arguments.
func NewSecFilingsBySymbolQuery(symbol string, from Date, to Date) SecFilingsBySymbolQuery {
	return SecFilingsBySymbolQuery{symbol: symbol, from: from, to: to}
}

// Symbol returns the symbol argument as given.
func (q SecFilingsBySymbolQuery) Symbol() string {
	return q.symbol
}

// From returns the from argument as given.
func (q SecFilingsBySymbolQuery) From() Date {
	return q.from
}

// To returns the to argument as given.
func (q SecFilingsBySymbolQuery) To() Date {
	return q.to
}

// WithPage sets the optional page parameter and returns the updated query.
func (q SecFilingsBySymbolQuery) WithPage(page uint32) SecFilingsBySymbolQuery {
	q.page = &page
	return q
}

// Page returns the optional page parameter, or nil when it is unset.
func (q SecFilingsBySymbolQuery) Page() *uint32 {
	return q.page
}

// WithLimit sets the optional limit parameter and returns the updated query.
func (q SecFilingsBySymbolQuery) WithLimit(limit uint32) SecFilingsBySymbolQuery {
	q.limit = &limit
	return q
}

// Limit returns the optional limit parameter, or nil when it is unset.
func (q SecFilingsBySymbolQuery) Limit() *uint32 {
	return q.limit
}

func (q SecFilingsBySymbolQuery) params() ([]queryParam, error) {
	params := make([]queryParam, 0, 5)
	symbol, err := tickerParam("symbol", q.symbol)
	if err != nil {
		return nil, err
	}
	params = append(params, symbol)
	from, err := dateParam("from", q.from)
	if err != nil {
		return nil, err
	}
	params = append(params, from)
	to, err := dateParam("to", q.to)
	if err != nil {
		return nil, err
	}
	params = append(params, to)
	if q.page != nil {
		page, err := uint32Param("page", *q.page)
		if err != nil {
			return nil, err
		}
		params = append(params, page)
	}
	if q.limit != nil {
		limit, err := uint32Param("limit", *q.limit)
		if err != nil {
			return nil, err
		}
		params = append(params, limit)
	}
	return params, nil
}

// Latest8k retrieves the latest US 8-K SEC filings within the required date
// range.
//
// GET sec-filings-8k?from=&to=&page=&limit=
func (n *SecFilingsNamespace) Latest8k(ctx context.Context, q Latest8kSecFilingsQuery) ([]SecFiling, error) {
	params, err := q.params()
	if err != nil {
		return nil, err
	}
	var out []SecFiling
	if err := n.client.getJSON(ctx, "sec-filings-8k", "sec-filings-8k", params, &out); err != nil {
		return nil, err
	}
	return out, nil
}

// Latest retrieves the latest US financial SEC filings within the required
// date range.
//
// GET sec-filings-financials?from=&to=&page=&limit=
func (n *SecFilingsNamespace) Latest(ctx context.Context, q LatestSecFilingsQuery) ([]SecFiling, error) {
	params, err := q.params()
	if err != nil {
		return nil, err
	}
	var out []SecFiling
	if err := n.client.getJSON(ctx, "sec-filings-financials", "sec-filings-financials", params, &out); err != nil {
		return nil, err
	}
	return out, nil
}

// ByFormType retrieves US SEC filings by their open form type.
//
// GET sec-filings-search/form-type?formType=&from=&to=&page=&limit=
func (n *SecFilingsNamespace) ByFormType(ctx context.Context, q SecFilingsByFormTypeQuery) ([]SecFiling, error) {
	params, err := q.params()
	if err != nil {
		return nil, err
	}
	var out []SecFiling
	if err := n.client.getJSON(ctx, "sec-filings-search/form-type", "sec-filings-search/form-type", params, &out); err != nil {
		return nil, err
	}
	return out, nil
}

// BySymbol retrieves US SEC filings for a ticker.
//
// GET sec-filings-search/symbol?symbol=&from=&to=&page=&limit=
func (n *SecFilingsNamespace) BySymbol(ctx context.Context, q SecFilingsBySymbolQuery) ([]SecFiling, error) {
	params, err := q.params()
	if err != nil {
		return nil, err
	}
	var out []SecFiling
	if err := n.client.getJSON(ctx, "sec-filings-search/symbol", "sec-filings-search/symbol", params, &out); err != nil {
		return nil, err
	}
	return out, nil
}

// ByCIK retrieves US SEC filings for a string-backed CIK.
//
// GET sec-filings-search/cik?cik=&from=&to=&page=&limit=
func (n *SecFilingsNamespace) ByCIK(ctx context.Context, q SecFilingsByCIKQuery) ([]SecFiling, error) {
	params, err := q.params()
	if err != nil {
		return nil, err
	}
	var out []SecFiling
	if err := n.client.getJSON(ctx, "sec-filings-search/cik", "sec-filings-search/cik", params, &out); err != nil {
		return nil, err
	}
	return out, nil
}

// SearchCompaniesByName searches US SEC companies by company-name text.
//
// GET sec-filings-company-search/name?company=
func (n *SecFilingsNamespace) SearchCompaniesByName(ctx context.Context, q SecCompaniesByNameQuery) ([]SecCompanySearchResult, error) {
	params, err := q.params()
	if err != nil {
		return nil, err
	}
	var out []SecCompanySearchResult
	if err := n.client.getJSON(ctx, "sec-filings-company-search/name", "sec-filings-company-search/name", params, &out); err != nil {
		return nil, err
	}
	return out, nil
}

// SearchCompaniesBySymbol searches US SEC companies by ticker.
//
// GET sec-filings-company-search/symbol?symbol=
func (n *SecFilingsNamespace) SearchCompaniesBySymbol(ctx context.Context, q SecCompaniesBySymbolQuery) ([]SecCompanySearchResult, error) {
	params, err := q.params()
	if err != nil {
		return nil, err
	}
	var out []SecCompanySearchResult
	if err := n.client.getJSON(ctx, "sec-filings-company-search/symbol", "sec-filings-company-search/symbol", params, &out); err != nil {
		return nil, err
	}
	return out, nil
}

// SearchCompaniesByCIK searches US SEC companies by string-backed CIK.
//
// GET sec-filings-company-search/cik?cik=
func (n *SecFilingsNamespace) SearchCompaniesByCIK(ctx context.Context, q SecCompaniesByCIKQuery) ([]SecCompanySearchResult, error) {
	params, err := q.params()
	if err != nil {
		return nil, err
	}
	var out []SecCompanySearchResult
	if err := n.client.getJSON(ctx, "sec-filings-company-search/cik", "sec-filings-company-search/cik", params, &out); err != nil {
		return nil, err
	}
	return out, nil
}

// CompanyProfile retrieves the full US SEC company profile for a ticker.
//
// GET sec-profile?symbol=&cik-A=
func (n *SecFilingsNamespace) CompanyProfile(ctx context.Context, q SecCompanyProfileQuery) ([]SecCompanyProfile, error) {
	params, err := q.params()
	if err != nil {
		return nil, err
	}
	var out []SecCompanyProfile
	if err := n.client.getJSON(ctx, "sec-profile", "sec-profile", params, &out); err != nil {
		return nil, err
	}
	return out, nil
}

// IndustryClassifications retrieves the US Standard Industrial Classification
// directory.
//
// GET standard-industrial-classification-list?industryTitle=&sicCode=
func (n *SecFilingsNamespace) IndustryClassifications(ctx context.Context, q IndustryClassificationsQuery) ([]SicClassification, error) {
	params, err := q.params()
	if err != nil {
		return nil, err
	}
	var out []SicClassification
	if err := n.client.getJSON(ctx, "standard-industrial-classification-list", "standard-industrial-classification-list", params, &out); err != nil {
		return nil, err
	}
	return out, nil
}

// AllIndustryClassifications retrieves the paginated US company
// industry-classification feed.
//
// GET all-industry-classification?page=&limit=
func (n *SecFilingsNamespace) AllIndustryClassifications(ctx context.Context, q AllIndustryClassificationsQuery) ([]SecCompanySearchResult, error) {
	params, err := q.params()
	if err != nil {
		return nil, err
	}
	var out []SecCompanySearchResult
	if err := n.client.getJSON(ctx, "all-industry-classification", "all-industry-classification", params, &out); err != nil {
		return nil, err
	}
	return out, nil
}

// SearchIndustryClassifications searches US industry classifications while
// preserving raw documented rows.
//
// GET industry-classification-search?symbol=&cik=&sicCode=
func (n *SecFilingsNamespace) SearchIndustryClassifications(ctx context.Context, q IndustryClassificationSearchQuery) ([]jsontext.Value, error) {
	params, err := q.params()
	if err != nil {
		return nil, err
	}
	var out []jsontext.Value
	if err := n.client.getJSON(ctx, "industry-classification-search", "industry-classification-search", params, &out); err != nil {
		return nil, err
	}
	if err := requireObjectRows("industry-classification-search", out); err != nil {
		return nil, err
	}
	return out, nil
}
