// Code generated by fmp-py-gen gen_go. DO NOT EDIT.

package fmp

// Response models of the sec_filings domain, generated from the
// crates/libfmp/src/responses/sec_filings module with the ADR 0030 type table.

import (
	"encoding/json/jsontext"
	"encoding/json/v2"
)

// SECFiling is one SEC filing row shared by all five filing feeds and
// searches.
type SECFiling struct {
	Symbol        string   `json:"symbol"`
	CIK           string   `json:"cik"`
	FilingDate    DateTime `json:"filingDate"`
	AcceptedDate  DateTime `json:"acceptedDate"`
	FormType      string   `json:"formType"`
	HasFinancials *bool    `json:"hasFinancials"`
	Link          string   `json:"link"`
	FinalLink     string   `json:"finalLink"`
}

// secFilingShadow mirrors SECFiling with a pointer or raw value for every
// required member so a missing or null member is observable after decoding.
type secFilingShadow struct {
	Symbol        *string   `json:"symbol"`
	CIK           *string   `json:"cik"`
	FilingDate    *DateTime `json:"filingDate"`
	AcceptedDate  *DateTime `json:"acceptedDate"`
	FormType      *string   `json:"formType"`
	HasFinancials *bool     `json:"hasFinancials"`
	Link          *string   `json:"link"`
	FinalLink     *string   `json:"finalLink"`
}

// UnmarshalJSONFrom decodes one JSON object and rejects it with a Decode
// error naming the first required member that is missing or null, as the
// Rust decoder does. Unknown members are ignored.
func (m *SECFiling) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	var shadow secFilingShadow
	if err := json.UnmarshalDecode(dec, &shadow); err != nil {
		return err
	}
	switch {
	case shadow.Symbol == nil:
		return missingMemberError("SECFiling", "symbol")
	case shadow.CIK == nil:
		return missingMemberError("SECFiling", "cik")
	case shadow.FilingDate == nil:
		return missingMemberError("SECFiling", "filingDate")
	case shadow.AcceptedDate == nil:
		return missingMemberError("SECFiling", "acceptedDate")
	case shadow.FormType == nil:
		return missingMemberError("SECFiling", "formType")
	case shadow.Link == nil:
		return missingMemberError("SECFiling", "link")
	case shadow.FinalLink == nil:
		return missingMemberError("SECFiling", "finalLink")
	}
	*m = SECFiling{
		Symbol:        *shadow.Symbol,
		CIK:           *shadow.CIK,
		FilingDate:    *shadow.FilingDate,
		AcceptedDate:  *shadow.AcceptedDate,
		FormType:      *shadow.FormType,
		HasFinancials: shadow.HasFinancials,
		Link:          *shadow.Link,
		FinalLink:     *shadow.FinalLink,
	}
	return nil
}

// SECCompanySearchResult is one company identity returned by the three SEC
// company-search routes.
type SECCompanySearchResult struct {
	Symbol          string  `json:"symbol"`
	Name            string  `json:"name"`
	CIK             string  `json:"cik"`
	SicCode         string  `json:"sicCode"`
	IndustryTitle   string  `json:"industryTitle"`
	BusinessAddress string  `json:"businessAddress"`
	PhoneNumber     *string `json:"phoneNumber"`
}

// secCompanySearchResultShadow mirrors SECCompanySearchResult with a pointer
// or raw value for every required member so a missing or null member is
// observable after decoding.
type secCompanySearchResultShadow struct {
	Symbol          *string        `json:"symbol"`
	Name            *string        `json:"name"`
	CIK             *string        `json:"cik"`
	SicCode         *string        `json:"sicCode"`
	IndustryTitle   *string        `json:"industryTitle"`
	BusinessAddress *string        `json:"businessAddress"`
	PhoneNumber     jsontext.Value `json:"phoneNumber"`
}

// UnmarshalJSONFrom decodes one JSON object and rejects it with a Decode
// error naming the first required member that is missing or null, as the
// Rust decoder does. Unknown members are ignored.
func (m *SECCompanySearchResult) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	var shadow secCompanySearchResultShadow
	if err := json.UnmarshalDecode(dec, &shadow); err != nil {
		return err
	}
	switch {
	case shadow.Symbol == nil:
		return missingMemberError("SECCompanySearchResult", "symbol")
	case shadow.Name == nil:
		return missingMemberError("SECCompanySearchResult", "name")
	case shadow.CIK == nil:
		return missingMemberError("SECCompanySearchResult", "cik")
	case shadow.SicCode == nil:
		return missingMemberError("SECCompanySearchResult", "sicCode")
	case shadow.IndustryTitle == nil:
		return missingMemberError("SECCompanySearchResult", "industryTitle")
	case shadow.BusinessAddress == nil:
		return missingMemberError("SECCompanySearchResult", "businessAddress")
	case len(shadow.PhoneNumber) == 0:
		return missingMemberError("SECCompanySearchResult", "phoneNumber")
	}
	var phoneNumber *string
	if shadow.PhoneNumber.Kind() != 'n' {
		var value string
		if err := json.Unmarshal(shadow.PhoneNumber, &value); err != nil {
			return memberDecodeError("SECCompanySearchResult", "phoneNumber", shadow.PhoneNumber, err)
		}
		phoneNumber = &value
	}
	*m = SECCompanySearchResult{
		Symbol:          *shadow.Symbol,
		Name:            *shadow.Name,
		CIK:             *shadow.CIK,
		SicCode:         *shadow.SicCode,
		IndustryTitle:   *shadow.IndustryTitle,
		BusinessAddress: *shadow.BusinessAddress,
		PhoneNumber:     phoneNumber,
	}
	return nil
}

// SECCompanyProfile is one full SEC company profile.
type SECCompanyProfile struct {
	Symbol                  string          `json:"symbol"`
	CIK                     string          `json:"cik"`
	RegistrantName          string          `json:"registrantName"`
	SicCode                 string          `json:"sicCode"`
	SicDescription          string          `json:"sicDescription"`
	SicGroup                string          `json:"sicGroup"`
	ISIN                    string          `json:"isin"`
	BusinessAddress         string          `json:"businessAddress"`
	MailingAddress          string          `json:"mailingAddress"`
	PhoneNumber             string          `json:"phoneNumber"`
	PostalCode              string          `json:"postalCode"`
	City                    string          `json:"city"`
	State                   string          `json:"state"`
	Country                 string          `json:"country"`
	Description             string          `json:"description"`
	Ceo                     string          `json:"ceo"`
	Website                 string          `json:"website"`
	Exchange                string          `json:"exchange"`
	StateLocation           string          `json:"stateLocation"`
	StateOfIncorporation    string          `json:"stateOfIncorporation"`
	FiscalYearEnd           *string         `json:"fiscalYearEnd"`
	IPODate                 Date            `json:"ipoDate"`
	Employees               *string         `json:"employees"`
	SECFilingsURL           string          `json:"secFilingsUrl"`
	TaxIdentificationNumber string          `json:"taxIdentificationNumber"`
	FiftyTwoWeekRange       string          `json:"fiftyTwoWeekRange"`
	IsActive                bool            `json:"isActive"`
	AssetType               string          `json:"assetType"`
	OpenFigiComposite       string          `json:"openFigiComposite"`
	PriceCurrency           string          `json:"priceCurrency"`
	MarketSector            string          `json:"marketSector"`
	SecurityType            *jsontext.Value `json:"securityType"`
	IsETF                   bool            `json:"isEtf"`
	IsAdr                   bool            `json:"isAdr"`
	IsFund                  bool            `json:"isFund"`
}

// secCompanyProfileShadow mirrors SECCompanyProfile with a pointer or raw
// value for every required member so a missing or null member is observable
// after decoding.
type secCompanyProfileShadow struct {
	Symbol                  *string        `json:"symbol"`
	CIK                     *string        `json:"cik"`
	RegistrantName          *string        `json:"registrantName"`
	SicCode                 *string        `json:"sicCode"`
	SicDescription          *string        `json:"sicDescription"`
	SicGroup                *string        `json:"sicGroup"`
	ISIN                    *string        `json:"isin"`
	BusinessAddress         *string        `json:"businessAddress"`
	MailingAddress          *string        `json:"mailingAddress"`
	PhoneNumber             *string        `json:"phoneNumber"`
	PostalCode              *string        `json:"postalCode"`
	City                    *string        `json:"city"`
	State                   *string        `json:"state"`
	Country                 *string        `json:"country"`
	Description             *string        `json:"description"`
	Ceo                     *string        `json:"ceo"`
	Website                 *string        `json:"website"`
	Exchange                *string        `json:"exchange"`
	StateLocation           *string        `json:"stateLocation"`
	StateOfIncorporation    *string        `json:"stateOfIncorporation"`
	FiscalYearEnd           jsontext.Value `json:"fiscalYearEnd"`
	IPODate                 *Date          `json:"ipoDate"`
	Employees               jsontext.Value `json:"employees"`
	SECFilingsURL           *string        `json:"secFilingsUrl"`
	TaxIdentificationNumber *string        `json:"taxIdentificationNumber"`
	FiftyTwoWeekRange       *string        `json:"fiftyTwoWeekRange"`
	IsActive                *bool          `json:"isActive"`
	AssetType               *string        `json:"assetType"`
	OpenFigiComposite       *string        `json:"openFigiComposite"`
	PriceCurrency           *string        `json:"priceCurrency"`
	MarketSector            *string        `json:"marketSector"`
	SecurityType            jsontext.Value `json:"securityType"`
	IsETF                   *bool          `json:"isEtf"`
	IsAdr                   *bool          `json:"isAdr"`
	IsFund                  *bool          `json:"isFund"`
}

// UnmarshalJSONFrom decodes one JSON object and rejects it with a Decode
// error naming the first required member that is missing or null, as the
// Rust decoder does. Unknown members are ignored.
func (m *SECCompanyProfile) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	var shadow secCompanyProfileShadow
	if err := json.UnmarshalDecode(dec, &shadow); err != nil {
		return err
	}
	switch {
	case shadow.Symbol == nil:
		return missingMemberError("SECCompanyProfile", "symbol")
	case shadow.CIK == nil:
		return missingMemberError("SECCompanyProfile", "cik")
	case shadow.RegistrantName == nil:
		return missingMemberError("SECCompanyProfile", "registrantName")
	case shadow.SicCode == nil:
		return missingMemberError("SECCompanyProfile", "sicCode")
	case shadow.SicDescription == nil:
		return missingMemberError("SECCompanyProfile", "sicDescription")
	case shadow.SicGroup == nil:
		return missingMemberError("SECCompanyProfile", "sicGroup")
	case shadow.ISIN == nil:
		return missingMemberError("SECCompanyProfile", "isin")
	case shadow.BusinessAddress == nil:
		return missingMemberError("SECCompanyProfile", "businessAddress")
	case shadow.MailingAddress == nil:
		return missingMemberError("SECCompanyProfile", "mailingAddress")
	case shadow.PhoneNumber == nil:
		return missingMemberError("SECCompanyProfile", "phoneNumber")
	case shadow.PostalCode == nil:
		return missingMemberError("SECCompanyProfile", "postalCode")
	case shadow.City == nil:
		return missingMemberError("SECCompanyProfile", "city")
	case shadow.State == nil:
		return missingMemberError("SECCompanyProfile", "state")
	case shadow.Country == nil:
		return missingMemberError("SECCompanyProfile", "country")
	case shadow.Description == nil:
		return missingMemberError("SECCompanyProfile", "description")
	case shadow.Ceo == nil:
		return missingMemberError("SECCompanyProfile", "ceo")
	case shadow.Website == nil:
		return missingMemberError("SECCompanyProfile", "website")
	case shadow.Exchange == nil:
		return missingMemberError("SECCompanyProfile", "exchange")
	case shadow.StateLocation == nil:
		return missingMemberError("SECCompanyProfile", "stateLocation")
	case shadow.StateOfIncorporation == nil:
		return missingMemberError("SECCompanyProfile", "stateOfIncorporation")
	case len(shadow.FiscalYearEnd) == 0:
		return missingMemberError("SECCompanyProfile", "fiscalYearEnd")
	case shadow.IPODate == nil:
		return missingMemberError("SECCompanyProfile", "ipoDate")
	case len(shadow.Employees) == 0:
		return missingMemberError("SECCompanyProfile", "employees")
	case shadow.SECFilingsURL == nil:
		return missingMemberError("SECCompanyProfile", "secFilingsUrl")
	case shadow.TaxIdentificationNumber == nil:
		return missingMemberError("SECCompanyProfile", "taxIdentificationNumber")
	case shadow.FiftyTwoWeekRange == nil:
		return missingMemberError("SECCompanyProfile", "fiftyTwoWeekRange")
	case shadow.IsActive == nil:
		return missingMemberError("SECCompanyProfile", "isActive")
	case shadow.AssetType == nil:
		return missingMemberError("SECCompanyProfile", "assetType")
	case shadow.OpenFigiComposite == nil:
		return missingMemberError("SECCompanyProfile", "openFigiComposite")
	case shadow.PriceCurrency == nil:
		return missingMemberError("SECCompanyProfile", "priceCurrency")
	case shadow.MarketSector == nil:
		return missingMemberError("SECCompanyProfile", "marketSector")
	case len(shadow.SecurityType) == 0:
		return missingMemberError("SECCompanyProfile", "securityType")
	case shadow.IsETF == nil:
		return missingMemberError("SECCompanyProfile", "isEtf")
	case shadow.IsAdr == nil:
		return missingMemberError("SECCompanyProfile", "isAdr")
	case shadow.IsFund == nil:
		return missingMemberError("SECCompanyProfile", "isFund")
	}
	var fiscalYearEnd *string
	if shadow.FiscalYearEnd.Kind() != 'n' {
		var value string
		if err := json.Unmarshal(shadow.FiscalYearEnd, &value); err != nil {
			return memberDecodeError("SECCompanyProfile", "fiscalYearEnd", shadow.FiscalYearEnd, err)
		}
		fiscalYearEnd = &value
	}
	var employees *string
	if shadow.Employees.Kind() != 'n' {
		var value string
		if err := json.Unmarshal(shadow.Employees, &value); err != nil {
			return memberDecodeError("SECCompanyProfile", "employees", shadow.Employees, err)
		}
		employees = &value
	}
	var securityType *jsontext.Value
	if shadow.SecurityType.Kind() != 'n' {
		var value jsontext.Value
		if err := json.Unmarshal(shadow.SecurityType, &value); err != nil {
			return memberDecodeError("SECCompanyProfile", "securityType", shadow.SecurityType, err)
		}
		securityType = &value
	}
	*m = SECCompanyProfile{
		Symbol:                  *shadow.Symbol,
		CIK:                     *shadow.CIK,
		RegistrantName:          *shadow.RegistrantName,
		SicCode:                 *shadow.SicCode,
		SicDescription:          *shadow.SicDescription,
		SicGroup:                *shadow.SicGroup,
		ISIN:                    *shadow.ISIN,
		BusinessAddress:         *shadow.BusinessAddress,
		MailingAddress:          *shadow.MailingAddress,
		PhoneNumber:             *shadow.PhoneNumber,
		PostalCode:              *shadow.PostalCode,
		City:                    *shadow.City,
		State:                   *shadow.State,
		Country:                 *shadow.Country,
		Description:             *shadow.Description,
		Ceo:                     *shadow.Ceo,
		Website:                 *shadow.Website,
		Exchange:                *shadow.Exchange,
		StateLocation:           *shadow.StateLocation,
		StateOfIncorporation:    *shadow.StateOfIncorporation,
		FiscalYearEnd:           fiscalYearEnd,
		IPODate:                 *shadow.IPODate,
		Employees:               employees,
		SECFilingsURL:           *shadow.SECFilingsURL,
		TaxIdentificationNumber: *shadow.TaxIdentificationNumber,
		FiftyTwoWeekRange:       *shadow.FiftyTwoWeekRange,
		IsActive:                *shadow.IsActive,
		AssetType:               *shadow.AssetType,
		OpenFigiComposite:       *shadow.OpenFigiComposite,
		PriceCurrency:           *shadow.PriceCurrency,
		MarketSector:            *shadow.MarketSector,
		SecurityType:            securityType,
		IsETF:                   *shadow.IsETF,
		IsAdr:                   *shadow.IsAdr,
		IsFund:                  *shadow.IsFund,
	}
	return nil
}

// SicClassification is one Standard Industrial Classification directory row.
type SicClassification struct {
	Office        string `json:"office"`
	SicCode       string `json:"sicCode"`
	IndustryTitle string `json:"industryTitle"`
}

// sicClassificationShadow mirrors SicClassification with a pointer or raw
// value for every required member so a missing or null member is observable
// after decoding.
type sicClassificationShadow struct {
	Office        *string `json:"office"`
	SicCode       *string `json:"sicCode"`
	IndustryTitle *string `json:"industryTitle"`
}

// UnmarshalJSONFrom decodes one JSON object and rejects it with a Decode
// error naming the first required member that is missing or null, as the
// Rust decoder does. Unknown members are ignored.
func (m *SicClassification) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	var shadow sicClassificationShadow
	if err := json.UnmarshalDecode(dec, &shadow); err != nil {
		return err
	}
	switch {
	case shadow.Office == nil:
		return missingMemberError("SicClassification", "office")
	case shadow.SicCode == nil:
		return missingMemberError("SicClassification", "sicCode")
	case shadow.IndustryTitle == nil:
		return missingMemberError("SicClassification", "industryTitle")
	}
	*m = SicClassification{
		Office:        *shadow.Office,
		SicCode:       *shadow.SicCode,
		IndustryTitle: *shadow.IndustryTitle,
	}
	return nil
}
