// @generated by gen_models; do not edit by hand.

use pyo3::IntoPyObjectExt;
use pyo3::prelude::*;
use pyo3::types::PyTuple;
use pyo3_stub_gen::derive::{gen_stub_pyclass, gen_stub_pymethods};

#[gen_stub_pyclass]
#[pyclass(module = "fmp._native.statements.income", frozen, from_py_object)]
#[derive(Clone)]
pub(crate) struct IncomeStatement {
    #[pyo3(get)]
    pub date: ::chrono::NaiveDate,
    #[pyo3(get)]
    pub symbol: String,
    #[pyo3(get)]
    pub reported_currency: String,
    #[pyo3(get)]
    pub cik: String,
    #[pyo3(get)]
    pub filing_date: ::chrono::NaiveDate,
    #[pyo3(get)]
    pub accepted_date: ::chrono::NaiveDateTime,
    #[pyo3(get)]
    pub fiscal_year: String,
    #[pyo3(get)]
    pub period: String,
    #[pyo3(get)]
    pub revenue: f64,
    #[pyo3(get)]
    pub cost_of_revenue: f64,
    #[pyo3(get)]
    pub gross_profit: f64,
    #[pyo3(get)]
    pub research_and_development_expenses: f64,
    #[pyo3(get)]
    pub general_and_administrative_expenses: f64,
    #[pyo3(get)]
    pub selling_and_marketing_expenses: f64,
    #[pyo3(get)]
    pub selling_general_and_administrative_expenses: f64,
    #[pyo3(get)]
    pub other_expenses: f64,
    #[pyo3(get)]
    pub operating_expenses: f64,
    #[pyo3(get)]
    pub cost_and_expenses: f64,
    #[pyo3(get)]
    pub net_interest_income: f64,
    #[pyo3(get)]
    pub interest_income: f64,
    #[pyo3(get)]
    pub interest_expense: f64,
    #[pyo3(get)]
    pub depreciation_and_amortization: f64,
    #[pyo3(get)]
    pub ebitda: f64,
    #[pyo3(get)]
    pub ebit: f64,
    #[pyo3(get)]
    pub non_operating_income_excluding_interest: f64,
    #[pyo3(get)]
    pub operating_income: f64,
    #[pyo3(get)]
    pub total_other_income_expenses_net: f64,
    #[pyo3(get)]
    pub income_before_tax: f64,
    #[pyo3(get)]
    pub income_tax_expense: f64,
    #[pyo3(get)]
    pub net_income_from_continuing_operations: f64,
    #[pyo3(get)]
    pub net_income_from_discontinued_operations: f64,
    #[pyo3(get)]
    pub other_adjustments_to_net_income: f64,
    #[pyo3(get)]
    pub net_income: f64,
    #[pyo3(get)]
    pub net_income_deductions: f64,
    #[pyo3(get)]
    pub bottom_line_net_income: f64,
    #[pyo3(get)]
    pub eps: f64,
    #[pyo3(get)]
    pub eps_diluted: f64,
    #[pyo3(get)]
    pub weighted_average_shs_out: f64,
    #[pyo3(get)]
    pub weighted_average_shs_out_dil: f64,
}

#[gen_stub_pymethods]
#[pymethods]
impl IncomeStatement {
    #[new]
    #[allow(clippy::too_many_arguments)]
    #[allow(clippy::fn_params_excessive_bools)]
    #[pyo3(signature = (date, symbol, reported_currency, cik, filing_date, accepted_date, fiscal_year, period, revenue, cost_of_revenue, gross_profit, research_and_development_expenses, general_and_administrative_expenses, selling_and_marketing_expenses, selling_general_and_administrative_expenses, other_expenses, operating_expenses, cost_and_expenses, net_interest_income, interest_income, interest_expense, depreciation_and_amortization, ebitda, ebit, non_operating_income_excluding_interest, operating_income, total_other_income_expenses_net, income_before_tax, income_tax_expense, net_income_from_continuing_operations, net_income_from_discontinued_operations, other_adjustments_to_net_income, net_income, net_income_deductions, bottom_line_net_income, eps, eps_diluted, weighted_average_shs_out, weighted_average_shs_out_dil))]
    fn new(
        date: ::chrono::NaiveDate,
        symbol: String,
        reported_currency: String,
        cik: String,
        filing_date: ::chrono::NaiveDate,
        accepted_date: ::chrono::NaiveDateTime,
        fiscal_year: String,
        period: String,
        revenue: f64,
        cost_of_revenue: f64,
        gross_profit: f64,
        research_and_development_expenses: f64,
        general_and_administrative_expenses: f64,
        selling_and_marketing_expenses: f64,
        selling_general_and_administrative_expenses: f64,
        other_expenses: f64,
        operating_expenses: f64,
        cost_and_expenses: f64,
        net_interest_income: f64,
        interest_income: f64,
        interest_expense: f64,
        depreciation_and_amortization: f64,
        ebitda: f64,
        ebit: f64,
        non_operating_income_excluding_interest: f64,
        operating_income: f64,
        total_other_income_expenses_net: f64,
        income_before_tax: f64,
        income_tax_expense: f64,
        net_income_from_continuing_operations: f64,
        net_income_from_discontinued_operations: f64,
        other_adjustments_to_net_income: f64,
        net_income: f64,
        net_income_deductions: f64,
        bottom_line_net_income: f64,
        eps: f64,
        eps_diluted: f64,
        weighted_average_shs_out: f64,
        weighted_average_shs_out_dil: f64,
    ) -> Self {
        Self {
            date,
            symbol,
            reported_currency,
            cik,
            filing_date,
            accepted_date,
            fiscal_year,
            period,
            revenue,
            cost_of_revenue,
            gross_profit,
            research_and_development_expenses,
            general_and_administrative_expenses,
            selling_and_marketing_expenses,
            selling_general_and_administrative_expenses,
            other_expenses,
            operating_expenses,
            cost_and_expenses,
            net_interest_income,
            interest_income,
            interest_expense,
            depreciation_and_amortization,
            ebitda,
            ebit,
            non_operating_income_excluding_interest,
            operating_income,
            total_other_income_expenses_net,
            income_before_tax,
            income_tax_expense,
            net_income_from_continuing_operations,
            net_income_from_discontinued_operations,
            other_adjustments_to_net_income,
            net_income,
            net_income_deductions,
            bottom_line_net_income,
            eps,
            eps_diluted,
            weighted_average_shs_out,
            weighted_average_shs_out_dil,
        }
    }

    #[allow(clippy::clone_on_copy)]
    fn __getnewargs__<'py>(&self, py: Python<'py>) -> PyResult<Bound<'py, PyTuple>> {
        let members: Vec<Bound<'py, PyAny>> = vec![
            self.date.clone().into_bound_py_any(py)?,
            self.symbol.clone().into_bound_py_any(py)?,
            self.reported_currency.clone().into_bound_py_any(py)?,
            self.cik.clone().into_bound_py_any(py)?,
            self.filing_date.clone().into_bound_py_any(py)?,
            self.accepted_date.clone().into_bound_py_any(py)?,
            self.fiscal_year.clone().into_bound_py_any(py)?,
            self.period.clone().into_bound_py_any(py)?,
            self.revenue.clone().into_bound_py_any(py)?,
            self.cost_of_revenue.clone().into_bound_py_any(py)?,
            self.gross_profit.clone().into_bound_py_any(py)?,
            self.research_and_development_expenses
                .clone()
                .into_bound_py_any(py)?,
            self.general_and_administrative_expenses
                .clone()
                .into_bound_py_any(py)?,
            self.selling_and_marketing_expenses
                .clone()
                .into_bound_py_any(py)?,
            self.selling_general_and_administrative_expenses
                .clone()
                .into_bound_py_any(py)?,
            self.other_expenses.clone().into_bound_py_any(py)?,
            self.operating_expenses.clone().into_bound_py_any(py)?,
            self.cost_and_expenses.clone().into_bound_py_any(py)?,
            self.net_interest_income.clone().into_bound_py_any(py)?,
            self.interest_income.clone().into_bound_py_any(py)?,
            self.interest_expense.clone().into_bound_py_any(py)?,
            self.depreciation_and_amortization
                .clone()
                .into_bound_py_any(py)?,
            self.ebitda.clone().into_bound_py_any(py)?,
            self.ebit.clone().into_bound_py_any(py)?,
            self.non_operating_income_excluding_interest
                .clone()
                .into_bound_py_any(py)?,
            self.operating_income.clone().into_bound_py_any(py)?,
            self.total_other_income_expenses_net
                .clone()
                .into_bound_py_any(py)?,
            self.income_before_tax.clone().into_bound_py_any(py)?,
            self.income_tax_expense.clone().into_bound_py_any(py)?,
            self.net_income_from_continuing_operations
                .clone()
                .into_bound_py_any(py)?,
            self.net_income_from_discontinued_operations
                .clone()
                .into_bound_py_any(py)?,
            self.other_adjustments_to_net_income
                .clone()
                .into_bound_py_any(py)?,
            self.net_income.clone().into_bound_py_any(py)?,
            self.net_income_deductions.clone().into_bound_py_any(py)?,
            self.bottom_line_net_income.clone().into_bound_py_any(py)?,
            self.eps.clone().into_bound_py_any(py)?,
            self.eps_diluted.clone().into_bound_py_any(py)?,
            self.weighted_average_shs_out
                .clone()
                .into_bound_py_any(py)?,
            self.weighted_average_shs_out_dil
                .clone()
                .into_bound_py_any(py)?,
        ];
        PyTuple::new(py, members)
    }
}

impl From<libfmp::responses::statements::income::IncomeStatement> for IncomeStatement {
    fn from(value: libfmp::responses::statements::income::IncomeStatement) -> Self {
        Self {
            date: value.date.into_inner(),
            symbol: value.symbol.into_inner(),
            reported_currency: value.reported_currency.into_inner(),
            cik: value.cik.into_inner(),
            filing_date: value.filing_date.into_inner(),
            accepted_date: value.accepted_date.into_inner(),
            fiscal_year: value.fiscal_year.as_str().to_owned(),
            period: value.period.to_string(),
            revenue: value.revenue,
            cost_of_revenue: value.cost_of_revenue,
            gross_profit: value.gross_profit,
            research_and_development_expenses: value.research_and_development_expenses,
            general_and_administrative_expenses: value.general_and_administrative_expenses,
            selling_and_marketing_expenses: value.selling_and_marketing_expenses,
            selling_general_and_administrative_expenses: value
                .selling_general_and_administrative_expenses,
            other_expenses: value.other_expenses,
            operating_expenses: value.operating_expenses,
            cost_and_expenses: value.cost_and_expenses,
            net_interest_income: value.net_interest_income,
            interest_income: value.interest_income,
            interest_expense: value.interest_expense,
            depreciation_and_amortization: value.depreciation_and_amortization,
            ebitda: value.ebitda,
            ebit: value.ebit,
            non_operating_income_excluding_interest: value.non_operating_income_excluding_interest,
            operating_income: value.operating_income,
            total_other_income_expenses_net: value.total_other_income_expenses_net,
            income_before_tax: value.income_before_tax,
            income_tax_expense: value.income_tax_expense,
            net_income_from_continuing_operations: value.net_income_from_continuing_operations,
            net_income_from_discontinued_operations: value.net_income_from_discontinued_operations,
            other_adjustments_to_net_income: value.other_adjustments_to_net_income,
            net_income: value.net_income,
            net_income_deductions: value.net_income_deductions,
            bottom_line_net_income: value.bottom_line_net_income,
            eps: value.eps,
            eps_diluted: value.eps_diluted,
            weighted_average_shs_out: value.weighted_average_shs_out,
            weighted_average_shs_out_dil: value.weighted_average_shs_out_dil,
        }
    }
}
