// @generated by gen_models; do not edit by hand.

use pyo3::IntoPyObjectExt;
use pyo3::prelude::*;
use pyo3::types::PyTuple;
use pyo3_stub_gen::derive::{gen_stub_pyclass, gen_stub_pymethods};

#[gen_stub_pyclass]
#[pyclass(module = "fmp._native.statements.ratios", frozen, from_py_object)]
#[derive(Clone)]
pub(crate) struct FinancialRatios {
    #[pyo3(get)]
    pub symbol: String,
    #[pyo3(get)]
    pub date: ::chrono::NaiveDate,
    #[pyo3(get)]
    pub fiscal_year: String,
    #[pyo3(get)]
    pub period: String,
    #[pyo3(get)]
    pub reported_currency: String,
    #[pyo3(get)]
    pub gross_profit_margin: f64,
    #[pyo3(get)]
    pub ebit_margin: f64,
    #[pyo3(get)]
    pub ebitda_margin: f64,
    #[pyo3(get)]
    pub operating_profit_margin: f64,
    #[pyo3(get)]
    pub pretax_profit_margin: f64,
    #[pyo3(get)]
    pub continuous_operations_profit_margin: f64,
    #[pyo3(get)]
    pub net_profit_margin: f64,
    #[pyo3(get)]
    pub bottom_line_profit_margin: f64,
    #[pyo3(get)]
    pub receivables_turnover: f64,
    #[pyo3(get)]
    pub payables_turnover: f64,
    #[pyo3(get)]
    pub inventory_turnover: f64,
    #[pyo3(get)]
    pub fixed_asset_turnover: f64,
    #[pyo3(get)]
    pub asset_turnover: f64,
    #[pyo3(get)]
    pub current_ratio: f64,
    #[pyo3(get)]
    pub quick_ratio: f64,
    #[pyo3(get)]
    pub solvency_ratio: f64,
    #[pyo3(get)]
    pub cash_ratio: f64,
    #[pyo3(get)]
    pub price_to_earnings_ratio: f64,
    #[pyo3(get)]
    pub price_to_earnings_growth_ratio: f64,
    #[pyo3(get)]
    pub forward_price_to_earnings_growth_ratio: f64,
    #[pyo3(get)]
    pub price_to_earnings_diluted_ratio: f64,
    #[pyo3(get)]
    pub price_to_earnings_diluted_growth_ratio: f64,
    #[pyo3(get)]
    pub price_to_book_ratio: f64,
    #[pyo3(get)]
    pub price_to_sales_ratio: f64,
    #[pyo3(get)]
    pub price_to_free_cash_flow_ratio: f64,
    #[pyo3(get)]
    pub price_to_operating_cash_flow_ratio: f64,
    #[pyo3(get)]
    pub debt_to_assets_ratio: f64,
    #[pyo3(get)]
    pub debt_to_equity_ratio: f64,
    #[pyo3(get)]
    pub debt_to_capital_ratio: f64,
    #[pyo3(get)]
    pub long_term_debt_to_capital_ratio: f64,
    #[pyo3(get)]
    pub financial_leverage_ratio: f64,
    #[pyo3(get)]
    pub working_capital_turnover_ratio: f64,
    #[pyo3(get)]
    pub operating_cash_flow_ratio: f64,
    #[pyo3(get)]
    pub operating_cash_flow_sales_ratio: f64,
    #[pyo3(get)]
    pub free_cash_flow_operating_cash_flow_ratio: f64,
    #[pyo3(get)]
    pub debt_service_coverage_ratio: f64,
    #[pyo3(get)]
    pub interest_coverage_ratio: f64,
    #[pyo3(get)]
    pub short_term_operating_cash_flow_coverage_ratio: f64,
    #[pyo3(get)]
    pub operating_cash_flow_coverage_ratio: f64,
    #[pyo3(get)]
    pub capital_expenditure_coverage_ratio: f64,
    #[pyo3(get)]
    pub dividend_paid_and_capex_coverage_ratio: f64,
    #[pyo3(get)]
    pub dividend_payout_ratio: f64,
    #[pyo3(get)]
    pub dividend_yield: f64,
    #[pyo3(get)]
    pub dividend_yield_percentage: f64,
    #[pyo3(get)]
    pub revenue_per_share: f64,
    #[pyo3(get)]
    pub net_income_per_share: f64,
    #[pyo3(get)]
    pub interest_debt_per_share: f64,
    #[pyo3(get)]
    pub cash_per_share: f64,
    #[pyo3(get)]
    pub book_value_per_share: f64,
    #[pyo3(get)]
    pub tangible_book_value_per_share: f64,
    #[pyo3(get)]
    pub shareholders_equity_per_share: f64,
    #[pyo3(get)]
    pub operating_cash_flow_per_share: f64,
    #[pyo3(get)]
    pub capex_per_share: f64,
    #[pyo3(get)]
    pub free_cash_flow_per_share: f64,
    #[pyo3(get)]
    pub net_income_per_ebt: f64,
    #[pyo3(get)]
    pub ebt_per_ebit: f64,
    #[pyo3(get)]
    pub price_to_fair_value: f64,
    #[pyo3(get)]
    pub debt_to_market_cap: f64,
    #[pyo3(get)]
    pub effective_tax_rate: f64,
    #[pyo3(get)]
    pub enterprise_value_multiple: f64,
    #[pyo3(get)]
    pub dividend_per_share: f64,
}

#[gen_stub_pymethods]
#[pymethods]
impl FinancialRatios {
    #[new]
    #[allow(clippy::too_many_arguments)]
    #[allow(clippy::fn_params_excessive_bools)]
    #[pyo3(signature = (symbol, date, fiscal_year, period, reported_currency, gross_profit_margin, ebit_margin, ebitda_margin, operating_profit_margin, pretax_profit_margin, continuous_operations_profit_margin, net_profit_margin, bottom_line_profit_margin, receivables_turnover, payables_turnover, inventory_turnover, fixed_asset_turnover, asset_turnover, current_ratio, quick_ratio, solvency_ratio, cash_ratio, price_to_earnings_ratio, price_to_earnings_growth_ratio, forward_price_to_earnings_growth_ratio, price_to_earnings_diluted_ratio, price_to_earnings_diluted_growth_ratio, price_to_book_ratio, price_to_sales_ratio, price_to_free_cash_flow_ratio, price_to_operating_cash_flow_ratio, debt_to_assets_ratio, debt_to_equity_ratio, debt_to_capital_ratio, long_term_debt_to_capital_ratio, financial_leverage_ratio, working_capital_turnover_ratio, operating_cash_flow_ratio, operating_cash_flow_sales_ratio, free_cash_flow_operating_cash_flow_ratio, debt_service_coverage_ratio, interest_coverage_ratio, short_term_operating_cash_flow_coverage_ratio, operating_cash_flow_coverage_ratio, capital_expenditure_coverage_ratio, dividend_paid_and_capex_coverage_ratio, dividend_payout_ratio, dividend_yield, dividend_yield_percentage, revenue_per_share, net_income_per_share, interest_debt_per_share, cash_per_share, book_value_per_share, tangible_book_value_per_share, shareholders_equity_per_share, operating_cash_flow_per_share, capex_per_share, free_cash_flow_per_share, net_income_per_ebt, ebt_per_ebit, price_to_fair_value, debt_to_market_cap, effective_tax_rate, enterprise_value_multiple, dividend_per_share))]
    fn new(
        symbol: String,
        date: ::chrono::NaiveDate,
        fiscal_year: String,
        period: String,
        reported_currency: String,
        gross_profit_margin: f64,
        ebit_margin: f64,
        ebitda_margin: f64,
        operating_profit_margin: f64,
        pretax_profit_margin: f64,
        continuous_operations_profit_margin: f64,
        net_profit_margin: f64,
        bottom_line_profit_margin: f64,
        receivables_turnover: f64,
        payables_turnover: f64,
        inventory_turnover: f64,
        fixed_asset_turnover: f64,
        asset_turnover: f64,
        current_ratio: f64,
        quick_ratio: f64,
        solvency_ratio: f64,
        cash_ratio: f64,
        price_to_earnings_ratio: f64,
        price_to_earnings_growth_ratio: f64,
        forward_price_to_earnings_growth_ratio: f64,
        price_to_earnings_diluted_ratio: f64,
        price_to_earnings_diluted_growth_ratio: f64,
        price_to_book_ratio: f64,
        price_to_sales_ratio: f64,
        price_to_free_cash_flow_ratio: f64,
        price_to_operating_cash_flow_ratio: f64,
        debt_to_assets_ratio: f64,
        debt_to_equity_ratio: f64,
        debt_to_capital_ratio: f64,
        long_term_debt_to_capital_ratio: f64,
        financial_leverage_ratio: f64,
        working_capital_turnover_ratio: f64,
        operating_cash_flow_ratio: f64,
        operating_cash_flow_sales_ratio: f64,
        free_cash_flow_operating_cash_flow_ratio: f64,
        debt_service_coverage_ratio: f64,
        interest_coverage_ratio: f64,
        short_term_operating_cash_flow_coverage_ratio: f64,
        operating_cash_flow_coverage_ratio: f64,
        capital_expenditure_coverage_ratio: f64,
        dividend_paid_and_capex_coverage_ratio: f64,
        dividend_payout_ratio: f64,
        dividend_yield: f64,
        dividend_yield_percentage: f64,
        revenue_per_share: f64,
        net_income_per_share: f64,
        interest_debt_per_share: f64,
        cash_per_share: f64,
        book_value_per_share: f64,
        tangible_book_value_per_share: f64,
        shareholders_equity_per_share: f64,
        operating_cash_flow_per_share: f64,
        capex_per_share: f64,
        free_cash_flow_per_share: f64,
        net_income_per_ebt: f64,
        ebt_per_ebit: f64,
        price_to_fair_value: f64,
        debt_to_market_cap: f64,
        effective_tax_rate: f64,
        enterprise_value_multiple: f64,
        dividend_per_share: f64,
    ) -> Self {
        Self {
            symbol,
            date,
            fiscal_year,
            period,
            reported_currency,
            gross_profit_margin,
            ebit_margin,
            ebitda_margin,
            operating_profit_margin,
            pretax_profit_margin,
            continuous_operations_profit_margin,
            net_profit_margin,
            bottom_line_profit_margin,
            receivables_turnover,
            payables_turnover,
            inventory_turnover,
            fixed_asset_turnover,
            asset_turnover,
            current_ratio,
            quick_ratio,
            solvency_ratio,
            cash_ratio,
            price_to_earnings_ratio,
            price_to_earnings_growth_ratio,
            forward_price_to_earnings_growth_ratio,
            price_to_earnings_diluted_ratio,
            price_to_earnings_diluted_growth_ratio,
            price_to_book_ratio,
            price_to_sales_ratio,
            price_to_free_cash_flow_ratio,
            price_to_operating_cash_flow_ratio,
            debt_to_assets_ratio,
            debt_to_equity_ratio,
            debt_to_capital_ratio,
            long_term_debt_to_capital_ratio,
            financial_leverage_ratio,
            working_capital_turnover_ratio,
            operating_cash_flow_ratio,
            operating_cash_flow_sales_ratio,
            free_cash_flow_operating_cash_flow_ratio,
            debt_service_coverage_ratio,
            interest_coverage_ratio,
            short_term_operating_cash_flow_coverage_ratio,
            operating_cash_flow_coverage_ratio,
            capital_expenditure_coverage_ratio,
            dividend_paid_and_capex_coverage_ratio,
            dividend_payout_ratio,
            dividend_yield,
            dividend_yield_percentage,
            revenue_per_share,
            net_income_per_share,
            interest_debt_per_share,
            cash_per_share,
            book_value_per_share,
            tangible_book_value_per_share,
            shareholders_equity_per_share,
            operating_cash_flow_per_share,
            capex_per_share,
            free_cash_flow_per_share,
            net_income_per_ebt,
            ebt_per_ebit,
            price_to_fair_value,
            debt_to_market_cap,
            effective_tax_rate,
            enterprise_value_multiple,
            dividend_per_share,
        }
    }

    #[allow(clippy::clone_on_copy)]
    fn __getnewargs__<'py>(&self, py: Python<'py>) -> PyResult<Bound<'py, PyTuple>> {
        let members: Vec<Bound<'py, PyAny>> = vec![
            self.symbol.clone().into_bound_py_any(py)?,
            self.date.clone().into_bound_py_any(py)?,
            self.fiscal_year.clone().into_bound_py_any(py)?,
            self.period.clone().into_bound_py_any(py)?,
            self.reported_currency.clone().into_bound_py_any(py)?,
            self.gross_profit_margin.clone().into_bound_py_any(py)?,
            self.ebit_margin.clone().into_bound_py_any(py)?,
            self.ebitda_margin.clone().into_bound_py_any(py)?,
            self.operating_profit_margin.clone().into_bound_py_any(py)?,
            self.pretax_profit_margin.clone().into_bound_py_any(py)?,
            self.continuous_operations_profit_margin
                .clone()
                .into_bound_py_any(py)?,
            self.net_profit_margin.clone().into_bound_py_any(py)?,
            self.bottom_line_profit_margin
                .clone()
                .into_bound_py_any(py)?,
            self.receivables_turnover.clone().into_bound_py_any(py)?,
            self.payables_turnover.clone().into_bound_py_any(py)?,
            self.inventory_turnover.clone().into_bound_py_any(py)?,
            self.fixed_asset_turnover.clone().into_bound_py_any(py)?,
            self.asset_turnover.clone().into_bound_py_any(py)?,
            self.current_ratio.clone().into_bound_py_any(py)?,
            self.quick_ratio.clone().into_bound_py_any(py)?,
            self.solvency_ratio.clone().into_bound_py_any(py)?,
            self.cash_ratio.clone().into_bound_py_any(py)?,
            self.price_to_earnings_ratio.clone().into_bound_py_any(py)?,
            self.price_to_earnings_growth_ratio
                .clone()
                .into_bound_py_any(py)?,
            self.forward_price_to_earnings_growth_ratio
                .clone()
                .into_bound_py_any(py)?,
            self.price_to_earnings_diluted_ratio
                .clone()
                .into_bound_py_any(py)?,
            self.price_to_earnings_diluted_growth_ratio
                .clone()
                .into_bound_py_any(py)?,
            self.price_to_book_ratio.clone().into_bound_py_any(py)?,
            self.price_to_sales_ratio.clone().into_bound_py_any(py)?,
            self.price_to_free_cash_flow_ratio
                .clone()
                .into_bound_py_any(py)?,
            self.price_to_operating_cash_flow_ratio
                .clone()
                .into_bound_py_any(py)?,
            self.debt_to_assets_ratio.clone().into_bound_py_any(py)?,
            self.debt_to_equity_ratio.clone().into_bound_py_any(py)?,
            self.debt_to_capital_ratio.clone().into_bound_py_any(py)?,
            self.long_term_debt_to_capital_ratio
                .clone()
                .into_bound_py_any(py)?,
            self.financial_leverage_ratio
                .clone()
                .into_bound_py_any(py)?,
            self.working_capital_turnover_ratio
                .clone()
                .into_bound_py_any(py)?,
            self.operating_cash_flow_ratio
                .clone()
                .into_bound_py_any(py)?,
            self.operating_cash_flow_sales_ratio
                .clone()
                .into_bound_py_any(py)?,
            self.free_cash_flow_operating_cash_flow_ratio
                .clone()
                .into_bound_py_any(py)?,
            self.debt_service_coverage_ratio
                .clone()
                .into_bound_py_any(py)?,
            self.interest_coverage_ratio.clone().into_bound_py_any(py)?,
            self.short_term_operating_cash_flow_coverage_ratio
                .clone()
                .into_bound_py_any(py)?,
            self.operating_cash_flow_coverage_ratio
                .clone()
                .into_bound_py_any(py)?,
            self.capital_expenditure_coverage_ratio
                .clone()
                .into_bound_py_any(py)?,
            self.dividend_paid_and_capex_coverage_ratio
                .clone()
                .into_bound_py_any(py)?,
            self.dividend_payout_ratio.clone().into_bound_py_any(py)?,
            self.dividend_yield.clone().into_bound_py_any(py)?,
            self.dividend_yield_percentage
                .clone()
                .into_bound_py_any(py)?,
            self.revenue_per_share.clone().into_bound_py_any(py)?,
            self.net_income_per_share.clone().into_bound_py_any(py)?,
            self.interest_debt_per_share.clone().into_bound_py_any(py)?,
            self.cash_per_share.clone().into_bound_py_any(py)?,
            self.book_value_per_share.clone().into_bound_py_any(py)?,
            self.tangible_book_value_per_share
                .clone()
                .into_bound_py_any(py)?,
            self.shareholders_equity_per_share
                .clone()
                .into_bound_py_any(py)?,
            self.operating_cash_flow_per_share
                .clone()
                .into_bound_py_any(py)?,
            self.capex_per_share.clone().into_bound_py_any(py)?,
            self.free_cash_flow_per_share
                .clone()
                .into_bound_py_any(py)?,
            self.net_income_per_ebt.clone().into_bound_py_any(py)?,
            self.ebt_per_ebit.clone().into_bound_py_any(py)?,
            self.price_to_fair_value.clone().into_bound_py_any(py)?,
            self.debt_to_market_cap.clone().into_bound_py_any(py)?,
            self.effective_tax_rate.clone().into_bound_py_any(py)?,
            self.enterprise_value_multiple
                .clone()
                .into_bound_py_any(py)?,
            self.dividend_per_share.clone().into_bound_py_any(py)?,
        ];
        PyTuple::new(py, members)
    }
}

impl From<libfmp::responses::statements::ratios::FinancialRatios> for FinancialRatios {
    fn from(value: libfmp::responses::statements::ratios::FinancialRatios) -> Self {
        Self {
            symbol: value.symbol.into_inner(),
            date: value.date.into_inner(),
            fiscal_year: value.fiscal_year.as_str().to_owned(),
            period: value.period.to_string(),
            reported_currency: value.reported_currency.into_inner(),
            gross_profit_margin: value.gross_profit_margin,
            ebit_margin: value.ebit_margin,
            ebitda_margin: value.ebitda_margin,
            operating_profit_margin: value.operating_profit_margin,
            pretax_profit_margin: value.pretax_profit_margin,
            continuous_operations_profit_margin: value.continuous_operations_profit_margin,
            net_profit_margin: value.net_profit_margin,
            bottom_line_profit_margin: value.bottom_line_profit_margin,
            receivables_turnover: value.receivables_turnover,
            payables_turnover: value.payables_turnover,
            inventory_turnover: value.inventory_turnover,
            fixed_asset_turnover: value.fixed_asset_turnover,
            asset_turnover: value.asset_turnover,
            current_ratio: value.current_ratio,
            quick_ratio: value.quick_ratio,
            solvency_ratio: value.solvency_ratio,
            cash_ratio: value.cash_ratio,
            price_to_earnings_ratio: value.price_to_earnings_ratio,
            price_to_earnings_growth_ratio: value.price_to_earnings_growth_ratio,
            forward_price_to_earnings_growth_ratio: value.forward_price_to_earnings_growth_ratio,
            price_to_earnings_diluted_ratio: value.price_to_earnings_diluted_ratio,
            price_to_earnings_diluted_growth_ratio: value.price_to_earnings_diluted_growth_ratio,
            price_to_book_ratio: value.price_to_book_ratio,
            price_to_sales_ratio: value.price_to_sales_ratio,
            price_to_free_cash_flow_ratio: value.price_to_free_cash_flow_ratio,
            price_to_operating_cash_flow_ratio: value.price_to_operating_cash_flow_ratio,
            debt_to_assets_ratio: value.debt_to_assets_ratio,
            debt_to_equity_ratio: value.debt_to_equity_ratio,
            debt_to_capital_ratio: value.debt_to_capital_ratio,
            long_term_debt_to_capital_ratio: value.long_term_debt_to_capital_ratio,
            financial_leverage_ratio: value.financial_leverage_ratio,
            working_capital_turnover_ratio: value.working_capital_turnover_ratio,
            operating_cash_flow_ratio: value.operating_cash_flow_ratio,
            operating_cash_flow_sales_ratio: value.operating_cash_flow_sales_ratio,
            free_cash_flow_operating_cash_flow_ratio: value
                .free_cash_flow_operating_cash_flow_ratio,
            debt_service_coverage_ratio: value.debt_service_coverage_ratio,
            interest_coverage_ratio: value.interest_coverage_ratio,
            short_term_operating_cash_flow_coverage_ratio: value
                .short_term_operating_cash_flow_coverage_ratio,
            operating_cash_flow_coverage_ratio: value.operating_cash_flow_coverage_ratio,
            capital_expenditure_coverage_ratio: value.capital_expenditure_coverage_ratio,
            dividend_paid_and_capex_coverage_ratio: value.dividend_paid_and_capex_coverage_ratio,
            dividend_payout_ratio: value.dividend_payout_ratio,
            dividend_yield: value.dividend_yield,
            dividend_yield_percentage: value.dividend_yield_percentage,
            revenue_per_share: value.revenue_per_share,
            net_income_per_share: value.net_income_per_share,
            interest_debt_per_share: value.interest_debt_per_share,
            cash_per_share: value.cash_per_share,
            book_value_per_share: value.book_value_per_share,
            tangible_book_value_per_share: value.tangible_book_value_per_share,
            shareholders_equity_per_share: value.shareholders_equity_per_share,
            operating_cash_flow_per_share: value.operating_cash_flow_per_share,
            capex_per_share: value.capex_per_share,
            free_cash_flow_per_share: value.free_cash_flow_per_share,
            net_income_per_ebt: value.net_income_per_ebt,
            ebt_per_ebit: value.ebt_per_ebit,
            price_to_fair_value: value.price_to_fair_value,
            debt_to_market_cap: value.debt_to_market_cap,
            effective_tax_rate: value.effective_tax_rate,
            enterprise_value_multiple: value.enterprise_value_multiple,
            dividend_per_share: value.dividend_per_share,
        }
    }
}

#[gen_stub_pyclass]
#[pyclass(module = "fmp._native.statements.ratios", frozen, from_py_object)]
#[derive(Clone)]
pub(crate) struct FinancialRatiosTtm {
    #[pyo3(get)]
    pub symbol: String,
    #[pyo3(get)]
    pub gross_profit_margin_ttm: f64,
    #[pyo3(get)]
    pub ebit_margin_ttm: f64,
    #[pyo3(get)]
    pub ebitda_margin_ttm: f64,
    #[pyo3(get)]
    pub operating_profit_margin_ttm: f64,
    #[pyo3(get)]
    pub pretax_profit_margin_ttm: f64,
    #[pyo3(get)]
    pub continuous_operations_profit_margin_ttm: f64,
    #[pyo3(get)]
    pub net_profit_margin_ttm: f64,
    #[pyo3(get)]
    pub bottom_line_profit_margin_ttm: f64,
    #[pyo3(get)]
    pub receivables_turnover_ttm: f64,
    #[pyo3(get)]
    pub payables_turnover_ttm: f64,
    #[pyo3(get)]
    pub inventory_turnover_ttm: f64,
    #[pyo3(get)]
    pub fixed_asset_turnover_ttm: f64,
    #[pyo3(get)]
    pub asset_turnover_ttm: f64,
    #[pyo3(get)]
    pub current_ratio_ttm: f64,
    #[pyo3(get)]
    pub quick_ratio_ttm: f64,
    #[pyo3(get)]
    pub solvency_ratio_ttm: f64,
    #[pyo3(get)]
    pub cash_ratio_ttm: f64,
    #[pyo3(get)]
    pub price_to_earnings_ratio_ttm: f64,
    #[pyo3(get)]
    pub price_to_earnings_growth_ratio_ttm: f64,
    #[pyo3(get)]
    pub forward_price_to_earnings_growth_ratio_ttm: f64,
    #[pyo3(get)]
    pub price_to_earnings_diluted_ratio_ttm: f64,
    #[pyo3(get)]
    pub price_to_earnings_diluted_growth_ratio_ttm: f64,
    #[pyo3(get)]
    pub price_to_book_ratio_ttm: f64,
    #[pyo3(get)]
    pub price_to_sales_ratio_ttm: f64,
    #[pyo3(get)]
    pub price_to_free_cash_flow_ratio_ttm: f64,
    #[pyo3(get)]
    pub price_to_operating_cash_flow_ratio_ttm: f64,
    #[pyo3(get)]
    pub debt_to_assets_ratio_ttm: f64,
    #[pyo3(get)]
    pub debt_to_equity_ratio_ttm: f64,
    #[pyo3(get)]
    pub debt_to_capital_ratio_ttm: f64,
    #[pyo3(get)]
    pub long_term_debt_to_capital_ratio_ttm: f64,
    #[pyo3(get)]
    pub financial_leverage_ratio_ttm: f64,
    #[pyo3(get)]
    pub working_capital_turnover_ratio_ttm: f64,
    #[pyo3(get)]
    pub operating_cash_flow_ratio_ttm: f64,
    #[pyo3(get)]
    pub operating_cash_flow_sales_ratio_ttm: f64,
    #[pyo3(get)]
    pub free_cash_flow_operating_cash_flow_ratio_ttm: f64,
    #[pyo3(get)]
    pub debt_service_coverage_ratio_ttm: f64,
    #[pyo3(get)]
    pub interest_coverage_ratio_ttm: f64,
    #[pyo3(get)]
    pub short_term_operating_cash_flow_coverage_ratio_ttm: f64,
    #[pyo3(get)]
    pub operating_cash_flow_coverage_ratio_ttm: f64,
    #[pyo3(get)]
    pub capital_expenditure_coverage_ratio_ttm: f64,
    #[pyo3(get)]
    pub dividend_paid_and_capex_coverage_ratio_ttm: f64,
    #[pyo3(get)]
    pub dividend_payout_ratio_ttm: f64,
    #[pyo3(get)]
    pub dividend_yield_ttm: f64,
    #[pyo3(get)]
    pub enterprise_value_ttm: f64,
    #[pyo3(get)]
    pub revenue_per_share_ttm: f64,
    #[pyo3(get)]
    pub net_income_per_share_ttm: f64,
    #[pyo3(get)]
    pub interest_debt_per_share_ttm: f64,
    #[pyo3(get)]
    pub cash_per_share_ttm: f64,
    #[pyo3(get)]
    pub book_value_per_share_ttm: f64,
    #[pyo3(get)]
    pub tangible_book_value_per_share_ttm: f64,
    #[pyo3(get)]
    pub shareholders_equity_per_share_ttm: f64,
    #[pyo3(get)]
    pub operating_cash_flow_per_share_ttm: f64,
    #[pyo3(get)]
    pub capex_per_share_ttm: f64,
    #[pyo3(get)]
    pub free_cash_flow_per_share_ttm: f64,
    #[pyo3(get)]
    pub net_income_per_ebt_ttm: f64,
    #[pyo3(get)]
    pub ebt_per_ebit_ttm: f64,
    #[pyo3(get)]
    pub price_to_fair_value_ttm: f64,
    #[pyo3(get)]
    pub debt_to_market_cap_ttm: f64,
    #[pyo3(get)]
    pub effective_tax_rate_ttm: f64,
    #[pyo3(get)]
    pub enterprise_value_multiple_ttm: f64,
    #[pyo3(get)]
    pub dividend_per_share_ttm: f64,
}

#[gen_stub_pymethods]
#[pymethods]
impl FinancialRatiosTtm {
    #[new]
    #[allow(clippy::too_many_arguments)]
    #[allow(clippy::fn_params_excessive_bools)]
    #[pyo3(signature = (symbol, gross_profit_margin_ttm, ebit_margin_ttm, ebitda_margin_ttm, operating_profit_margin_ttm, pretax_profit_margin_ttm, continuous_operations_profit_margin_ttm, net_profit_margin_ttm, bottom_line_profit_margin_ttm, receivables_turnover_ttm, payables_turnover_ttm, inventory_turnover_ttm, fixed_asset_turnover_ttm, asset_turnover_ttm, current_ratio_ttm, quick_ratio_ttm, solvency_ratio_ttm, cash_ratio_ttm, price_to_earnings_ratio_ttm, price_to_earnings_growth_ratio_ttm, forward_price_to_earnings_growth_ratio_ttm, price_to_earnings_diluted_ratio_ttm, price_to_earnings_diluted_growth_ratio_ttm, price_to_book_ratio_ttm, price_to_sales_ratio_ttm, price_to_free_cash_flow_ratio_ttm, price_to_operating_cash_flow_ratio_ttm, debt_to_assets_ratio_ttm, debt_to_equity_ratio_ttm, debt_to_capital_ratio_ttm, long_term_debt_to_capital_ratio_ttm, financial_leverage_ratio_ttm, working_capital_turnover_ratio_ttm, operating_cash_flow_ratio_ttm, operating_cash_flow_sales_ratio_ttm, free_cash_flow_operating_cash_flow_ratio_ttm, debt_service_coverage_ratio_ttm, interest_coverage_ratio_ttm, short_term_operating_cash_flow_coverage_ratio_ttm, operating_cash_flow_coverage_ratio_ttm, capital_expenditure_coverage_ratio_ttm, dividend_paid_and_capex_coverage_ratio_ttm, dividend_payout_ratio_ttm, dividend_yield_ttm, enterprise_value_ttm, revenue_per_share_ttm, net_income_per_share_ttm, interest_debt_per_share_ttm, cash_per_share_ttm, book_value_per_share_ttm, tangible_book_value_per_share_ttm, shareholders_equity_per_share_ttm, operating_cash_flow_per_share_ttm, capex_per_share_ttm, free_cash_flow_per_share_ttm, net_income_per_ebt_ttm, ebt_per_ebit_ttm, price_to_fair_value_ttm, debt_to_market_cap_ttm, effective_tax_rate_ttm, enterprise_value_multiple_ttm, dividend_per_share_ttm))]
    fn new(
        symbol: String,
        gross_profit_margin_ttm: f64,
        ebit_margin_ttm: f64,
        ebitda_margin_ttm: f64,
        operating_profit_margin_ttm: f64,
        pretax_profit_margin_ttm: f64,
        continuous_operations_profit_margin_ttm: f64,
        net_profit_margin_ttm: f64,
        bottom_line_profit_margin_ttm: f64,
        receivables_turnover_ttm: f64,
        payables_turnover_ttm: f64,
        inventory_turnover_ttm: f64,
        fixed_asset_turnover_ttm: f64,
        asset_turnover_ttm: f64,
        current_ratio_ttm: f64,
        quick_ratio_ttm: f64,
        solvency_ratio_ttm: f64,
        cash_ratio_ttm: f64,
        price_to_earnings_ratio_ttm: f64,
        price_to_earnings_growth_ratio_ttm: f64,
        forward_price_to_earnings_growth_ratio_ttm: f64,
        price_to_earnings_diluted_ratio_ttm: f64,
        price_to_earnings_diluted_growth_ratio_ttm: f64,
        price_to_book_ratio_ttm: f64,
        price_to_sales_ratio_ttm: f64,
        price_to_free_cash_flow_ratio_ttm: f64,
        price_to_operating_cash_flow_ratio_ttm: f64,
        debt_to_assets_ratio_ttm: f64,
        debt_to_equity_ratio_ttm: f64,
        debt_to_capital_ratio_ttm: f64,
        long_term_debt_to_capital_ratio_ttm: f64,
        financial_leverage_ratio_ttm: f64,
        working_capital_turnover_ratio_ttm: f64,
        operating_cash_flow_ratio_ttm: f64,
        operating_cash_flow_sales_ratio_ttm: f64,
        free_cash_flow_operating_cash_flow_ratio_ttm: f64,
        debt_service_coverage_ratio_ttm: f64,
        interest_coverage_ratio_ttm: f64,
        short_term_operating_cash_flow_coverage_ratio_ttm: f64,
        operating_cash_flow_coverage_ratio_ttm: f64,
        capital_expenditure_coverage_ratio_ttm: f64,
        dividend_paid_and_capex_coverage_ratio_ttm: f64,
        dividend_payout_ratio_ttm: f64,
        dividend_yield_ttm: f64,
        enterprise_value_ttm: f64,
        revenue_per_share_ttm: f64,
        net_income_per_share_ttm: f64,
        interest_debt_per_share_ttm: f64,
        cash_per_share_ttm: f64,
        book_value_per_share_ttm: f64,
        tangible_book_value_per_share_ttm: f64,
        shareholders_equity_per_share_ttm: f64,
        operating_cash_flow_per_share_ttm: f64,
        capex_per_share_ttm: f64,
        free_cash_flow_per_share_ttm: f64,
        net_income_per_ebt_ttm: f64,
        ebt_per_ebit_ttm: f64,
        price_to_fair_value_ttm: f64,
        debt_to_market_cap_ttm: f64,
        effective_tax_rate_ttm: f64,
        enterprise_value_multiple_ttm: f64,
        dividend_per_share_ttm: f64,
    ) -> Self {
        Self {
            symbol,
            gross_profit_margin_ttm,
            ebit_margin_ttm,
            ebitda_margin_ttm,
            operating_profit_margin_ttm,
            pretax_profit_margin_ttm,
            continuous_operations_profit_margin_ttm,
            net_profit_margin_ttm,
            bottom_line_profit_margin_ttm,
            receivables_turnover_ttm,
            payables_turnover_ttm,
            inventory_turnover_ttm,
            fixed_asset_turnover_ttm,
            asset_turnover_ttm,
            current_ratio_ttm,
            quick_ratio_ttm,
            solvency_ratio_ttm,
            cash_ratio_ttm,
            price_to_earnings_ratio_ttm,
            price_to_earnings_growth_ratio_ttm,
            forward_price_to_earnings_growth_ratio_ttm,
            price_to_earnings_diluted_ratio_ttm,
            price_to_earnings_diluted_growth_ratio_ttm,
            price_to_book_ratio_ttm,
            price_to_sales_ratio_ttm,
            price_to_free_cash_flow_ratio_ttm,
            price_to_operating_cash_flow_ratio_ttm,
            debt_to_assets_ratio_ttm,
            debt_to_equity_ratio_ttm,
            debt_to_capital_ratio_ttm,
            long_term_debt_to_capital_ratio_ttm,
            financial_leverage_ratio_ttm,
            working_capital_turnover_ratio_ttm,
            operating_cash_flow_ratio_ttm,
            operating_cash_flow_sales_ratio_ttm,
            free_cash_flow_operating_cash_flow_ratio_ttm,
            debt_service_coverage_ratio_ttm,
            interest_coverage_ratio_ttm,
            short_term_operating_cash_flow_coverage_ratio_ttm,
            operating_cash_flow_coverage_ratio_ttm,
            capital_expenditure_coverage_ratio_ttm,
            dividend_paid_and_capex_coverage_ratio_ttm,
            dividend_payout_ratio_ttm,
            dividend_yield_ttm,
            enterprise_value_ttm,
            revenue_per_share_ttm,
            net_income_per_share_ttm,
            interest_debt_per_share_ttm,
            cash_per_share_ttm,
            book_value_per_share_ttm,
            tangible_book_value_per_share_ttm,
            shareholders_equity_per_share_ttm,
            operating_cash_flow_per_share_ttm,
            capex_per_share_ttm,
            free_cash_flow_per_share_ttm,
            net_income_per_ebt_ttm,
            ebt_per_ebit_ttm,
            price_to_fair_value_ttm,
            debt_to_market_cap_ttm,
            effective_tax_rate_ttm,
            enterprise_value_multiple_ttm,
            dividend_per_share_ttm,
        }
    }

    #[allow(clippy::clone_on_copy)]
    fn __getnewargs__<'py>(&self, py: Python<'py>) -> PyResult<Bound<'py, PyTuple>> {
        let members: Vec<Bound<'py, PyAny>> = vec![
            self.symbol.clone().into_bound_py_any(py)?,
            self.gross_profit_margin_ttm.clone().into_bound_py_any(py)?,
            self.ebit_margin_ttm.clone().into_bound_py_any(py)?,
            self.ebitda_margin_ttm.clone().into_bound_py_any(py)?,
            self.operating_profit_margin_ttm
                .clone()
                .into_bound_py_any(py)?,
            self.pretax_profit_margin_ttm
                .clone()
                .into_bound_py_any(py)?,
            self.continuous_operations_profit_margin_ttm
                .clone()
                .into_bound_py_any(py)?,
            self.net_profit_margin_ttm.clone().into_bound_py_any(py)?,
            self.bottom_line_profit_margin_ttm
                .clone()
                .into_bound_py_any(py)?,
            self.receivables_turnover_ttm
                .clone()
                .into_bound_py_any(py)?,
            self.payables_turnover_ttm.clone().into_bound_py_any(py)?,
            self.inventory_turnover_ttm.clone().into_bound_py_any(py)?,
            self.fixed_asset_turnover_ttm
                .clone()
                .into_bound_py_any(py)?,
            self.asset_turnover_ttm.clone().into_bound_py_any(py)?,
            self.current_ratio_ttm.clone().into_bound_py_any(py)?,
            self.quick_ratio_ttm.clone().into_bound_py_any(py)?,
            self.solvency_ratio_ttm.clone().into_bound_py_any(py)?,
            self.cash_ratio_ttm.clone().into_bound_py_any(py)?,
            self.price_to_earnings_ratio_ttm
                .clone()
                .into_bound_py_any(py)?,
            self.price_to_earnings_growth_ratio_ttm
                .clone()
                .into_bound_py_any(py)?,
            self.forward_price_to_earnings_growth_ratio_ttm
                .clone()
                .into_bound_py_any(py)?,
            self.price_to_earnings_diluted_ratio_ttm
                .clone()
                .into_bound_py_any(py)?,
            self.price_to_earnings_diluted_growth_ratio_ttm
                .clone()
                .into_bound_py_any(py)?,
            self.price_to_book_ratio_ttm.clone().into_bound_py_any(py)?,
            self.price_to_sales_ratio_ttm
                .clone()
                .into_bound_py_any(py)?,
            self.price_to_free_cash_flow_ratio_ttm
                .clone()
                .into_bound_py_any(py)?,
            self.price_to_operating_cash_flow_ratio_ttm
                .clone()
                .into_bound_py_any(py)?,
            self.debt_to_assets_ratio_ttm
                .clone()
                .into_bound_py_any(py)?,
            self.debt_to_equity_ratio_ttm
                .clone()
                .into_bound_py_any(py)?,
            self.debt_to_capital_ratio_ttm
                .clone()
                .into_bound_py_any(py)?,
            self.long_term_debt_to_capital_ratio_ttm
                .clone()
                .into_bound_py_any(py)?,
            self.financial_leverage_ratio_ttm
                .clone()
                .into_bound_py_any(py)?,
            self.working_capital_turnover_ratio_ttm
                .clone()
                .into_bound_py_any(py)?,
            self.operating_cash_flow_ratio_ttm
                .clone()
                .into_bound_py_any(py)?,
            self.operating_cash_flow_sales_ratio_ttm
                .clone()
                .into_bound_py_any(py)?,
            self.free_cash_flow_operating_cash_flow_ratio_ttm
                .clone()
                .into_bound_py_any(py)?,
            self.debt_service_coverage_ratio_ttm
                .clone()
                .into_bound_py_any(py)?,
            self.interest_coverage_ratio_ttm
                .clone()
                .into_bound_py_any(py)?,
            self.short_term_operating_cash_flow_coverage_ratio_ttm
                .clone()
                .into_bound_py_any(py)?,
            self.operating_cash_flow_coverage_ratio_ttm
                .clone()
                .into_bound_py_any(py)?,
            self.capital_expenditure_coverage_ratio_ttm
                .clone()
                .into_bound_py_any(py)?,
            self.dividend_paid_and_capex_coverage_ratio_ttm
                .clone()
                .into_bound_py_any(py)?,
            self.dividend_payout_ratio_ttm
                .clone()
                .into_bound_py_any(py)?,
            self.dividend_yield_ttm.clone().into_bound_py_any(py)?,
            self.enterprise_value_ttm.clone().into_bound_py_any(py)?,
            self.revenue_per_share_ttm.clone().into_bound_py_any(py)?,
            self.net_income_per_share_ttm
                .clone()
                .into_bound_py_any(py)?,
            self.interest_debt_per_share_ttm
                .clone()
                .into_bound_py_any(py)?,
            self.cash_per_share_ttm.clone().into_bound_py_any(py)?,
            self.book_value_per_share_ttm
                .clone()
                .into_bound_py_any(py)?,
            self.tangible_book_value_per_share_ttm
                .clone()
                .into_bound_py_any(py)?,
            self.shareholders_equity_per_share_ttm
                .clone()
                .into_bound_py_any(py)?,
            self.operating_cash_flow_per_share_ttm
                .clone()
                .into_bound_py_any(py)?,
            self.capex_per_share_ttm.clone().into_bound_py_any(py)?,
            self.free_cash_flow_per_share_ttm
                .clone()
                .into_bound_py_any(py)?,
            self.net_income_per_ebt_ttm.clone().into_bound_py_any(py)?,
            self.ebt_per_ebit_ttm.clone().into_bound_py_any(py)?,
            self.price_to_fair_value_ttm.clone().into_bound_py_any(py)?,
            self.debt_to_market_cap_ttm.clone().into_bound_py_any(py)?,
            self.effective_tax_rate_ttm.clone().into_bound_py_any(py)?,
            self.enterprise_value_multiple_ttm
                .clone()
                .into_bound_py_any(py)?,
            self.dividend_per_share_ttm.clone().into_bound_py_any(py)?,
        ];
        PyTuple::new(py, members)
    }
}

impl From<libfmp::responses::statements::ratios::FinancialRatiosTtm> for FinancialRatiosTtm {
    fn from(value: libfmp::responses::statements::ratios::FinancialRatiosTtm) -> Self {
        Self {
            symbol: value.symbol.into_inner(),
            gross_profit_margin_ttm: value.gross_profit_margin_ttm,
            ebit_margin_ttm: value.ebit_margin_ttm,
            ebitda_margin_ttm: value.ebitda_margin_ttm,
            operating_profit_margin_ttm: value.operating_profit_margin_ttm,
            pretax_profit_margin_ttm: value.pretax_profit_margin_ttm,
            continuous_operations_profit_margin_ttm: value.continuous_operations_profit_margin_ttm,
            net_profit_margin_ttm: value.net_profit_margin_ttm,
            bottom_line_profit_margin_ttm: value.bottom_line_profit_margin_ttm,
            receivables_turnover_ttm: value.receivables_turnover_ttm,
            payables_turnover_ttm: value.payables_turnover_ttm,
            inventory_turnover_ttm: value.inventory_turnover_ttm,
            fixed_asset_turnover_ttm: value.fixed_asset_turnover_ttm,
            asset_turnover_ttm: value.asset_turnover_ttm,
            current_ratio_ttm: value.current_ratio_ttm,
            quick_ratio_ttm: value.quick_ratio_ttm,
            solvency_ratio_ttm: value.solvency_ratio_ttm,
            cash_ratio_ttm: value.cash_ratio_ttm,
            price_to_earnings_ratio_ttm: value.price_to_earnings_ratio_ttm,
            price_to_earnings_growth_ratio_ttm: value.price_to_earnings_growth_ratio_ttm,
            forward_price_to_earnings_growth_ratio_ttm: value
                .forward_price_to_earnings_growth_ratio_ttm,
            price_to_earnings_diluted_ratio_ttm: value.price_to_earnings_diluted_ratio_ttm,
            price_to_earnings_diluted_growth_ratio_ttm: value
                .price_to_earnings_diluted_growth_ratio_ttm,
            price_to_book_ratio_ttm: value.price_to_book_ratio_ttm,
            price_to_sales_ratio_ttm: value.price_to_sales_ratio_ttm,
            price_to_free_cash_flow_ratio_ttm: value.price_to_free_cash_flow_ratio_ttm,
            price_to_operating_cash_flow_ratio_ttm: value.price_to_operating_cash_flow_ratio_ttm,
            debt_to_assets_ratio_ttm: value.debt_to_assets_ratio_ttm,
            debt_to_equity_ratio_ttm: value.debt_to_equity_ratio_ttm,
            debt_to_capital_ratio_ttm: value.debt_to_capital_ratio_ttm,
            long_term_debt_to_capital_ratio_ttm: value.long_term_debt_to_capital_ratio_ttm,
            financial_leverage_ratio_ttm: value.financial_leverage_ratio_ttm,
            working_capital_turnover_ratio_ttm: value.working_capital_turnover_ratio_ttm,
            operating_cash_flow_ratio_ttm: value.operating_cash_flow_ratio_ttm,
            operating_cash_flow_sales_ratio_ttm: value.operating_cash_flow_sales_ratio_ttm,
            free_cash_flow_operating_cash_flow_ratio_ttm: value
                .free_cash_flow_operating_cash_flow_ratio_ttm,
            debt_service_coverage_ratio_ttm: value.debt_service_coverage_ratio_ttm,
            interest_coverage_ratio_ttm: value.interest_coverage_ratio_ttm,
            short_term_operating_cash_flow_coverage_ratio_ttm: value
                .short_term_operating_cash_flow_coverage_ratio_ttm,
            operating_cash_flow_coverage_ratio_ttm: value.operating_cash_flow_coverage_ratio_ttm,
            capital_expenditure_coverage_ratio_ttm: value.capital_expenditure_coverage_ratio_ttm,
            dividend_paid_and_capex_coverage_ratio_ttm: value
                .dividend_paid_and_capex_coverage_ratio_ttm,
            dividend_payout_ratio_ttm: value.dividend_payout_ratio_ttm,
            dividend_yield_ttm: value.dividend_yield_ttm,
            enterprise_value_ttm: value.enterprise_value_ttm,
            revenue_per_share_ttm: value.revenue_per_share_ttm,
            net_income_per_share_ttm: value.net_income_per_share_ttm,
            interest_debt_per_share_ttm: value.interest_debt_per_share_ttm,
            cash_per_share_ttm: value.cash_per_share_ttm,
            book_value_per_share_ttm: value.book_value_per_share_ttm,
            tangible_book_value_per_share_ttm: value.tangible_book_value_per_share_ttm,
            shareholders_equity_per_share_ttm: value.shareholders_equity_per_share_ttm,
            operating_cash_flow_per_share_ttm: value.operating_cash_flow_per_share_ttm,
            capex_per_share_ttm: value.capex_per_share_ttm,
            free_cash_flow_per_share_ttm: value.free_cash_flow_per_share_ttm,
            net_income_per_ebt_ttm: value.net_income_per_ebt_ttm,
            ebt_per_ebit_ttm: value.ebt_per_ebit_ttm,
            price_to_fair_value_ttm: value.price_to_fair_value_ttm,
            debt_to_market_cap_ttm: value.debt_to_market_cap_ttm,
            effective_tax_rate_ttm: value.effective_tax_rate_ttm,
            enterprise_value_multiple_ttm: value.enterprise_value_multiple_ttm,
            dividend_per_share_ttm: value.dividend_per_share_ttm,
        }
    }
}
