// @generated by gen_models; do not edit by hand.

use pyo3::IntoPyObjectExt;
use pyo3::prelude::*;
use pyo3::types::{PyDict, PyTuple};
use pyo3_stub_gen::derive::{gen_stub_pyclass, gen_stub_pymethods};

#[gen_stub_pyclass]
#[pyclass(
    module = "fmp._native.statements.summaries",
    frozen,
    eq,
    from_py_object
)]
#[derive(Clone, PartialEq)]
pub(crate) struct LatestFinancialStatement {
    #[pyo3(get)]
    pub symbol: String,
    #[pyo3(get)]
    pub calendar_year: u32,
    #[pyo3(get)]
    pub period: String,
    #[pyo3(get)]
    pub date: ::chrono::NaiveDate,
    #[pyo3(get)]
    pub date_added: ::chrono::NaiveDateTime,
}

#[gen_stub_pymethods]
#[pymethods]
impl LatestFinancialStatement {
    #[new]
    #[allow(clippy::too_many_arguments)]
    #[allow(clippy::fn_params_excessive_bools)]
    #[pyo3(signature = (*, symbol, calendar_year, period, date, date_added))]
    fn new(
        symbol: String,
        calendar_year: u32,
        period: String,
        date: ::chrono::NaiveDate,
        date_added: ::chrono::NaiveDateTime,
    ) -> Self {
        Self {
            symbol,
            calendar_year,
            period,
            date,
            date_added,
        }
    }

    #[classattr]
    const __hash__: Option<Py<PyAny>> = None;

    #[allow(clippy::clone_on_copy)]
    fn __getnewargs_ex__<'py>(
        &self,
        py: Python<'py>,
    ) -> PyResult<(Bound<'py, PyTuple>, Bound<'py, PyDict>)> {
        let kwargs = PyDict::new(py);
        kwargs.set_item("symbol", self.symbol.clone().into_bound_py_any(py)?)?;
        kwargs.set_item(
            "calendar_year",
            self.calendar_year.clone().into_bound_py_any(py)?,
        )?;
        kwargs.set_item("period", self.period.clone().into_bound_py_any(py)?)?;
        kwargs.set_item("date", self.date.clone().into_bound_py_any(py)?)?;
        kwargs.set_item("date_added", self.date_added.clone().into_bound_py_any(py)?)?;
        Ok((PyTuple::empty(py), kwargs))
    }
}

impl From<libfmp::responses::statements::summaries::LatestFinancialStatement>
    for LatestFinancialStatement
{
    fn from(value: libfmp::responses::statements::summaries::LatestFinancialStatement) -> Self {
        Self {
            symbol: value.symbol.into_inner(),
            calendar_year: value.calendar_year.get(),
            period: value.period.to_string(),
            date: value.date.into_inner(),
            date_added: value.date_added.into_inner(),
        }
    }
}

#[gen_stub_pyclass]
#[pyclass(
    module = "fmp._native.statements.summaries",
    frozen,
    eq,
    from_py_object
)]
#[derive(Clone, PartialEq)]
pub(crate) struct FinancialScore {
    #[pyo3(get)]
    pub symbol: String,
    #[pyo3(get)]
    pub reported_currency: String,
    #[pyo3(get)]
    pub altman_z_score: f64,
    #[pyo3(get)]
    pub piotroski_score: u64,
    #[pyo3(get)]
    pub working_capital: f64,
    #[pyo3(get)]
    pub total_assets: f64,
    #[pyo3(get)]
    pub retained_earnings: f64,
    #[pyo3(get)]
    pub ebit: f64,
    #[pyo3(get)]
    pub market_cap: f64,
    #[pyo3(get)]
    pub total_liabilities: f64,
    #[pyo3(get)]
    pub revenue: f64,
}

#[gen_stub_pymethods]
#[pymethods]
impl FinancialScore {
    #[new]
    #[allow(clippy::too_many_arguments)]
    #[allow(clippy::fn_params_excessive_bools)]
    #[pyo3(signature = (*, symbol, reported_currency, altman_z_score, piotroski_score, working_capital, total_assets, retained_earnings, ebit, market_cap, total_liabilities, revenue))]
    fn new(
        symbol: String,
        reported_currency: String,
        altman_z_score: f64,
        piotroski_score: u64,
        working_capital: f64,
        total_assets: f64,
        retained_earnings: f64,
        ebit: f64,
        market_cap: f64,
        total_liabilities: f64,
        revenue: f64,
    ) -> Self {
        Self {
            symbol,
            reported_currency,
            altman_z_score,
            piotroski_score,
            working_capital,
            total_assets,
            retained_earnings,
            ebit,
            market_cap,
            total_liabilities,
            revenue,
        }
    }

    #[classattr]
    const __hash__: Option<Py<PyAny>> = None;

    #[allow(clippy::clone_on_copy)]
    fn __getnewargs_ex__<'py>(
        &self,
        py: Python<'py>,
    ) -> PyResult<(Bound<'py, PyTuple>, Bound<'py, PyDict>)> {
        let kwargs = PyDict::new(py);
        kwargs.set_item("symbol", self.symbol.clone().into_bound_py_any(py)?)?;
        kwargs.set_item(
            "reported_currency",
            self.reported_currency.clone().into_bound_py_any(py)?,
        )?;
        kwargs.set_item(
            "altman_z_score",
            self.altman_z_score.clone().into_bound_py_any(py)?,
        )?;
        kwargs.set_item(
            "piotroski_score",
            self.piotroski_score.clone().into_bound_py_any(py)?,
        )?;
        kwargs.set_item(
            "working_capital",
            self.working_capital.clone().into_bound_py_any(py)?,
        )?;
        kwargs.set_item(
            "total_assets",
            self.total_assets.clone().into_bound_py_any(py)?,
        )?;
        kwargs.set_item(
            "retained_earnings",
            self.retained_earnings.clone().into_bound_py_any(py)?,
        )?;
        kwargs.set_item("ebit", self.ebit.clone().into_bound_py_any(py)?)?;
        kwargs.set_item("market_cap", self.market_cap.clone().into_bound_py_any(py)?)?;
        kwargs.set_item(
            "total_liabilities",
            self.total_liabilities.clone().into_bound_py_any(py)?,
        )?;
        kwargs.set_item("revenue", self.revenue.clone().into_bound_py_any(py)?)?;
        Ok((PyTuple::empty(py), kwargs))
    }
}

impl From<libfmp::responses::statements::summaries::FinancialScore> for FinancialScore {
    fn from(value: libfmp::responses::statements::summaries::FinancialScore) -> Self {
        Self {
            symbol: value.symbol.into_inner(),
            reported_currency: value.reported_currency.into_inner(),
            altman_z_score: value.altman_z_score,
            piotroski_score: value.piotroski_score,
            working_capital: value.working_capital,
            total_assets: value.total_assets,
            retained_earnings: value.retained_earnings,
            ebit: value.ebit,
            market_cap: value.market_cap,
            total_liabilities: value.total_liabilities,
            revenue: value.revenue,
        }
    }
}

#[gen_stub_pyclass]
#[pyclass(
    module = "fmp._native.statements.summaries",
    frozen,
    eq,
    from_py_object
)]
#[derive(Clone, PartialEq)]
pub(crate) struct OwnerEarnings {
    #[pyo3(get)]
    pub symbol: String,
    #[pyo3(get)]
    pub reported_currency: String,
    #[pyo3(get)]
    pub fiscal_year: String,
    #[pyo3(get)]
    pub period: String,
    #[pyo3(get)]
    pub date: ::chrono::NaiveDate,
    #[pyo3(get)]
    pub average_ppe: f64,
    #[pyo3(get)]
    pub maintenance_capex: f64,
    #[pyo3(get)]
    pub owners_earnings: f64,
    #[pyo3(get)]
    pub growth_capex: f64,
    #[pyo3(get)]
    pub owners_earnings_per_share: f64,
}

#[gen_stub_pymethods]
#[pymethods]
impl OwnerEarnings {
    #[new]
    #[allow(clippy::too_many_arguments)]
    #[allow(clippy::fn_params_excessive_bools)]
    #[pyo3(signature = (*, symbol, reported_currency, fiscal_year, period, date, average_ppe, maintenance_capex, owners_earnings, growth_capex, owners_earnings_per_share))]
    fn new(
        symbol: String,
        reported_currency: String,
        fiscal_year: String,
        period: String,
        date: ::chrono::NaiveDate,
        average_ppe: f64,
        maintenance_capex: f64,
        owners_earnings: f64,
        growth_capex: f64,
        owners_earnings_per_share: f64,
    ) -> Self {
        Self {
            symbol,
            reported_currency,
            fiscal_year,
            period,
            date,
            average_ppe,
            maintenance_capex,
            owners_earnings,
            growth_capex,
            owners_earnings_per_share,
        }
    }

    #[classattr]
    const __hash__: Option<Py<PyAny>> = None;

    #[allow(clippy::clone_on_copy)]
    fn __getnewargs_ex__<'py>(
        &self,
        py: Python<'py>,
    ) -> PyResult<(Bound<'py, PyTuple>, Bound<'py, PyDict>)> {
        let kwargs = PyDict::new(py);
        kwargs.set_item("symbol", self.symbol.clone().into_bound_py_any(py)?)?;
        kwargs.set_item(
            "reported_currency",
            self.reported_currency.clone().into_bound_py_any(py)?,
        )?;
        kwargs.set_item(
            "fiscal_year",
            self.fiscal_year.clone().into_bound_py_any(py)?,
        )?;
        kwargs.set_item("period", self.period.clone().into_bound_py_any(py)?)?;
        kwargs.set_item("date", self.date.clone().into_bound_py_any(py)?)?;
        kwargs.set_item(
            "average_ppe",
            self.average_ppe.clone().into_bound_py_any(py)?,
        )?;
        kwargs.set_item(
            "maintenance_capex",
            self.maintenance_capex.clone().into_bound_py_any(py)?,
        )?;
        kwargs.set_item(
            "owners_earnings",
            self.owners_earnings.clone().into_bound_py_any(py)?,
        )?;
        kwargs.set_item(
            "growth_capex",
            self.growth_capex.clone().into_bound_py_any(py)?,
        )?;
        kwargs.set_item(
            "owners_earnings_per_share",
            self.owners_earnings_per_share
                .clone()
                .into_bound_py_any(py)?,
        )?;
        Ok((PyTuple::empty(py), kwargs))
    }
}

impl From<libfmp::responses::statements::summaries::OwnerEarnings> for OwnerEarnings {
    fn from(value: libfmp::responses::statements::summaries::OwnerEarnings) -> Self {
        Self {
            symbol: value.symbol.into_inner(),
            reported_currency: value.reported_currency.into_inner(),
            fiscal_year: value.fiscal_year.as_str().to_owned(),
            period: value.period.to_string(),
            date: value.date.into_inner(),
            average_ppe: value.average_ppe,
            maintenance_capex: value.maintenance_capex,
            owners_earnings: value.owners_earnings,
            growth_capex: value.growth_capex,
            owners_earnings_per_share: value.owners_earnings_per_share,
        }
    }
}

#[gen_stub_pyclass]
#[pyclass(
    module = "fmp._native.statements.summaries",
    frozen,
    eq,
    from_py_object
)]
#[derive(Clone, PartialEq)]
pub(crate) struct EnterpriseValue {
    #[pyo3(get)]
    pub symbol: String,
    #[pyo3(get)]
    pub date: ::chrono::NaiveDate,
    #[pyo3(get)]
    pub stock_price: f64,
    #[pyo3(get)]
    pub number_of_shares: f64,
    #[pyo3(get)]
    pub market_capitalization: f64,
    #[pyo3(get)]
    pub minus_cash_and_cash_equivalents: f64,
    #[pyo3(get)]
    pub add_total_debt: f64,
    #[pyo3(get)]
    pub enterprise_value: f64,
}

#[gen_stub_pymethods]
#[pymethods]
impl EnterpriseValue {
    #[new]
    #[allow(clippy::too_many_arguments)]
    #[allow(clippy::fn_params_excessive_bools)]
    #[pyo3(signature = (*, symbol, date, stock_price, number_of_shares, market_capitalization, minus_cash_and_cash_equivalents, add_total_debt, enterprise_value))]
    fn new(
        symbol: String,
        date: ::chrono::NaiveDate,
        stock_price: f64,
        number_of_shares: f64,
        market_capitalization: f64,
        minus_cash_and_cash_equivalents: f64,
        add_total_debt: f64,
        enterprise_value: f64,
    ) -> Self {
        Self {
            symbol,
            date,
            stock_price,
            number_of_shares,
            market_capitalization,
            minus_cash_and_cash_equivalents,
            add_total_debt,
            enterprise_value,
        }
    }

    #[classattr]
    const __hash__: Option<Py<PyAny>> = None;

    #[allow(clippy::clone_on_copy)]
    fn __getnewargs_ex__<'py>(
        &self,
        py: Python<'py>,
    ) -> PyResult<(Bound<'py, PyTuple>, Bound<'py, PyDict>)> {
        let kwargs = PyDict::new(py);
        kwargs.set_item("symbol", self.symbol.clone().into_bound_py_any(py)?)?;
        kwargs.set_item("date", self.date.clone().into_bound_py_any(py)?)?;
        kwargs.set_item(
            "stock_price",
            self.stock_price.clone().into_bound_py_any(py)?,
        )?;
        kwargs.set_item(
            "number_of_shares",
            self.number_of_shares.clone().into_bound_py_any(py)?,
        )?;
        kwargs.set_item(
            "market_capitalization",
            self.market_capitalization.clone().into_bound_py_any(py)?,
        )?;
        kwargs.set_item(
            "minus_cash_and_cash_equivalents",
            self.minus_cash_and_cash_equivalents
                .clone()
                .into_bound_py_any(py)?,
        )?;
        kwargs.set_item(
            "add_total_debt",
            self.add_total_debt.clone().into_bound_py_any(py)?,
        )?;
        kwargs.set_item(
            "enterprise_value",
            self.enterprise_value.clone().into_bound_py_any(py)?,
        )?;
        Ok((PyTuple::empty(py), kwargs))
    }
}

impl From<libfmp::responses::statements::summaries::EnterpriseValue> for EnterpriseValue {
    fn from(value: libfmp::responses::statements::summaries::EnterpriseValue) -> Self {
        Self {
            symbol: value.symbol.into_inner(),
            date: value.date.into_inner(),
            stock_price: value.stock_price,
            number_of_shares: value.number_of_shares,
            market_capitalization: value.market_capitalization,
            minus_cash_and_cash_equivalents: value.minus_cash_and_cash_equivalents,
            add_total_debt: value.add_total_debt,
            enterprise_value: value.enterprise_value,
        }
    }
}
