[package]
name = "libfmp"
version.workspace = true
edition.workspace = true
repository.workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
chrono.workspace = true
http.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
url.workspace = true

[dev-dependencies]
tokio.workspace = true
