// @generated by gen_namespaces; do not edit by hand.

use std::sync::Arc;

use libfmp::endpoints::funds::{
    EtfAssetExposureQuery, EtfCountryWeightingsQuery, EtfHoldingsQuery, EtfInfoQuery,
    EtfSectorWeightingsQuery, FundDisclosureDatesQuery, FundDisclosureHolderSearchQuery,
    FundDisclosureQuery, LatestFundDisclosureHoldersQuery,
};
use pyo3::prelude::*;
use pyo3_stub_gen::derive::{gen_stub_pyclass, gen_stub_pymethods};

use crate::args;
use crate::errors::to_py_error;
use crate::models::funds::{
    EtfAssetExposure, EtfCountryWeighting, EtfFundHolding, EtfFundInfo, EtfSectorWeighting,
    FundDisclosure, FundDisclosureHolder, FundDisclosureSearchResult,
};
use crate::models::institutional_ownership::Form13fFilingDate;
use crate::runtime::{ClientHandle, block_on};

/// Funds endpoints for a single client, exposed as `client.funds`.
#[gen_stub_pyclass]
#[pyclass(module = "fmp._native.funds", frozen)]
pub(crate) struct FundsNamespace {
    builder: Arc<ClientHandle>,
}

impl FundsNamespace {
    pub(crate) fn new(builder: Arc<ClientHandle>) -> Self {
        Self { builder }
    }
}

#[gen_stub_pymethods]
#[pymethods]
impl FundsNamespace {
    /// Retrieves the worldwide holdings of one ETF or mutual fund.
    #[pyo3(signature = (symbol))]
    fn etf_holdings(&self, py: Python<'_>, symbol: &str) -> PyResult<Vec<EtfFundHolding>> {
        let query = etf_holdings_query(symbol)?;
        let builder = self.builder.clone();
        let rows = py.detach(move || {
            block_on(
                builder,
                |client| async move { client.etf_holdings(query).await },
            )
        })?;
        rows.map(|items| items.into_iter().map(EtfFundHolding::from).collect())
            .map_err(to_py_error)
    }

    /// Retrieves worldwide descriptive and trading information for one fund.
    #[pyo3(signature = (symbol))]
    fn etf_info(&self, py: Python<'_>, symbol: &str) -> PyResult<Vec<EtfFundInfo>> {
        let query = etf_info_query(symbol)?;
        let builder = self.builder.clone();
        let rows = py.detach(move || {
            block_on(
                builder,
                |client| async move { client.etf_info(query).await },
            )
        })?;
        rows.map(|items| items.into_iter().map(EtfFundInfo::from).collect())
            .map_err(to_py_error)
    }

    /// Retrieves the worldwide country allocation for one ETF or mutual fund.
    #[pyo3(signature = (symbol))]
    fn etf_country_weightings(
        &self,
        py: Python<'_>,
        symbol: &str,
    ) -> PyResult<Vec<EtfCountryWeighting>> {
        let query = etf_country_weightings_query(symbol)?;
        let builder = self.builder.clone();
        let rows = py.detach(move || {
            block_on(builder, |client| async move {
                client.etf_country_weightings(query).await
            })
        })?;
        rows.map(|items| items.into_iter().map(EtfCountryWeighting::from).collect())
            .map_err(to_py_error)
    }

    /// Retrieves the worldwide ETF exposure to one requested asset.
    #[pyo3(signature = (symbol))]
    fn etf_asset_exposure(&self, py: Python<'_>, symbol: &str) -> PyResult<Vec<EtfAssetExposure>> {
        let query = etf_asset_exposure_query(symbol)?;
        let builder = self.builder.clone();
        let rows = py.detach(move || {
            block_on(builder, |client| async move {
                client.etf_asset_exposure(query).await
            })
        })?;
        rows.map(|items| items.into_iter().map(EtfAssetExposure::from).collect())
            .map_err(to_py_error)
    }

    /// Retrieves the worldwide sector allocation for one ETF or mutual fund.
    #[pyo3(signature = (symbol))]
    fn etf_sector_weightings(
        &self,
        py: Python<'_>,
        symbol: &str,
    ) -> PyResult<Vec<EtfSectorWeighting>> {
        let query = etf_sector_weightings_query(symbol)?;
        let builder = self.builder.clone();
        let rows = py.detach(move || {
            block_on(builder, |client| async move {
                client.etf_sector_weightings(query).await
            })
        })?;
        rows.map(|items| items.into_iter().map(EtfSectorWeighting::from).collect())
            .map_err(to_py_error)
    }

    /// Retrieves the latest US fund disclosures holding one requested asset.
    #[pyo3(signature = (symbol))]
    fn latest_disclosure_holders(
        &self,
        py: Python<'_>,
        symbol: &str,
    ) -> PyResult<Vec<FundDisclosureHolder>> {
        let query = latest_disclosure_holders_query(symbol)?;
        let builder = self.builder.clone();
        let rows = py.detach(move || {
            block_on(builder, |client| async move {
                client.latest_fund_disclosure_holders(query).await
            })
        })?;
        rows.map(|items| items.into_iter().map(FundDisclosureHolder::from).collect())
            .map_err(to_py_error)
    }

    /// Retrieves positions from one US mutual-fund disclosure period.
    #[pyo3(signature = (symbol, year, quarter, *, cik=None))]
    fn disclosures(
        &self,
        py: Python<'_>,
        symbol: &str,
        year: i64,
        quarter: i64,
        cik: Option<&str>,
    ) -> PyResult<Vec<FundDisclosure>> {
        let query = disclosures_query(symbol, year, quarter, cik)?;
        let builder = self.builder.clone();
        let rows = py.detach(move || {
            block_on(builder, |client| async move {
                client.fund_disclosures(query).await
            })
        })?;
        rows.map(|items| items.into_iter().map(FundDisclosure::from).collect())
            .map_err(to_py_error)
    }

    /// Searches US mutual-fund and ETF disclosure holders by exact name text.
    #[pyo3(signature = (name))]
    fn search_disclosure_holders(
        &self,
        py: Python<'_>,
        name: &str,
    ) -> PyResult<Vec<FundDisclosureSearchResult>> {
        let query = search_disclosure_holders_query(name)?;
        let builder = self.builder.clone();
        let rows = py.detach(move || {
            block_on(builder, |client| async move {
                client.search_fund_disclosure_holders(query).await
            })
        })?;
        rows.map(|items| {
            items
                .into_iter()
                .map(FundDisclosureSearchResult::from)
                .collect()
        })
        .map_err(to_py_error)
    }

    /// Retrieves available US fund-disclosure reporting dates.
    #[pyo3(signature = (symbol, *, cik=None))]
    fn disclosure_dates(
        &self,
        py: Python<'_>,
        symbol: &str,
        cik: Option<&str>,
    ) -> PyResult<Vec<Form13fFilingDate>> {
        let query = disclosure_dates_query(symbol, cik)?;
        let builder = self.builder.clone();
        let rows = py.detach(move || {
            block_on(builder, |client| async move {
                client.fund_disclosure_dates(query).await
            })
        })?;
        rows.map(|items| items.into_iter().map(Form13fFilingDate::from).collect())
            .map_err(to_py_error)
    }
}

/// Builds the `EtfHoldingsQuery` for `FundsNamespace::etf_holdings` from validated Python arguments.
fn etf_holdings_query(symbol: &str) -> PyResult<EtfHoldingsQuery> {
    let symbol = args::ticker("symbol", symbol)?;
    Ok(EtfHoldingsQuery::new(symbol))
}

/// Builds the `EtfInfoQuery` for `FundsNamespace::etf_info` from validated Python arguments.
fn etf_info_query(symbol: &str) -> PyResult<EtfInfoQuery> {
    let symbol = args::ticker("symbol", symbol)?;
    Ok(EtfInfoQuery::new(symbol))
}

/// Builds the `EtfCountryWeightingsQuery` for `FundsNamespace::etf_country_weightings` from validated Python arguments.
fn etf_country_weightings_query(symbol: &str) -> PyResult<EtfCountryWeightingsQuery> {
    let symbol = args::ticker("symbol", symbol)?;
    Ok(EtfCountryWeightingsQuery::new(symbol))
}

/// Builds the `EtfAssetExposureQuery` for `FundsNamespace::etf_asset_exposure` from validated Python arguments.
fn etf_asset_exposure_query(symbol: &str) -> PyResult<EtfAssetExposureQuery> {
    let symbol = args::ticker("symbol", symbol)?;
    Ok(EtfAssetExposureQuery::new(symbol))
}

/// Builds the `EtfSectorWeightingsQuery` for `FundsNamespace::etf_sector_weightings` from validated Python arguments.
fn etf_sector_weightings_query(symbol: &str) -> PyResult<EtfSectorWeightingsQuery> {
    let symbol = args::ticker("symbol", symbol)?;
    Ok(EtfSectorWeightingsQuery::new(symbol))
}

/// Builds the `LatestFundDisclosureHoldersQuery` for `FundsNamespace::latest_disclosure_holders` from validated Python arguments.
fn latest_disclosure_holders_query(symbol: &str) -> PyResult<LatestFundDisclosureHoldersQuery> {
    let symbol = args::ticker("symbol", symbol)?;
    Ok(LatestFundDisclosureHoldersQuery::new(symbol))
}

/// Builds the `FundDisclosureQuery` for `FundsNamespace::disclosures` from validated Python arguments.
fn disclosures_query(
    symbol: &str,
    year: i64,
    quarter: i64,
    cik: Option<&str>,
) -> PyResult<FundDisclosureQuery> {
    let symbol = args::ticker("symbol", symbol)?;
    let year = args::year("year", year)?;
    let quarter = args::quarter("quarter", quarter)?;
    let cik = args::optional("cik", cik, args::cik)?;
    let mut query = FundDisclosureQuery::new(symbol, year, quarter);
    if let Some(cik) = cik {
        query = query.with_cik(cik);
    }
    Ok(query)
}

/// Builds the `FundDisclosureHolderSearchQuery` for `FundsNamespace::search_disclosure_holders` from validated Python arguments.
fn search_disclosure_holders_query(name: &str) -> PyResult<FundDisclosureHolderSearchQuery> {
    let name = args::search_term("name", name)?;
    Ok(FundDisclosureHolderSearchQuery::new(name))
}

/// Builds the `FundDisclosureDatesQuery` for `FundsNamespace::disclosure_dates` from validated Python arguments.
fn disclosure_dates_query(symbol: &str, cik: Option<&str>) -> PyResult<FundDisclosureDatesQuery> {
    let symbol = args::ticker("symbol", symbol)?;
    let cik = args::optional("cik", cik, args::cik)?;
    let mut query = FundDisclosureDatesQuery::new(symbol);
    if let Some(cik) = cik {
        query = query.with_cik(cik);
    }
    Ok(query)
}
