// @generated by gen_namespaces; do not edit by hand.

use std::sync::Arc;

use libfmp::endpoints::news::{
    ArticlesQuery, LatestCryptoNewsQuery, LatestForexNewsQuery, LatestGeneralNewsQuery,
    LatestPressReleasesQuery, LatestStockNewsQuery, SearchCryptoNewsQuery, SearchForexNewsQuery,
    SearchPressReleasesQuery, SearchStockNewsQuery,
};
use pyo3::prelude::*;
use pyo3_stub_gen::derive::{gen_stub_pyclass, gen_stub_pymethods};

use crate::args;
use crate::errors::to_py_error;
use crate::models::news::{Article, NewsArticle};
use crate::runtime::{ClientHandle, block_on};

/// News endpoints for a single client, exposed as `client.news`.
#[gen_stub_pyclass]
#[pyclass(module = "fmp._native.news", frozen)]
pub(crate) struct NewsNamespace {
    builder: Arc<ClientHandle>,
}

impl NewsNamespace {
    pub(crate) fn new(builder: Arc<ClientHandle>) -> Self {
        Self { builder }
    }
}

#[gen_stub_pymethods]
#[pymethods]
impl NewsNamespace {
    /// Retrieves US-authored Financial Modeling Prep articles.
    #[pyo3(signature = (*, page=None, limit=None))]
    fn articles(
        &self,
        py: Python<'_>,
        page: Option<i64>,
        limit: Option<i64>,
    ) -> PyResult<Vec<Article>> {
        let query = articles_query(page, limit)?;
        let builder = self.builder.clone();
        let rows = py.detach(move || {
            block_on(
                builder,
                |client| async move { client.articles(query).await },
            )
        })?;
        rows.map(|items| items.into_iter().map(Article::from).collect())
            .map_err(to_py_error)
    }

    /// Retrieves the latest worldwide general-news articles.
    #[pyo3(signature = (*, from_=None, to=None, page=None, limit=None))]
    fn latest_general_news(
        &self,
        py: Python<'_>,
        from_: Option<args::DateArg>,
        to: Option<args::DateArg>,
        page: Option<i64>,
        limit: Option<i64>,
    ) -> PyResult<Vec<NewsArticle>> {
        let query = latest_general_news_query(from_, to, page, limit)?;
        let builder = self.builder.clone();
        let rows = py.detach(move || {
            block_on(builder, |client| async move {
                client.latest_general_news(query).await
            })
        })?;
        rows.map(|items| items.into_iter().map(NewsArticle::from).collect())
            .map_err(to_py_error)
    }

    /// Retrieves the latest US press releases.
    #[pyo3(signature = (*, from_=None, to=None, page=None, limit=None))]
    fn latest_press_releases(
        &self,
        py: Python<'_>,
        from_: Option<args::DateArg>,
        to: Option<args::DateArg>,
        page: Option<i64>,
        limit: Option<i64>,
    ) -> PyResult<Vec<NewsArticle>> {
        let query = latest_press_releases_query(from_, to, page, limit)?;
        let builder = self.builder.clone();
        let rows = py.detach(move || {
            block_on(builder, |client| async move {
                client.latest_press_releases(query).await
            })
        })?;
        rows.map(|items| items.into_iter().map(NewsArticle::from).collect())
            .map_err(to_py_error)
    }

    /// Retrieves the latest stock-news articles.
    #[pyo3(signature = (*, from_=None, to=None, page=None, limit=None))]
    fn latest_stock_news(
        &self,
        py: Python<'_>,
        from_: Option<args::DateArg>,
        to: Option<args::DateArg>,
        page: Option<i64>,
        limit: Option<i64>,
    ) -> PyResult<Vec<NewsArticle>> {
        let query = latest_stock_news_query(from_, to, page, limit)?;
        let builder = self.builder.clone();
        let rows = py.detach(move || {
            block_on(builder, |client| async move {
                client.latest_stock_news(query).await
            })
        })?;
        rows.map(|items| items.into_iter().map(NewsArticle::from).collect())
            .map_err(to_py_error)
    }

    /// Retrieves the latest cryptocurrency-news articles.
    #[pyo3(signature = (*, from_=None, to=None, page=None, limit=None))]
    fn latest_crypto_news(
        &self,
        py: Python<'_>,
        from_: Option<args::DateArg>,
        to: Option<args::DateArg>,
        page: Option<i64>,
        limit: Option<i64>,
    ) -> PyResult<Vec<NewsArticle>> {
        let query = latest_crypto_news_query(from_, to, page, limit)?;
        let builder = self.builder.clone();
        let rows = py.detach(move || {
            block_on(builder, |client| async move {
                client.latest_crypto_news(query).await
            })
        })?;
        rows.map(|items| items.into_iter().map(NewsArticle::from).collect())
            .map_err(to_py_error)
    }

    /// Retrieves the latest foreign-exchange-news articles.
    #[pyo3(signature = (*, from_=None, to=None, page=None, limit=None))]
    fn latest_forex_news(
        &self,
        py: Python<'_>,
        from_: Option<args::DateArg>,
        to: Option<args::DateArg>,
        page: Option<i64>,
        limit: Option<i64>,
    ) -> PyResult<Vec<NewsArticle>> {
        let query = latest_forex_news_query(from_, to, page, limit)?;
        let builder = self.builder.clone();
        let rows = py.detach(move || {
            block_on(builder, |client| async move {
                client.latest_forex_news(query).await
            })
        })?;
        rows.map(|items| items.into_iter().map(NewsArticle::from).collect())
            .map_err(to_py_error)
    }

    /// Searches US press releases for an ordered non-empty ticker list.
    #[pyo3(signature = (symbols, *, from_=None, to=None, page=None, limit=None))]
    fn search_press_releases(
        &self,
        py: Python<'_>,
        symbols: args::SymbolsArg,
        from_: Option<args::DateArg>,
        to: Option<args::DateArg>,
        page: Option<i64>,
        limit: Option<i64>,
    ) -> PyResult<Vec<NewsArticle>> {
        let query = search_press_releases_query(symbols, from_, to, page, limit)?;
        let builder = self.builder.clone();
        let rows = py.detach(move || {
            block_on(builder, |client| async move {
                client.search_press_releases(query).await
            })
        })?;
        rows.map(|items| items.into_iter().map(NewsArticle::from).collect())
            .map_err(to_py_error)
    }

    /// Searches stock news for an ordered non-empty ticker list.
    #[pyo3(signature = (symbols, *, from_=None, to=None, page=None, limit=None))]
    fn search_stock_news(
        &self,
        py: Python<'_>,
        symbols: args::SymbolsArg,
        from_: Option<args::DateArg>,
        to: Option<args::DateArg>,
        page: Option<i64>,
        limit: Option<i64>,
    ) -> PyResult<Vec<NewsArticle>> {
        let query = search_stock_news_query(symbols, from_, to, page, limit)?;
        let builder = self.builder.clone();
        let rows = py.detach(move || {
            block_on(builder, |client| async move {
                client.search_stock_news(query).await
            })
        })?;
        rows.map(|items| items.into_iter().map(NewsArticle::from).collect())
            .map_err(to_py_error)
    }

    /// Searches cryptocurrency news for an ordered non-empty ticker list.
    #[pyo3(signature = (symbols, *, from_=None, to=None, page=None, limit=None))]
    fn search_crypto_news(
        &self,
        py: Python<'_>,
        symbols: args::SymbolsArg,
        from_: Option<args::DateArg>,
        to: Option<args::DateArg>,
        page: Option<i64>,
        limit: Option<i64>,
    ) -> PyResult<Vec<NewsArticle>> {
        let query = search_crypto_news_query(symbols, from_, to, page, limit)?;
        let builder = self.builder.clone();
        let rows = py.detach(move || {
            block_on(builder, |client| async move {
                client.search_crypto_news(query).await
            })
        })?;
        rows.map(|items| items.into_iter().map(NewsArticle::from).collect())
            .map_err(to_py_error)
    }

    /// Searches foreign-exchange news for an ordered non-empty ticker list.
    #[pyo3(signature = (symbols, *, from_=None, to=None, page=None, limit=None))]
    fn search_forex_news(
        &self,
        py: Python<'_>,
        symbols: args::SymbolsArg,
        from_: Option<args::DateArg>,
        to: Option<args::DateArg>,
        page: Option<i64>,
        limit: Option<i64>,
    ) -> PyResult<Vec<NewsArticle>> {
        let query = search_forex_news_query(symbols, from_, to, page, limit)?;
        let builder = self.builder.clone();
        let rows = py.detach(move || {
            block_on(builder, |client| async move {
                client.search_forex_news(query).await
            })
        })?;
        rows.map(|items| items.into_iter().map(NewsArticle::from).collect())
            .map_err(to_py_error)
    }
}

/// Builds the `ArticlesQuery` for `NewsNamespace::articles` from validated Python arguments.
fn articles_query(page: Option<i64>, limit: Option<i64>) -> PyResult<ArticlesQuery> {
    let page = args::optional("page", page, args::page)?;
    let limit = args::optional("limit", limit, args::limit)?;
    let mut query = ArticlesQuery::new();
    if let Some(page) = page {
        query = query.with_page(page);
    }
    if let Some(limit) = limit {
        query = query.with_limit(limit);
    }
    Ok(query)
}

/// Builds the `LatestGeneralNewsQuery` for `NewsNamespace::latest_general_news` from validated Python arguments.
fn latest_general_news_query(
    from_: Option<args::DateArg>,
    to: Option<args::DateArg>,
    page: Option<i64>,
    limit: Option<i64>,
) -> PyResult<LatestGeneralNewsQuery> {
    let from_ = args::optional("from_", from_, args::date)?;
    let to = args::optional("to", to, args::date)?;
    let page = args::optional("page", page, args::page)?;
    let limit = args::optional("limit", limit, args::limit)?;
    let mut query = LatestGeneralNewsQuery::new();
    if let Some(from_) = from_ {
        query = query.with_from(from_);
    }
    if let Some(to) = to {
        query = query.with_to(to);
    }
    if let Some(page) = page {
        query = query.with_page(page);
    }
    if let Some(limit) = limit {
        query = query.with_limit(limit);
    }
    Ok(query)
}

/// Builds the `LatestPressReleasesQuery` for `NewsNamespace::latest_press_releases` from validated Python arguments.
fn latest_press_releases_query(
    from_: Option<args::DateArg>,
    to: Option<args::DateArg>,
    page: Option<i64>,
    limit: Option<i64>,
) -> PyResult<LatestPressReleasesQuery> {
    let from_ = args::optional("from_", from_, args::date)?;
    let to = args::optional("to", to, args::date)?;
    let page = args::optional("page", page, args::page)?;
    let limit = args::optional("limit", limit, args::limit)?;
    let mut query = LatestPressReleasesQuery::new();
    if let Some(from_) = from_ {
        query = query.with_from(from_);
    }
    if let Some(to) = to {
        query = query.with_to(to);
    }
    if let Some(page) = page {
        query = query.with_page(page);
    }
    if let Some(limit) = limit {
        query = query.with_limit(limit);
    }
    Ok(query)
}

/// Builds the `LatestStockNewsQuery` for `NewsNamespace::latest_stock_news` from validated Python arguments.
fn latest_stock_news_query(
    from_: Option<args::DateArg>,
    to: Option<args::DateArg>,
    page: Option<i64>,
    limit: Option<i64>,
) -> PyResult<LatestStockNewsQuery> {
    let from_ = args::optional("from_", from_, args::date)?;
    let to = args::optional("to", to, args::date)?;
    let page = args::optional("page", page, args::page)?;
    let limit = args::optional("limit", limit, args::limit)?;
    let mut query = LatestStockNewsQuery::new();
    if let Some(from_) = from_ {
        query = query.with_from(from_);
    }
    if let Some(to) = to {
        query = query.with_to(to);
    }
    if let Some(page) = page {
        query = query.with_page(page);
    }
    if let Some(limit) = limit {
        query = query.with_limit(limit);
    }
    Ok(query)
}

/// Builds the `LatestCryptoNewsQuery` for `NewsNamespace::latest_crypto_news` from validated Python arguments.
fn latest_crypto_news_query(
    from_: Option<args::DateArg>,
    to: Option<args::DateArg>,
    page: Option<i64>,
    limit: Option<i64>,
) -> PyResult<LatestCryptoNewsQuery> {
    let from_ = args::optional("from_", from_, args::date)?;
    let to = args::optional("to", to, args::date)?;
    let page = args::optional("page", page, args::page)?;
    let limit = args::optional("limit", limit, args::limit)?;
    let mut query = LatestCryptoNewsQuery::new();
    if let Some(from_) = from_ {
        query = query.with_from(from_);
    }
    if let Some(to) = to {
        query = query.with_to(to);
    }
    if let Some(page) = page {
        query = query.with_page(page);
    }
    if let Some(limit) = limit {
        query = query.with_limit(limit);
    }
    Ok(query)
}

/// Builds the `LatestForexNewsQuery` for `NewsNamespace::latest_forex_news` from validated Python arguments.
fn latest_forex_news_query(
    from_: Option<args::DateArg>,
    to: Option<args::DateArg>,
    page: Option<i64>,
    limit: Option<i64>,
) -> PyResult<LatestForexNewsQuery> {
    let from_ = args::optional("from_", from_, args::date)?;
    let to = args::optional("to", to, args::date)?;
    let page = args::optional("page", page, args::page)?;
    let limit = args::optional("limit", limit, args::limit)?;
    let mut query = LatestForexNewsQuery::new();
    if let Some(from_) = from_ {
        query = query.with_from(from_);
    }
    if let Some(to) = to {
        query = query.with_to(to);
    }
    if let Some(page) = page {
        query = query.with_page(page);
    }
    if let Some(limit) = limit {
        query = query.with_limit(limit);
    }
    Ok(query)
}

/// Builds the `SearchPressReleasesQuery` for `NewsNamespace::search_press_releases` from validated Python arguments.
fn search_press_releases_query(
    symbols: args::SymbolsArg,
    from_: Option<args::DateArg>,
    to: Option<args::DateArg>,
    page: Option<i64>,
    limit: Option<i64>,
) -> PyResult<SearchPressReleasesQuery> {
    let symbols = args::ticker_list("symbols", symbols)?;
    let from_ = args::optional("from_", from_, args::date)?;
    let to = args::optional("to", to, args::date)?;
    let page = args::optional("page", page, args::page)?;
    let limit = args::optional("limit", limit, args::limit)?;
    let mut query = SearchPressReleasesQuery::new(symbols);
    if let Some(from_) = from_ {
        query = query.with_from(from_);
    }
    if let Some(to) = to {
        query = query.with_to(to);
    }
    if let Some(page) = page {
        query = query.with_page(page);
    }
    if let Some(limit) = limit {
        query = query.with_limit(limit);
    }
    Ok(query)
}

/// Builds the `SearchStockNewsQuery` for `NewsNamespace::search_stock_news` from validated Python arguments.
fn search_stock_news_query(
    symbols: args::SymbolsArg,
    from_: Option<args::DateArg>,
    to: Option<args::DateArg>,
    page: Option<i64>,
    limit: Option<i64>,
) -> PyResult<SearchStockNewsQuery> {
    let symbols = args::ticker_list("symbols", symbols)?;
    let from_ = args::optional("from_", from_, args::date)?;
    let to = args::optional("to", to, args::date)?;
    let page = args::optional("page", page, args::page)?;
    let limit = args::optional("limit", limit, args::limit)?;
    let mut query = SearchStockNewsQuery::new(symbols);
    if let Some(from_) = from_ {
        query = query.with_from(from_);
    }
    if let Some(to) = to {
        query = query.with_to(to);
    }
    if let Some(page) = page {
        query = query.with_page(page);
    }
    if let Some(limit) = limit {
        query = query.with_limit(limit);
    }
    Ok(query)
}

/// Builds the `SearchCryptoNewsQuery` for `NewsNamespace::search_crypto_news` from validated Python arguments.
fn search_crypto_news_query(
    symbols: args::SymbolsArg,
    from_: Option<args::DateArg>,
    to: Option<args::DateArg>,
    page: Option<i64>,
    limit: Option<i64>,
) -> PyResult<SearchCryptoNewsQuery> {
    let symbols = args::ticker_list("symbols", symbols)?;
    let from_ = args::optional("from_", from_, args::date)?;
    let to = args::optional("to", to, args::date)?;
    let page = args::optional("page", page, args::page)?;
    let limit = args::optional("limit", limit, args::limit)?;
    let mut query = SearchCryptoNewsQuery::new(symbols);
    if let Some(from_) = from_ {
        query = query.with_from(from_);
    }
    if let Some(to) = to {
        query = query.with_to(to);
    }
    if let Some(page) = page {
        query = query.with_page(page);
    }
    if let Some(limit) = limit {
        query = query.with_limit(limit);
    }
    Ok(query)
}

/// Builds the `SearchForexNewsQuery` for `NewsNamespace::search_forex_news` from validated Python arguments.
fn search_forex_news_query(
    symbols: args::SymbolsArg,
    from_: Option<args::DateArg>,
    to: Option<args::DateArg>,
    page: Option<i64>,
    limit: Option<i64>,
) -> PyResult<SearchForexNewsQuery> {
    let symbols = args::ticker_list("symbols", symbols)?;
    let from_ = args::optional("from_", from_, args::date)?;
    let to = args::optional("to", to, args::date)?;
    let page = args::optional("page", page, args::page)?;
    let limit = args::optional("limit", limit, args::limit)?;
    let mut query = SearchForexNewsQuery::new(symbols);
    if let Some(from_) = from_ {
        query = query.with_from(from_);
    }
    if let Some(to) = to {
        query = query.with_to(to);
    }
    if let Some(page) = page {
        query = query.with_page(page);
    }
    if let Some(limit) = limit {
        query = query.with_limit(limit);
    }
    Ok(query)
}
