// @generated by gen_namespaces; do not edit by hand.

use std::sync::Arc;

use libfmp::ClientBuilder;
use libfmp::endpoints::tipranks::{
    PointInTimeRatingsByAnalystQuery, PointInTimeRatingsBySymbolQuery, TipRanksAnalystSummaryQuery,
    TipRanksAnalystsQuery, TipRanksFirmSummaryQuery, TipRanksSearchQuery,
    TipRanksSymbolSummaryQuery,
};
use pyo3::prelude::*;
use pyo3_stub_gen::derive::{gen_stub_pyclass, gen_stub_pymethods};

use crate::args;
use crate::errors::to_py_error;
use crate::models::tipranks::{
    TipRanksAnalystProfile, TipRanksAnalystSummary, TipRanksFirmSummary, TipRanksPointInTimeRating,
    TipRanksRatingSearchResult, TipRanksSymbolSummary,
};
use crate::runtime::block_on;

/// Tipranks endpoints for a single client, exposed as `client.tipranks`.
#[gen_stub_pyclass]
#[pyclass(module = "fmp._native.tipranks", frozen)]
pub(crate) struct TipranksNamespace {
    builder: Arc<ClientBuilder>,
}

impl TipranksNamespace {
    pub(crate) fn new(builder: Arc<ClientBuilder>) -> Self {
        Self { builder }
    }
}

#[gen_stub_pymethods]
#[pymethods]
impl TipranksNamespace {
    /// Retrieves individual analyst ratings from the TipRanks add-on.
    #[pyo3(signature = (*, expert_uid=None, symbol=None, from_=None, to=None, limit=None, page=None, nonadjusted=None))]
    #[allow(clippy::too_many_arguments)]
    fn search_ratings(
        &self,
        py: Python<'_>,
        expert_uid: Option<&str>,
        symbol: Option<&str>,
        from_: Option<args::DateArg>,
        to: Option<args::DateArg>,
        limit: Option<i64>,
        page: Option<i64>,
        nonadjusted: Option<bool>,
    ) -> PyResult<Vec<TipRanksRatingSearchResult>> {
        let query = search_ratings_query(expert_uid, symbol, from_, to, limit, page, nonadjusted)?;
        let builder = self.builder.clone();
        let rows = py.detach(move || {
            block_on(builder, |client| async move {
                client.search_tipranks_ratings(query).await
            })
        })?;
        rows.map(|items| {
            items
                .into_iter()
                .map(TipRanksRatingSearchResult::from)
                .collect()
        })
        .map_err(to_py_error)
    }

    /// Retrieves a ticker's analyst ratings as of an optional snapshot date.
    #[pyo3(signature = (symbol, *, date=None, limit=None, page=None, nonadjusted=None))]
    fn point_in_time_ratings_by_symbol(
        &self,
        py: Python<'_>,
        symbol: &str,
        date: Option<args::DateArg>,
        limit: Option<i64>,
        page: Option<i64>,
        nonadjusted: Option<bool>,
    ) -> PyResult<Vec<TipRanksPointInTimeRating>> {
        let query = point_in_time_ratings_by_symbol_query(symbol, date, limit, page, nonadjusted)?;
        let builder = self.builder.clone();
        let rows = py.detach(move || {
            block_on(builder, |client| async move {
                client.tipranks_point_in_time_ratings_by_symbol(query).await
            })
        })?;
        rows.map(|items| {
            items
                .into_iter()
                .map(TipRanksPointInTimeRating::from)
                .collect()
        })
        .map_err(to_py_error)
    }

    /// Retrieves an analyst's active coverage as of an optional snapshot date.
    #[pyo3(signature = (*, expert_uid=None, analyst_name=None, date=None, limit=None, page=None, nonadjusted=None))]
    #[allow(clippy::too_many_arguments)]
    fn point_in_time_ratings_by_analyst(
        &self,
        py: Python<'_>,
        expert_uid: Option<&str>,
        analyst_name: Option<&str>,
        date: Option<args::DateArg>,
        limit: Option<i64>,
        page: Option<i64>,
        nonadjusted: Option<bool>,
    ) -> PyResult<Vec<TipRanksPointInTimeRating>> {
        let query = point_in_time_ratings_by_analyst_query(
            expert_uid,
            analyst_name,
            date,
            limit,
            page,
            nonadjusted,
        )?;
        let builder = self.builder.clone();
        let rows = py.detach(move || {
            block_on(builder, |client| async move {
                client
                    .tipranks_point_in_time_ratings_by_analyst(query)
                    .await
            })
        })?;
        rows.map(|items| {
            items
                .into_iter()
                .map(TipRanksPointInTimeRating::from)
                .collect()
        })
        .map_err(to_py_error)
    }

    /// Retrieves a ticker's aggregate TipRanks ratings summary.
    #[pyo3(signature = (symbol, *, from_=None, to=None))]
    fn symbol_summary(
        &self,
        py: Python<'_>,
        symbol: &str,
        from_: Option<args::DateArg>,
        to: Option<args::DateArg>,
    ) -> PyResult<Vec<TipRanksSymbolSummary>> {
        let query = symbol_summary_query(symbol, from_, to)?;
        let builder = self.builder.clone();
        let rows = py.detach(move || {
            block_on(builder, |client| async move {
                client.tipranks_symbol_summary(query).await
            })
        })?;
        rows.map(|items| items.into_iter().map(TipRanksSymbolSummary::from).collect())
            .map_err(to_py_error)
    }

    /// Retrieves an analyst's aggregate TipRanks ratings summary.
    #[pyo3(signature = (expert_uid, *, from_=None, to=None))]
    fn analyst_summary(
        &self,
        py: Python<'_>,
        expert_uid: &str,
        from_: Option<args::DateArg>,
        to: Option<args::DateArg>,
    ) -> PyResult<Vec<TipRanksAnalystSummary>> {
        let query = analyst_summary_query(expert_uid, from_, to)?;
        let builder = self.builder.clone();
        let rows = py.detach(move || {
            block_on(builder, |client| async move {
                client.tipranks_analyst_summary(query).await
            })
        })?;
        rows.map(|items| {
            items
                .into_iter()
                .map(TipRanksAnalystSummary::from)
                .collect()
        })
        .map_err(to_py_error)
    }

    /// Retrieves a firm's aggregate TipRanks ratings summary.
    #[pyo3(signature = (firm_name, *, from_=None, to=None))]
    fn firm_summary(
        &self,
        py: Python<'_>,
        firm_name: &str,
        from_: Option<args::DateArg>,
        to: Option<args::DateArg>,
    ) -> PyResult<Vec<TipRanksFirmSummary>> {
        let query = firm_summary_query(firm_name, from_, to)?;
        let builder = self.builder.clone();
        let rows = py.detach(move || {
            block_on(builder, |client| async move {
                client.tipranks_firm_summary(query).await
            })
        })?;
        rows.map(|items| items.into_iter().map(TipRanksFirmSummary::from).collect())
            .map_err(to_py_error)
    }

    /// Retrieves analyst profiles from the TipRanks directory.
    #[pyo3(signature = (*, page=None, limit=None, firm_name=None, analyst_name=None))]
    fn analysts(
        &self,
        py: Python<'_>,
        page: Option<i64>,
        limit: Option<i64>,
        firm_name: Option<&str>,
        analyst_name: Option<&str>,
    ) -> PyResult<Vec<TipRanksAnalystProfile>> {
        let query = analysts_query(page, limit, firm_name, analyst_name)?;
        let builder = self.builder.clone();
        let rows = py.detach(move || {
            block_on(builder, |client| async move {
                client.tipranks_analysts(query).await
            })
        })?;
        rows.map(|items| {
            items
                .into_iter()
                .map(TipRanksAnalystProfile::from)
                .collect()
        })
        .map_err(to_py_error)
    }
}

/// Builds the `TipRanksSearchQuery` for `TipranksNamespace::search_ratings` from validated Python arguments.
fn search_ratings_query(
    expert_uid: Option<&str>,
    symbol: Option<&str>,
    from_: Option<args::DateArg>,
    to: Option<args::DateArg>,
    limit: Option<i64>,
    page: Option<i64>,
    nonadjusted: Option<bool>,
) -> PyResult<TipRanksSearchQuery> {
    let expert_uid = args::optional("expert_uid", expert_uid, args::tipranks_expert_uid)?;
    let symbol = args::optional("symbol", symbol, args::ticker)?;
    let from_ = args::optional("from_", from_, args::date)?;
    let to = args::optional("to", to, args::date)?;
    let limit = args::optional("limit", limit, args::limit)?;
    let page = args::optional("page", page, args::page)?;
    let nonadjusted = args::optional("nonadjusted", nonadjusted, args::boolean)?;
    let mut query = TipRanksSearchQuery::new();
    if let Some(expert_uid) = expert_uid {
        query = query.with_expert_uid(expert_uid);
    }
    if let Some(symbol) = symbol {
        query = query.with_symbol(symbol);
    }
    if let Some(from_) = from_ {
        query = query.with_from(from_);
    }
    if let Some(to) = to {
        query = query.with_to(to);
    }
    if let Some(limit) = limit {
        query = query.with_limit(limit);
    }
    if let Some(page) = page {
        query = query.with_page(page);
    }
    if let Some(nonadjusted) = nonadjusted {
        query = query.with_nonadjusted(nonadjusted);
    }
    Ok(query)
}

/// Builds the `PointInTimeRatingsBySymbolQuery` for `TipranksNamespace::point_in_time_ratings_by_symbol` from validated Python arguments.
fn point_in_time_ratings_by_symbol_query(
    symbol: &str,
    date: Option<args::DateArg>,
    limit: Option<i64>,
    page: Option<i64>,
    nonadjusted: Option<bool>,
) -> PyResult<PointInTimeRatingsBySymbolQuery> {
    let symbol = args::ticker("symbol", symbol)?;
    let date = args::optional("date", date, args::date)?;
    let limit = args::optional("limit", limit, args::limit)?;
    let page = args::optional("page", page, args::page)?;
    let nonadjusted = args::optional("nonadjusted", nonadjusted, args::boolean)?;
    let mut query = PointInTimeRatingsBySymbolQuery::new(symbol);
    if let Some(date) = date {
        query = query.with_date(date);
    }
    if let Some(limit) = limit {
        query = query.with_limit(limit);
    }
    if let Some(page) = page {
        query = query.with_page(page);
    }
    if let Some(nonadjusted) = nonadjusted {
        query = query.with_nonadjusted(nonadjusted);
    }
    Ok(query)
}

/// Builds the `PointInTimeRatingsByAnalystQuery` for `TipranksNamespace::point_in_time_ratings_by_analyst` from validated Python arguments.
fn point_in_time_ratings_by_analyst_query(
    expert_uid: Option<&str>,
    analyst_name: Option<&str>,
    date: Option<args::DateArg>,
    limit: Option<i64>,
    page: Option<i64>,
    nonadjusted: Option<bool>,
) -> PyResult<PointInTimeRatingsByAnalystQuery> {
    let expert_uid = args::optional("expert_uid", expert_uid, args::tipranks_expert_uid)?;
    let analyst_name = args::optional("analyst_name", analyst_name, args::search_term)?;
    let date = args::optional("date", date, args::date)?;
    let limit = args::optional("limit", limit, args::limit)?;
    let page = args::optional("page", page, args::page)?;
    let nonadjusted = args::optional("nonadjusted", nonadjusted, args::boolean)?;
    let mut query = PointInTimeRatingsByAnalystQuery::new();
    if let Some(expert_uid) = expert_uid {
        query = query.with_expert_uid(expert_uid);
    }
    if let Some(analyst_name) = analyst_name {
        query = query.with_analyst_name(analyst_name);
    }
    if let Some(date) = date {
        query = query.with_date(date);
    }
    if let Some(limit) = limit {
        query = query.with_limit(limit);
    }
    if let Some(page) = page {
        query = query.with_page(page);
    }
    if let Some(nonadjusted) = nonadjusted {
        query = query.with_nonadjusted(nonadjusted);
    }
    Ok(query)
}

/// Builds the `TipRanksSymbolSummaryQuery` for `TipranksNamespace::symbol_summary` from validated Python arguments.
fn symbol_summary_query(
    symbol: &str,
    from_: Option<args::DateArg>,
    to: Option<args::DateArg>,
) -> PyResult<TipRanksSymbolSummaryQuery> {
    let symbol = args::ticker("symbol", symbol)?;
    let from_ = args::optional("from_", from_, args::date)?;
    let to = args::optional("to", to, args::date)?;
    let mut query = TipRanksSymbolSummaryQuery::new(symbol);
    if let Some(from_) = from_ {
        query = query.with_from(from_);
    }
    if let Some(to) = to {
        query = query.with_to(to);
    }
    Ok(query)
}

/// Builds the `TipRanksAnalystSummaryQuery` for `TipranksNamespace::analyst_summary` from validated Python arguments.
fn analyst_summary_query(
    expert_uid: &str,
    from_: Option<args::DateArg>,
    to: Option<args::DateArg>,
) -> PyResult<TipRanksAnalystSummaryQuery> {
    let expert_uid = args::tipranks_expert_uid("expert_uid", expert_uid)?;
    let from_ = args::optional("from_", from_, args::date)?;
    let to = args::optional("to", to, args::date)?;
    let mut query = TipRanksAnalystSummaryQuery::new(expert_uid);
    if let Some(from_) = from_ {
        query = query.with_from(from_);
    }
    if let Some(to) = to {
        query = query.with_to(to);
    }
    Ok(query)
}

/// Builds the `TipRanksFirmSummaryQuery` for `TipranksNamespace::firm_summary` from validated Python arguments.
fn firm_summary_query(
    firm_name: &str,
    from_: Option<args::DateArg>,
    to: Option<args::DateArg>,
) -> PyResult<TipRanksFirmSummaryQuery> {
    let firm_name = args::search_term("firm_name", firm_name)?;
    let from_ = args::optional("from_", from_, args::date)?;
    let to = args::optional("to", to, args::date)?;
    let mut query = TipRanksFirmSummaryQuery::new(firm_name);
    if let Some(from_) = from_ {
        query = query.with_from(from_);
    }
    if let Some(to) = to {
        query = query.with_to(to);
    }
    Ok(query)
}

/// Builds the `TipRanksAnalystsQuery` for `TipranksNamespace::analysts` from validated Python arguments.
fn analysts_query(
    page: Option<i64>,
    limit: Option<i64>,
    firm_name: Option<&str>,
    analyst_name: Option<&str>,
) -> PyResult<TipRanksAnalystsQuery> {
    let page = args::optional("page", page, args::page)?;
    let limit = args::optional("limit", limit, args::limit)?;
    let firm_name = args::optional("firm_name", firm_name, args::search_term)?;
    let analyst_name = args::optional("analyst_name", analyst_name, args::search_term)?;
    let mut query = TipRanksAnalystsQuery::new();
    if let Some(page) = page {
        query = query.with_page(page);
    }
    if let Some(limit) = limit {
        query = query.with_limit(limit);
    }
    if let Some(firm_name) = firm_name {
        query = query.with_firm_name(firm_name);
    }
    if let Some(analyst_name) = analyst_name {
        query = query.with_analyst_name(analyst_name);
    }
    Ok(query)
}
