// @generated by gen_models; do not edit by hand.

use pyo3::IntoPyObjectExt;
use pyo3::prelude::*;
use pyo3::types::PyTuple;
use pyo3_stub_gen::derive::{gen_stub_pyclass, gen_stub_pymethods};

#[gen_stub_pyclass]
#[pyclass(module = "fmp._native.bulk.snapshots", frozen, from_py_object)]
#[derive(Clone)]
pub(crate) struct BulkStockRating {
    #[pyo3(get)]
    pub symbol: String,
    #[pyo3(get)]
    pub date: ::chrono::NaiveDate,
    #[pyo3(get)]
    pub rating: String,
    #[pyo3(get)]
    pub discounted_cash_flow_score: String,
    #[pyo3(get)]
    pub return_on_equity_score: String,
    #[pyo3(get)]
    pub return_on_assets_score: String,
    #[pyo3(get)]
    pub debt_to_equity_score: String,
    #[pyo3(get)]
    pub price_to_earnings_score: String,
    #[pyo3(get)]
    pub price_to_book_score: String,
}

#[gen_stub_pymethods]
#[pymethods]
impl BulkStockRating {
    #[new]
    #[allow(clippy::too_many_arguments)]
    #[allow(clippy::fn_params_excessive_bools)]
    #[pyo3(signature = (symbol, date, rating, discounted_cash_flow_score, return_on_equity_score, return_on_assets_score, debt_to_equity_score, price_to_earnings_score, price_to_book_score))]
    fn new(
        symbol: String,
        date: ::chrono::NaiveDate,
        rating: String,
        discounted_cash_flow_score: String,
        return_on_equity_score: String,
        return_on_assets_score: String,
        debt_to_equity_score: String,
        price_to_earnings_score: String,
        price_to_book_score: String,
    ) -> Self {
        Self {
            symbol,
            date,
            rating,
            discounted_cash_flow_score,
            return_on_equity_score,
            return_on_assets_score,
            debt_to_equity_score,
            price_to_earnings_score,
            price_to_book_score,
        }
    }

    #[allow(clippy::clone_on_copy)]
    fn __getnewargs__<'py>(&self, py: Python<'py>) -> PyResult<Bound<'py, PyTuple>> {
        let members: Vec<Bound<'py, PyAny>> = vec![
            self.symbol.clone().into_bound_py_any(py)?,
            self.date.clone().into_bound_py_any(py)?,
            self.rating.clone().into_bound_py_any(py)?,
            self.discounted_cash_flow_score
                .clone()
                .into_bound_py_any(py)?,
            self.return_on_equity_score.clone().into_bound_py_any(py)?,
            self.return_on_assets_score.clone().into_bound_py_any(py)?,
            self.debt_to_equity_score.clone().into_bound_py_any(py)?,
            self.price_to_earnings_score.clone().into_bound_py_any(py)?,
            self.price_to_book_score.clone().into_bound_py_any(py)?,
        ];
        PyTuple::new(py, members)
    }
}

impl From<libfmp::responses::bulk::BulkStockRating> for BulkStockRating {
    fn from(value: libfmp::responses::bulk::BulkStockRating) -> Self {
        Self {
            symbol: value.symbol.into_inner(),
            date: value.date.into_inner(),
            rating: value.rating,
            discounted_cash_flow_score: value.discounted_cash_flow_score.into_inner(),
            return_on_equity_score: value.return_on_equity_score.into_inner(),
            return_on_assets_score: value.return_on_assets_score.into_inner(),
            debt_to_equity_score: value.debt_to_equity_score.into_inner(),
            price_to_earnings_score: value.price_to_earnings_score.into_inner(),
            price_to_book_score: value.price_to_book_score.into_inner(),
        }
    }
}

#[gen_stub_pyclass]
#[pyclass(module = "fmp._native.bulk.snapshots", frozen, from_py_object)]
#[derive(Clone)]
pub(crate) struct BulkDcfValuation {
    #[pyo3(get)]
    pub symbol: String,
    #[pyo3(get)]
    pub date: ::chrono::NaiveDate,
    #[pyo3(get)]
    pub dcf: String,
    #[pyo3(get)]
    pub stock_price: String,
}

#[gen_stub_pymethods]
#[pymethods]
impl BulkDcfValuation {
    #[new]
    #[allow(clippy::too_many_arguments)]
    #[allow(clippy::fn_params_excessive_bools)]
    #[pyo3(signature = (symbol, date, dcf, stock_price))]
    fn new(symbol: String, date: ::chrono::NaiveDate, dcf: String, stock_price: String) -> Self {
        Self {
            symbol,
            date,
            dcf,
            stock_price,
        }
    }

    #[allow(clippy::clone_on_copy)]
    fn __getnewargs__<'py>(&self, py: Python<'py>) -> PyResult<Bound<'py, PyTuple>> {
        let members: Vec<Bound<'py, PyAny>> = vec![
            self.symbol.clone().into_bound_py_any(py)?,
            self.date.clone().into_bound_py_any(py)?,
            self.dcf.clone().into_bound_py_any(py)?,
            self.stock_price.clone().into_bound_py_any(py)?,
        ];
        PyTuple::new(py, members)
    }
}

impl From<libfmp::responses::bulk::BulkDcfValuation> for BulkDcfValuation {
    fn from(value: libfmp::responses::bulk::BulkDcfValuation) -> Self {
        Self {
            symbol: value.symbol.into_inner(),
            date: value.date.into_inner(),
            dcf: value.dcf.into_inner(),
            stock_price: value.stock_price.into_inner(),
        }
    }
}

#[gen_stub_pyclass]
#[pyclass(module = "fmp._native.bulk.snapshots", frozen, from_py_object)]
#[derive(Clone)]
pub(crate) struct BulkFinancialScore {
    #[pyo3(get)]
    pub symbol: String,
    #[pyo3(get)]
    pub reported_currency: String,
    #[pyo3(get)]
    pub altman_z_score: String,
    #[pyo3(get)]
    pub piotroski_score: String,
    #[pyo3(get)]
    pub working_capital: String,
    #[pyo3(get)]
    pub total_assets: String,
    #[pyo3(get)]
    pub retained_earnings: String,
    #[pyo3(get)]
    pub ebit: String,
    #[pyo3(get)]
    pub market_cap: String,
    #[pyo3(get)]
    pub total_liabilities: String,
    #[pyo3(get)]
    pub revenue: String,
}

#[gen_stub_pymethods]
#[pymethods]
impl BulkFinancialScore {
    #[new]
    #[allow(clippy::too_many_arguments)]
    #[allow(clippy::fn_params_excessive_bools)]
    #[pyo3(signature = (symbol, reported_currency, altman_z_score, piotroski_score, working_capital, total_assets, retained_earnings, ebit, market_cap, total_liabilities, revenue))]
    fn new(
        symbol: String,
        reported_currency: String,
        altman_z_score: String,
        piotroski_score: String,
        working_capital: String,
        total_assets: String,
        retained_earnings: String,
        ebit: String,
        market_cap: String,
        total_liabilities: String,
        revenue: String,
    ) -> Self {
        Self {
            symbol,
            reported_currency,
            altman_z_score,
            piotroski_score,
            working_capital,
            total_assets,
            retained_earnings,
            ebit,
            market_cap,
            total_liabilities,
            revenue,
        }
    }

    #[allow(clippy::clone_on_copy)]
    fn __getnewargs__<'py>(&self, py: Python<'py>) -> PyResult<Bound<'py, PyTuple>> {
        let members: Vec<Bound<'py, PyAny>> = vec![
            self.symbol.clone().into_bound_py_any(py)?,
            self.reported_currency.clone().into_bound_py_any(py)?,
            self.altman_z_score.clone().into_bound_py_any(py)?,
            self.piotroski_score.clone().into_bound_py_any(py)?,
            self.working_capital.clone().into_bound_py_any(py)?,
            self.total_assets.clone().into_bound_py_any(py)?,
            self.retained_earnings.clone().into_bound_py_any(py)?,
            self.ebit.clone().into_bound_py_any(py)?,
            self.market_cap.clone().into_bound_py_any(py)?,
            self.total_liabilities.clone().into_bound_py_any(py)?,
            self.revenue.clone().into_bound_py_any(py)?,
        ];
        PyTuple::new(py, members)
    }
}

impl From<libfmp::responses::bulk::BulkFinancialScore> for BulkFinancialScore {
    fn from(value: libfmp::responses::bulk::BulkFinancialScore) -> Self {
        Self {
            symbol: value.symbol.into_inner(),
            reported_currency: value.reported_currency.into_inner(),
            altman_z_score: value.altman_z_score.into_inner(),
            piotroski_score: value.piotroski_score.into_inner(),
            working_capital: value.working_capital.into_inner(),
            total_assets: value.total_assets.into_inner(),
            retained_earnings: value.retained_earnings.into_inner(),
            ebit: value.ebit.into_inner(),
            market_cap: value.market_cap.into_inner(),
            total_liabilities: value.total_liabilities.into_inner(),
            revenue: value.revenue.into_inner(),
        }
    }
}

#[gen_stub_pyclass]
#[pyclass(module = "fmp._native.bulk.snapshots", frozen, from_py_object)]
#[derive(Clone)]
pub(crate) struct BulkPriceTargetSummary {
    #[pyo3(get)]
    pub symbol: String,
    #[pyo3(get)]
    pub last_month_count: String,
    #[pyo3(get)]
    pub last_month_avg_price_target: String,
    #[pyo3(get)]
    pub last_quarter_count: String,
    #[pyo3(get)]
    pub last_quarter_avg_price_target: String,
    #[pyo3(get)]
    pub last_year_count: String,
    #[pyo3(get)]
    pub last_year_avg_price_target: String,
    #[pyo3(get)]
    pub all_time_count: String,
    #[pyo3(get)]
    pub all_time_avg_price_target: String,
    #[pyo3(get)]
    pub publishers: String,
}

#[gen_stub_pymethods]
#[pymethods]
impl BulkPriceTargetSummary {
    #[new]
    #[allow(clippy::too_many_arguments)]
    #[allow(clippy::fn_params_excessive_bools)]
    #[pyo3(signature = (symbol, last_month_count, last_month_avg_price_target, last_quarter_count, last_quarter_avg_price_target, last_year_count, last_year_avg_price_target, all_time_count, all_time_avg_price_target, publishers))]
    fn new(
        symbol: String,
        last_month_count: String,
        last_month_avg_price_target: String,
        last_quarter_count: String,
        last_quarter_avg_price_target: String,
        last_year_count: String,
        last_year_avg_price_target: String,
        all_time_count: String,
        all_time_avg_price_target: String,
        publishers: String,
    ) -> Self {
        Self {
            symbol,
            last_month_count,
            last_month_avg_price_target,
            last_quarter_count,
            last_quarter_avg_price_target,
            last_year_count,
            last_year_avg_price_target,
            all_time_count,
            all_time_avg_price_target,
            publishers,
        }
    }

    #[allow(clippy::clone_on_copy)]
    fn __getnewargs__<'py>(&self, py: Python<'py>) -> PyResult<Bound<'py, PyTuple>> {
        let members: Vec<Bound<'py, PyAny>> = vec![
            self.symbol.clone().into_bound_py_any(py)?,
            self.last_month_count.clone().into_bound_py_any(py)?,
            self.last_month_avg_price_target
                .clone()
                .into_bound_py_any(py)?,
            self.last_quarter_count.clone().into_bound_py_any(py)?,
            self.last_quarter_avg_price_target
                .clone()
                .into_bound_py_any(py)?,
            self.last_year_count.clone().into_bound_py_any(py)?,
            self.last_year_avg_price_target
                .clone()
                .into_bound_py_any(py)?,
            self.all_time_count.clone().into_bound_py_any(py)?,
            self.all_time_avg_price_target
                .clone()
                .into_bound_py_any(py)?,
            self.publishers.clone().into_bound_py_any(py)?,
        ];
        PyTuple::new(py, members)
    }
}

impl From<libfmp::responses::bulk::BulkPriceTargetSummary> for BulkPriceTargetSummary {
    fn from(value: libfmp::responses::bulk::BulkPriceTargetSummary) -> Self {
        Self {
            symbol: value.symbol.into_inner(),
            last_month_count: value.last_month_count.into_inner(),
            last_month_avg_price_target: value.last_month_avg_price_target.into_inner(),
            last_quarter_count: value.last_quarter_count.into_inner(),
            last_quarter_avg_price_target: value.last_quarter_avg_price_target.into_inner(),
            last_year_count: value.last_year_count.into_inner(),
            last_year_avg_price_target: value.last_year_avg_price_target.into_inner(),
            all_time_count: value.all_time_count.into_inner(),
            all_time_avg_price_target: value.all_time_avg_price_target.into_inner(),
            publishers: value.publishers,
        }
    }
}

#[gen_stub_pyclass]
#[pyclass(module = "fmp._native.bulk.snapshots", frozen, from_py_object)]
#[derive(Clone)]
pub(crate) struct BulkEtfHolding {
    #[pyo3(get)]
    pub symbol: String,
    #[pyo3(get)]
    pub name: String,
    #[pyo3(get)]
    pub shares_number: String,
    #[pyo3(get)]
    pub asset: String,
    #[pyo3(get)]
    pub weight_percentage: String,
    #[pyo3(get)]
    pub cusip: String,
    #[pyo3(get)]
    pub isin: String,
    #[pyo3(get)]
    pub market_value: String,
    #[pyo3(get)]
    pub last_updated_raw: String,
}

#[gen_stub_pymethods]
#[pymethods]
impl BulkEtfHolding {
    #[new]
    #[allow(clippy::too_many_arguments)]
    #[allow(clippy::fn_params_excessive_bools)]
    #[pyo3(signature = (symbol, name, shares_number, asset, weight_percentage, cusip, isin, market_value, last_updated_raw))]
    fn new(
        symbol: String,
        name: String,
        shares_number: String,
        asset: String,
        weight_percentage: String,
        cusip: String,
        isin: String,
        market_value: String,
        last_updated_raw: String,
    ) -> Self {
        Self {
            symbol,
            name,
            shares_number,
            asset,
            weight_percentage,
            cusip,
            isin,
            market_value,
            last_updated_raw,
        }
    }

    #[allow(clippy::clone_on_copy)]
    fn __getnewargs__<'py>(&self, py: Python<'py>) -> PyResult<Bound<'py, PyTuple>> {
        let members: Vec<Bound<'py, PyAny>> = vec![
            self.symbol.clone().into_bound_py_any(py)?,
            self.name.clone().into_bound_py_any(py)?,
            self.shares_number.clone().into_bound_py_any(py)?,
            self.asset.clone().into_bound_py_any(py)?,
            self.weight_percentage.clone().into_bound_py_any(py)?,
            self.cusip.clone().into_bound_py_any(py)?,
            self.isin.clone().into_bound_py_any(py)?,
            self.market_value.clone().into_bound_py_any(py)?,
            self.last_updated_raw.clone().into_bound_py_any(py)?,
        ];
        PyTuple::new(py, members)
    }
}

impl From<libfmp::responses::bulk::BulkEtfHolding> for BulkEtfHolding {
    fn from(value: libfmp::responses::bulk::BulkEtfHolding) -> Self {
        Self {
            symbol: value.symbol.into_inner(),
            name: value.name,
            shares_number: value.shares_number.into_inner(),
            asset: value.asset.into_inner(),
            weight_percentage: value.weight_percentage.into_inner(),
            cusip: value.cusip,
            isin: value.isin.into_inner(),
            market_value: value.market_value.into_inner(),
            last_updated_raw: value.last_updated_raw,
        }
    }
}

#[gen_stub_pyclass]
#[pyclass(module = "fmp._native.bulk.snapshots", frozen, from_py_object)]
#[derive(Clone)]
pub(crate) struct BulkUpgradesDowngradesConsensus {
    #[pyo3(get)]
    pub symbol: String,
    #[pyo3(get)]
    pub strong_buy: String,
    #[pyo3(get)]
    pub buy: String,
    #[pyo3(get)]
    pub hold: String,
    #[pyo3(get)]
    pub sell: String,
    #[pyo3(get)]
    pub strong_sell: String,
    #[pyo3(get)]
    pub consensus: String,
}

#[gen_stub_pymethods]
#[pymethods]
impl BulkUpgradesDowngradesConsensus {
    #[new]
    #[allow(clippy::too_many_arguments)]
    #[allow(clippy::fn_params_excessive_bools)]
    #[pyo3(signature = (symbol, strong_buy, buy, hold, sell, strong_sell, consensus))]
    fn new(
        symbol: String,
        strong_buy: String,
        buy: String,
        hold: String,
        sell: String,
        strong_sell: String,
        consensus: String,
    ) -> Self {
        Self {
            symbol,
            strong_buy,
            buy,
            hold,
            sell,
            strong_sell,
            consensus,
        }
    }

    #[allow(clippy::clone_on_copy)]
    fn __getnewargs__<'py>(&self, py: Python<'py>) -> PyResult<Bound<'py, PyTuple>> {
        let members: Vec<Bound<'py, PyAny>> = vec![
            self.symbol.clone().into_bound_py_any(py)?,
            self.strong_buy.clone().into_bound_py_any(py)?,
            self.buy.clone().into_bound_py_any(py)?,
            self.hold.clone().into_bound_py_any(py)?,
            self.sell.clone().into_bound_py_any(py)?,
            self.strong_sell.clone().into_bound_py_any(py)?,
            self.consensus.clone().into_bound_py_any(py)?,
        ];
        PyTuple::new(py, members)
    }
}

impl From<libfmp::responses::bulk::BulkUpgradesDowngradesConsensus>
    for BulkUpgradesDowngradesConsensus
{
    fn from(value: libfmp::responses::bulk::BulkUpgradesDowngradesConsensus) -> Self {
        Self {
            symbol: value.symbol,
            strong_buy: value.strong_buy.into_inner(),
            buy: value.buy.into_inner(),
            hold: value.hold.into_inner(),
            sell: value.sell.into_inner(),
            strong_sell: value.strong_sell.into_inner(),
            consensus: value.consensus,
        }
    }
}
