//! Bulk balance-sheet and balance-sheet-growth rows.

use serde::{Deserialize, Serialize};

use crate::{
    codecs::{FiscalYearString, NumericString},
    query::FiscalPeriod,
    types::{ApiDateTime, Cik, CurrencyCode, Date, Ticker},
};

/// One worldwide bulk balance-sheet-statement row.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct BulkBalanceSheetStatement {
    pub date: Date,
    pub symbol: Ticker,
    pub reported_currency: CurrencyCode,
    pub cik: Cik,
    pub filing_date: Date,
    pub accepted_date: ApiDateTime,
    pub fiscal_year: FiscalYearString,
    pub period: FiscalPeriod,
    pub cash_and_cash_equivalents: NumericString,
    pub short_term_investments: NumericString,
    pub cash_and_short_term_investments: NumericString,
    pub net_receivables: NumericString,
    pub accounts_receivables: NumericString,
    pub other_receivables: NumericString,
    pub inventory: NumericString,
    pub prepaids: NumericString,
    pub other_current_assets: NumericString,
    pub total_current_assets: NumericString,
    pub property_plant_equipment_net: NumericString,
    pub goodwill: NumericString,
    pub intangible_assets: NumericString,
    pub goodwill_and_intangible_assets: NumericString,
    pub long_term_investments: NumericString,
    pub tax_assets: NumericString,
    pub other_non_current_assets: NumericString,
    pub total_non_current_assets: NumericString,
    pub other_assets: NumericString,
    pub total_assets: NumericString,
    pub total_payables: NumericString,
    pub account_payables: NumericString,
    pub other_payables: NumericString,
    pub accrued_expenses: NumericString,
    pub short_term_debt: NumericString,
    pub capital_lease_obligations_current: NumericString,
    pub tax_payables: NumericString,
    pub deferred_revenue: NumericString,
    pub other_current_liabilities: NumericString,
    pub total_current_liabilities: NumericString,
    pub long_term_debt: NumericString,
    pub capital_lease_obligations_non_current: NumericString,
    pub deferred_revenue_non_current: NumericString,
    pub deferred_tax_liabilities_non_current: NumericString,
    pub other_non_current_liabilities: NumericString,
    pub total_non_current_liabilities: NumericString,
    pub other_liabilities: NumericString,
    pub capital_lease_obligations: NumericString,
    pub total_liabilities: NumericString,
    pub treasury_stock: NumericString,
    pub preferred_stock: NumericString,
    pub common_stock: NumericString,
    pub retained_earnings: NumericString,
    pub additional_paid_in_capital: NumericString,
    pub accumulated_other_comprehensive_income_loss: NumericString,
    pub other_total_stockholders_equity: NumericString,
    pub total_stockholders_equity: NumericString,
    pub total_equity: NumericString,
    pub minority_interest: NumericString,
    pub total_liabilities_and_total_equity: NumericString,
    pub total_investments: NumericString,
    pub total_debt: NumericString,
    pub net_debt: NumericString,
}

/// One worldwide bulk balance-sheet-statement-growth row.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct BulkBalanceSheetStatementGrowth {
    pub symbol: Ticker,
    pub date: Date,
    pub fiscal_year: FiscalYearString,
    pub period: FiscalPeriod,
    pub reported_currency: CurrencyCode,
    pub growth_cash_and_cash_equivalents: NumericString,
    pub growth_short_term_investments: NumericString,
    pub growth_cash_and_short_term_investments: NumericString,
    pub growth_net_receivables: NumericString,
    pub growth_inventory: NumericString,
    pub growth_other_current_assets: NumericString,
    pub growth_total_current_assets: NumericString,
    pub growth_property_plant_equipment_net: NumericString,
    pub growth_goodwill: NumericString,
    pub growth_intangible_assets: NumericString,
    pub growth_goodwill_and_intangible_assets: NumericString,
    pub growth_long_term_investments: NumericString,
    pub growth_tax_assets: NumericString,
    pub growth_other_non_current_assets: NumericString,
    pub growth_total_non_current_assets: NumericString,
    pub growth_other_assets: NumericString,
    pub growth_total_assets: NumericString,
    pub growth_account_payables: NumericString,
    pub growth_short_term_debt: NumericString,
    pub growth_tax_payables: NumericString,
    pub growth_deferred_revenue: NumericString,
    pub growth_other_current_liabilities: NumericString,
    pub growth_total_current_liabilities: NumericString,
    pub growth_long_term_debt: NumericString,
    pub growth_deferred_revenue_non_current: NumericString,
    pub growth_deferred_tax_liabilities_non_current: NumericString,
    pub growth_other_non_current_liabilities: NumericString,
    pub growth_total_non_current_liabilities: NumericString,
    pub growth_other_liabilities: NumericString,
    pub growth_total_liabilities: NumericString,
    pub growth_preferred_stock: NumericString,
    pub growth_common_stock: NumericString,
    pub growth_retained_earnings: NumericString,
    pub growth_accumulated_other_comprehensive_income_loss: NumericString,
    #[serde(rename = "growthOthertotalStockholdersEquity")]
    pub growth_other_total_stockholders_equity: NumericString,
    pub growth_total_stockholders_equity: NumericString,
    pub growth_minority_interest: NumericString,
    pub growth_total_equity: NumericString,
    pub growth_total_liabilities_and_stockholders_equity: NumericString,
    pub growth_total_investments: NumericString,
    pub growth_total_debt: NumericString,
    pub growth_net_debt: NumericString,
    pub growth_accounts_receivables: NumericString,
    pub growth_other_receivables: NumericString,
    pub growth_prepaids: NumericString,
    pub growth_total_payables: NumericString,
    pub growth_other_payables: NumericString,
    pub growth_accrued_expenses: NumericString,
    pub growth_capital_lease_obligations_current: NumericString,
    pub growth_additional_paid_in_capital: NumericString,
    pub growth_treasury_stock: NumericString,
}
