//! Bulk balance-sheet and balance-sheet-growth rows.

use serde::{Deserialize, Serialize};

use crate::{
    codecs::{FiscalYearString, NumericString},
    query::FiscalPeriod,
    types::{ApiDateTime, Cik, CurrencyCode, Date, Ticker},
};

/// One worldwide bulk balance-sheet-statement row.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[non_exhaustive]
#[serde(rename_all = "camelCase")]
pub struct BulkBalanceSheetStatement {
    pub date: Date,
    pub symbol: Ticker,
    pub reported_currency: CurrencyCode,
    pub cik: Cik,
    pub filing_date: Date,
    pub accepted_date: ApiDateTime,
    pub fiscal_year: FiscalYearString,
    pub period: FiscalPeriod,
    pub cash_and_cash_equivalents: Option<NumericString>,
    pub short_term_investments: Option<NumericString>,
    pub cash_and_short_term_investments: Option<NumericString>,
    pub net_receivables: Option<NumericString>,
    pub accounts_receivables: Option<NumericString>,
    pub other_receivables: Option<NumericString>,
    pub inventory: Option<NumericString>,
    pub prepaids: Option<NumericString>,
    pub other_current_assets: Option<NumericString>,
    pub total_current_assets: Option<NumericString>,
    pub property_plant_equipment_net: Option<NumericString>,
    pub goodwill: Option<NumericString>,
    pub intangible_assets: Option<NumericString>,
    pub goodwill_and_intangible_assets: Option<NumericString>,
    pub long_term_investments: Option<NumericString>,
    pub tax_assets: Option<NumericString>,
    pub other_non_current_assets: Option<NumericString>,
    pub total_non_current_assets: Option<NumericString>,
    pub other_assets: Option<NumericString>,
    pub total_assets: Option<NumericString>,
    pub total_payables: Option<NumericString>,
    pub account_payables: Option<NumericString>,
    pub other_payables: Option<NumericString>,
    pub accrued_expenses: Option<NumericString>,
    pub short_term_debt: Option<NumericString>,
    pub capital_lease_obligations_current: Option<NumericString>,
    pub tax_payables: Option<NumericString>,
    pub deferred_revenue: Option<NumericString>,
    pub other_current_liabilities: Option<NumericString>,
    pub total_current_liabilities: Option<NumericString>,
    pub long_term_debt: Option<NumericString>,
    pub capital_lease_obligations_non_current: Option<NumericString>,
    pub deferred_revenue_non_current: Option<NumericString>,
    pub deferred_tax_liabilities_non_current: Option<NumericString>,
    pub other_non_current_liabilities: Option<NumericString>,
    pub total_non_current_liabilities: Option<NumericString>,
    pub other_liabilities: Option<NumericString>,
    pub capital_lease_obligations: Option<NumericString>,
    pub total_liabilities: Option<NumericString>,
    pub treasury_stock: Option<NumericString>,
    pub preferred_stock: Option<NumericString>,
    pub common_stock: Option<NumericString>,
    pub retained_earnings: Option<NumericString>,
    pub additional_paid_in_capital: Option<NumericString>,
    pub accumulated_other_comprehensive_income_loss: Option<NumericString>,
    pub other_total_stockholders_equity: Option<NumericString>,
    pub total_stockholders_equity: Option<NumericString>,
    pub total_equity: Option<NumericString>,
    pub minority_interest: Option<NumericString>,
    pub total_liabilities_and_total_equity: Option<NumericString>,
    pub total_investments: Option<NumericString>,
    pub total_debt: Option<NumericString>,
    pub net_debt: Option<NumericString>,
}

/// One worldwide bulk balance-sheet-statement-growth row.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[non_exhaustive]
#[serde(rename_all = "camelCase")]
pub struct BulkBalanceSheetStatementGrowth {
    pub symbol: Ticker,
    pub date: Date,
    pub fiscal_year: FiscalYearString,
    pub period: FiscalPeriod,
    pub reported_currency: CurrencyCode,
    pub growth_cash_and_cash_equivalents: Option<NumericString>,
    pub growth_short_term_investments: Option<NumericString>,
    pub growth_cash_and_short_term_investments: Option<NumericString>,
    pub growth_net_receivables: Option<NumericString>,
    pub growth_inventory: Option<NumericString>,
    pub growth_other_current_assets: Option<NumericString>,
    pub growth_total_current_assets: Option<NumericString>,
    pub growth_property_plant_equipment_net: Option<NumericString>,
    pub growth_goodwill: Option<NumericString>,
    pub growth_intangible_assets: Option<NumericString>,
    pub growth_goodwill_and_intangible_assets: Option<NumericString>,
    pub growth_long_term_investments: Option<NumericString>,
    pub growth_tax_assets: Option<NumericString>,
    pub growth_other_non_current_assets: Option<NumericString>,
    pub growth_total_non_current_assets: Option<NumericString>,
    pub growth_other_assets: Option<NumericString>,
    pub growth_total_assets: Option<NumericString>,
    pub growth_account_payables: Option<NumericString>,
    pub growth_short_term_debt: Option<NumericString>,
    pub growth_tax_payables: Option<NumericString>,
    pub growth_deferred_revenue: Option<NumericString>,
    pub growth_other_current_liabilities: Option<NumericString>,
    pub growth_total_current_liabilities: Option<NumericString>,
    pub growth_long_term_debt: Option<NumericString>,
    pub growth_deferred_revenue_non_current: Option<NumericString>,
    pub growth_deferred_tax_liabilities_non_current: Option<NumericString>,
    pub growth_other_non_current_liabilities: Option<NumericString>,
    pub growth_total_non_current_liabilities: Option<NumericString>,
    pub growth_other_liabilities: Option<NumericString>,
    pub growth_total_liabilities: Option<NumericString>,
    pub growth_preferred_stock: Option<NumericString>,
    pub growth_common_stock: Option<NumericString>,
    pub growth_retained_earnings: Option<NumericString>,
    pub growth_accumulated_other_comprehensive_income_loss: Option<NumericString>,
    #[serde(rename = "growthOthertotalStockholdersEquity")]
    pub growth_other_total_stockholders_equity: Option<NumericString>,
    pub growth_total_stockholders_equity: Option<NumericString>,
    pub growth_minority_interest: Option<NumericString>,
    pub growth_total_equity: Option<NumericString>,
    pub growth_total_liabilities_and_stockholders_equity: Option<NumericString>,
    pub growth_total_investments: Option<NumericString>,
    pub growth_total_debt: Option<NumericString>,
    pub growth_net_debt: Option<NumericString>,
    pub growth_accounts_receivables: Option<NumericString>,
    pub growth_other_receivables: Option<NumericString>,
    pub growth_prepaids: Option<NumericString>,
    pub growth_total_payables: Option<NumericString>,
    pub growth_other_payables: Option<NumericString>,
    pub growth_accrued_expenses: Option<NumericString>,
    pub growth_capital_lease_obligations_current: Option<NumericString>,
    pub growth_additional_paid_in_capital: Option<NumericString>,
    pub growth_treasury_stock: Option<NumericString>,
}
