# This file is automatically generated by pyo3_stub_gen

import builtins
import datetime
import typing

__all__ = [
    "EnterpriseValue",
    "FinancialScore",
    "LatestFinancialStatement",
    "OwnerEarnings",
    "StatementsSummariesNamespace",
]


@typing.final
class EnterpriseValue:
    __hash__: typing.ClassVar[None]  # type: ignore[assignment]
    __match_args__: tuple[
        typing.Literal["symbol"],
        typing.Literal["date"],
        typing.Literal["stock_price"],
        typing.Literal["number_of_shares"],
        typing.Literal["market_capitalization"],
        typing.Literal["minus_cash_and_cash_equivalents"],
        typing.Literal["add_total_debt"],
        typing.Literal["enterprise_value"],
    ]

    @property
    def symbol(self) -> builtins.str: ...
    @property
    def date(self) -> datetime.date: ...
    @property
    def stock_price(self) -> builtins.float: ...
    @property
    def number_of_shares(self) -> builtins.float: ...
    @property
    def market_capitalization(self) -> builtins.float: ...
    @property
    def minus_cash_and_cash_equivalents(self) -> builtins.float: ...
    @property
    def add_total_debt(self) -> builtins.float: ...
    @property
    def enterprise_value(self) -> builtins.float: ...
    def __eq__(self, other: builtins.object, /) -> builtins.bool: ...
    def __new__(
        cls,
        *,
        symbol: builtins.str,
        date: datetime.date,
        stock_price: builtins.float,
        number_of_shares: builtins.float,
        market_capitalization: builtins.float,
        minus_cash_and_cash_equivalents: builtins.float,
        add_total_debt: builtins.float,
        enterprise_value: builtins.float,
    ) -> EnterpriseValue: ...
    def __getnewargs_ex__(self) -> tuple[tuple, dict]: ...
    def __repr__(self) -> builtins.str: ...
    def to_dict(self) -> builtins.dict[builtins.str, typing.Any]:
        r"""
        Returns the row as a `dict` keyed by attribute name; nested models become
        dicts and lists of models become lists of dicts.
        """


@typing.final
class FinancialScore:
    __hash__: typing.ClassVar[None]  # type: ignore[assignment]
    __match_args__: tuple[
        typing.Literal["symbol"],
        typing.Literal["reported_currency"],
        typing.Literal["altman_z_score"],
        typing.Literal["piotroski_score"],
        typing.Literal["working_capital"],
        typing.Literal["total_assets"],
        typing.Literal["retained_earnings"],
        typing.Literal["ebit"],
        typing.Literal["market_cap"],
        typing.Literal["total_liabilities"],
        typing.Literal["revenue"],
    ]

    @property
    def symbol(self) -> builtins.str: ...
    @property
    def reported_currency(self) -> builtins.str: ...
    @property
    def altman_z_score(self) -> builtins.float: ...
    @property
    def piotroski_score(self) -> builtins.int: ...
    @property
    def working_capital(self) -> builtins.float: ...
    @property
    def total_assets(self) -> builtins.float: ...
    @property
    def retained_earnings(self) -> builtins.float: ...
    @property
    def ebit(self) -> builtins.float: ...
    @property
    def market_cap(self) -> builtins.float: ...
    @property
    def total_liabilities(self) -> builtins.float: ...
    @property
    def revenue(self) -> builtins.float: ...
    def __eq__(self, other: builtins.object, /) -> builtins.bool: ...
    def __new__(
        cls,
        *,
        symbol: builtins.str,
        reported_currency: builtins.str,
        altman_z_score: builtins.float,
        piotroski_score: builtins.int,
        working_capital: builtins.float,
        total_assets: builtins.float,
        retained_earnings: builtins.float,
        ebit: builtins.float,
        market_cap: builtins.float,
        total_liabilities: builtins.float,
        revenue: builtins.float,
    ) -> FinancialScore: ...
    def __getnewargs_ex__(self) -> tuple[tuple, dict]: ...
    def __repr__(self) -> builtins.str: ...
    def to_dict(self) -> builtins.dict[builtins.str, typing.Any]:
        r"""
        Returns the row as a `dict` keyed by attribute name; nested models become
        dicts and lists of models become lists of dicts.
        """


@typing.final
class LatestFinancialStatement:
    __hash__: typing.ClassVar[None]  # type: ignore[assignment]
    __match_args__: tuple[
        typing.Literal["symbol"],
        typing.Literal["calendar_year"],
        typing.Literal["period"],
        typing.Literal["date"],
        typing.Literal["date_added"],
    ]

    @property
    def symbol(self) -> builtins.str: ...
    @property
    def calendar_year(self) -> builtins.int: ...
    @property
    def period(self) -> builtins.str: ...
    @property
    def date(self) -> datetime.date: ...
    @property
    def date_added(self) -> datetime.datetime: ...
    def __eq__(self, other: builtins.object, /) -> builtins.bool: ...
    def __new__(
        cls,
        *,
        symbol: builtins.str,
        calendar_year: builtins.int,
        period: builtins.str,
        date: datetime.date,
        date_added: datetime.datetime,
    ) -> LatestFinancialStatement: ...
    def __getnewargs_ex__(self) -> tuple[tuple, dict]: ...
    def __repr__(self) -> builtins.str: ...
    def to_dict(self) -> builtins.dict[builtins.str, typing.Any]:
        r"""
        Returns the row as a `dict` keyed by attribute name; nested models become
        dicts and lists of models become lists of dicts.
        """


@typing.final
class OwnerEarnings:
    __hash__: typing.ClassVar[None]  # type: ignore[assignment]
    __match_args__: tuple[
        typing.Literal["symbol"],
        typing.Literal["reported_currency"],
        typing.Literal["fiscal_year"],
        typing.Literal["period"],
        typing.Literal["date"],
        typing.Literal["average_ppe"],
        typing.Literal["maintenance_capex"],
        typing.Literal["owners_earnings"],
        typing.Literal["growth_capex"],
        typing.Literal["owners_earnings_per_share"],
    ]

    @property
    def symbol(self) -> builtins.str: ...
    @property
    def reported_currency(self) -> builtins.str: ...
    @property
    def fiscal_year(self) -> builtins.str: ...
    @property
    def period(self) -> builtins.str: ...
    @property
    def date(self) -> datetime.date: ...
    @property
    def average_ppe(self) -> builtins.float: ...
    @property
    def maintenance_capex(self) -> builtins.float: ...
    @property
    def owners_earnings(self) -> builtins.float: ...
    @property
    def growth_capex(self) -> builtins.float: ...
    @property
    def owners_earnings_per_share(self) -> builtins.float: ...
    def __eq__(self, other: builtins.object, /) -> builtins.bool: ...
    def __new__(
        cls,
        *,
        symbol: builtins.str,
        reported_currency: builtins.str,
        fiscal_year: builtins.str,
        period: builtins.str,
        date: datetime.date,
        average_ppe: builtins.float,
        maintenance_capex: builtins.float,
        owners_earnings: builtins.float,
        growth_capex: builtins.float,
        owners_earnings_per_share: builtins.float,
    ) -> OwnerEarnings: ...
    def __getnewargs_ex__(self) -> tuple[tuple, dict]: ...
    def __repr__(self) -> builtins.str: ...
    def to_dict(self) -> builtins.dict[builtins.str, typing.Any]:
        r"""
        Returns the row as a `dict` keyed by attribute name; nested models become
        dicts and lists of models become lists of dicts.
        """


@typing.final
class StatementsSummariesNamespace:
    r"""
    Statements summaries endpoints for a single client, exposed as `client.statements.summaries`.
    """

    def latest_financial_statements(
        self,
        *,
        page: typing.Optional[builtins.int] = None,
        limit: typing.Optional[builtins.int] = None,
    ) -> builtins.list[LatestFinancialStatement]:
        r"""
        Retrieves the latest worldwide financial-statement filings.
        """

    def financial_scores(self, symbol: builtins.str) -> builtins.list[FinancialScore]:
        r"""
        Retrieves worldwide financial-health scores for one company.
        """

    def owner_earnings(
        self, symbol: builtins.str, *, limit: typing.Optional[builtins.int] = None
    ) -> builtins.list[OwnerEarnings]:
        r"""
        Retrieves worldwide owner earnings for one company.
        """

    def enterprise_values(
        self,
        symbol: builtins.str,
        *,
        limit: typing.Optional[builtins.int] = None,
        period: typing.Optional[builtins.str] = None,
    ) -> builtins.list[EnterpriseValue]:
        r"""
        Retrieves worldwide enterprise values for one company.
        """
