"""Source marker for the compiled ``fmp._native`` extension.

The extension module takes precedence at runtime. This file lets static type
checkers pair the compiled module with ``_native.pyi``.

Auto-generated by scripts/gen_submodule_shims.py from ``_native.pyi``; do not edit by hand.
"""
