"""Runtime source shim for the native ``fmp.client`` submodule.

The real ``fmp.client`` is a compiled submodule registered into
``sys.modules`` by the extension (see crates/fmp-py/src/lib.rs); it wins
at import time, so nothing here runs. This file exists only so static type
checkers resolve ``from fmp.client import ...`` from ``client.pyi`` without
a ``reportMissingModuleSource`` warning.

Auto-generated by scripts/gen_submodule_shims.py from ``client.pyi``; do not edit or delete by hand.
"""
