# This file is automatically generated by pyo3_stub_gen

import builtins
import datetime
import typing

__all__ = [
    "AnalystNamespace",
    "FinancialEstimate",
    "HistoricalRating",
    "HistoricalStockGrade",
    "PriceTargetConsensus",
    "PriceTargetSummary",
    "RatingSnapshot",
    "StockGrade",
    "StockGradesSummary",
]


@typing.final
class AnalystNamespace:
    r"""
    Analyst endpoints for a single client, exposed as `client.analyst`.
    """

    def financial_estimates(
        self,
        symbol: builtins.str,
        period: builtins.str,
        *,
        page: typing.Optional[builtins.int] = None,
        limit: typing.Optional[builtins.int] = None,
    ) -> builtins.list[FinancialEstimate]:
        r"""
        Retrieves worldwide analyst financial estimates for one ticker.
        """

    def ratings_snapshot(self, symbol: builtins.str) -> builtins.list[RatingSnapshot]:
        r"""
        Retrieves the worldwide financial-rating snapshot for one ticker.
        """

    def historical_ratings(
        self, symbol: builtins.str, *, limit: typing.Optional[builtins.int] = None
    ) -> builtins.list[HistoricalRating]:
        r"""
        Retrieves worldwide historical financial ratings for one ticker.
        """

    def price_target_summary(
        self, symbol: builtins.str
    ) -> builtins.list[PriceTargetSummary]:
        r"""
        Retrieves the US-only price-target summary for one ticker.
        """

    def price_target_consensus(
        self, symbol: builtins.str
    ) -> builtins.list[PriceTargetConsensus]:
        r"""
        Retrieves the US-only price-target consensus for one ticker.
        """

    def stock_grades(self, symbol: builtins.str) -> builtins.list[StockGrade]:
        r"""
        Retrieves current worldwide stock-grade actions for one ticker.
        """

    def historical_stock_grades(
        self, symbol: builtins.str, *, limit: typing.Optional[builtins.int] = None
    ) -> builtins.list[HistoricalStockGrade]:
        r"""
        Retrieves worldwide historical stock-grade counts for one ticker.
        """

    def stock_grades_summary(
        self, symbol: builtins.str
    ) -> builtins.list[StockGradesSummary]:
        r"""
        Retrieves the worldwide stock-grades summary for one ticker.
        """


@typing.final
class FinancialEstimate:
    __hash__: typing.ClassVar[None]  # type: ignore[assignment]
    __match_args__: tuple[
        typing.Literal["symbol"],
        typing.Literal["date"],
        typing.Literal["revenue_low"],
        typing.Literal["revenue_high"],
        typing.Literal["revenue_avg"],
        typing.Literal["ebitda_low"],
        typing.Literal["ebitda_high"],
        typing.Literal["ebitda_avg"],
        typing.Literal["ebit_low"],
        typing.Literal["ebit_high"],
        typing.Literal["ebit_avg"],
        typing.Literal["net_income_low"],
        typing.Literal["net_income_high"],
        typing.Literal["net_income_avg"],
        typing.Literal["sga_expense_low"],
        typing.Literal["sga_expense_high"],
        typing.Literal["sga_expense_avg"],
        typing.Literal["eps_avg"],
        typing.Literal["eps_high"],
        typing.Literal["eps_low"],
        typing.Literal["num_analysts_revenue"],
        typing.Literal["num_analysts_eps"],
    ]

    @property
    def symbol(self) -> builtins.str: ...
    @property
    def date(self) -> datetime.date: ...
    @property
    def revenue_low(self) -> builtins.float: ...
    @property
    def revenue_high(self) -> builtins.float: ...
    @property
    def revenue_avg(self) -> builtins.float: ...
    @property
    def ebitda_low(self) -> builtins.float: ...
    @property
    def ebitda_high(self) -> builtins.float: ...
    @property
    def ebitda_avg(self) -> builtins.float: ...
    @property
    def ebit_low(self) -> builtins.float: ...
    @property
    def ebit_high(self) -> builtins.float: ...
    @property
    def ebit_avg(self) -> builtins.float: ...
    @property
    def net_income_low(self) -> builtins.float: ...
    @property
    def net_income_high(self) -> builtins.float: ...
    @property
    def net_income_avg(self) -> builtins.float: ...
    @property
    def sga_expense_low(self) -> builtins.float: ...
    @property
    def sga_expense_high(self) -> builtins.float: ...
    @property
    def sga_expense_avg(self) -> builtins.float: ...
    @property
    def eps_avg(self) -> builtins.float: ...
    @property
    def eps_high(self) -> builtins.float: ...
    @property
    def eps_low(self) -> builtins.float: ...
    @property
    def num_analysts_revenue(self) -> builtins.int: ...
    @property
    def num_analysts_eps(self) -> builtins.int: ...
    def __eq__(self, other: builtins.object, /) -> builtins.bool: ...
    def __new__(
        cls,
        *,
        symbol: builtins.str,
        date: datetime.date,
        revenue_low: builtins.float,
        revenue_high: builtins.float,
        revenue_avg: builtins.float,
        ebitda_low: builtins.float,
        ebitda_high: builtins.float,
        ebitda_avg: builtins.float,
        ebit_low: builtins.float,
        ebit_high: builtins.float,
        ebit_avg: builtins.float,
        net_income_low: builtins.float,
        net_income_high: builtins.float,
        net_income_avg: builtins.float,
        sga_expense_low: builtins.float,
        sga_expense_high: builtins.float,
        sga_expense_avg: builtins.float,
        eps_avg: builtins.float,
        eps_high: builtins.float,
        eps_low: builtins.float,
        num_analysts_revenue: builtins.int,
        num_analysts_eps: builtins.int,
    ) -> FinancialEstimate: ...
    def __getnewargs_ex__(self) -> tuple[tuple, dict]: ...
    def __repr__(self) -> builtins.str: ...
    def to_dict(self) -> builtins.dict[builtins.str, typing.Any]:
        r"""
        Returns the row as a `dict` keyed by attribute name; nested models become
        dicts and lists of models become lists of dicts.
        """


@typing.final
class HistoricalRating:
    __hash__: typing.ClassVar[None]  # type: ignore[assignment]
    __match_args__: tuple[
        typing.Literal["symbol"],
        typing.Literal["date"],
        typing.Literal["rating"],
        typing.Literal["overall_score"],
        typing.Literal["discounted_cash_flow_score"],
        typing.Literal["return_on_equity_score"],
        typing.Literal["return_on_assets_score"],
        typing.Literal["debt_to_equity_score"],
        typing.Literal["price_to_earnings_score"],
        typing.Literal["price_to_book_score"],
    ]

    @property
    def symbol(self) -> builtins.str: ...
    @property
    def date(self) -> datetime.date: ...
    @property
    def rating(self) -> builtins.str: ...
    @property
    def overall_score(self) -> builtins.int: ...
    @property
    def discounted_cash_flow_score(self) -> builtins.int: ...
    @property
    def return_on_equity_score(self) -> builtins.int: ...
    @property
    def return_on_assets_score(self) -> builtins.int: ...
    @property
    def debt_to_equity_score(self) -> builtins.int: ...
    @property
    def price_to_earnings_score(self) -> builtins.int: ...
    @property
    def price_to_book_score(self) -> builtins.int: ...
    def __eq__(self, other: builtins.object, /) -> builtins.bool: ...
    def __new__(
        cls,
        *,
        symbol: builtins.str,
        date: datetime.date,
        rating: builtins.str,
        overall_score: builtins.int,
        discounted_cash_flow_score: builtins.int,
        return_on_equity_score: builtins.int,
        return_on_assets_score: builtins.int,
        debt_to_equity_score: builtins.int,
        price_to_earnings_score: builtins.int,
        price_to_book_score: builtins.int,
    ) -> HistoricalRating: ...
    def __getnewargs_ex__(self) -> tuple[tuple, dict]: ...
    def __repr__(self) -> builtins.str: ...
    def to_dict(self) -> builtins.dict[builtins.str, typing.Any]:
        r"""
        Returns the row as a `dict` keyed by attribute name; nested models become
        dicts and lists of models become lists of dicts.
        """


@typing.final
class HistoricalStockGrade:
    __hash__: typing.ClassVar[None]  # type: ignore[assignment]
    __match_args__: tuple[
        typing.Literal["symbol"],
        typing.Literal["date"],
        typing.Literal["analyst_ratings_strong_buy"],
        typing.Literal["analyst_ratings_buy"],
        typing.Literal["analyst_ratings_hold"],
        typing.Literal["analyst_ratings_sell"],
        typing.Literal["analyst_ratings_strong_sell"],
    ]

    @property
    def symbol(self) -> builtins.str: ...
    @property
    def date(self) -> datetime.date: ...
    @property
    def analyst_ratings_strong_buy(self) -> builtins.int: ...
    @property
    def analyst_ratings_buy(self) -> builtins.int: ...
    @property
    def analyst_ratings_hold(self) -> builtins.int: ...
    @property
    def analyst_ratings_sell(self) -> builtins.int: ...
    @property
    def analyst_ratings_strong_sell(self) -> builtins.int: ...
    def __eq__(self, other: builtins.object, /) -> builtins.bool: ...
    def __new__(
        cls,
        *,
        symbol: builtins.str,
        date: datetime.date,
        analyst_ratings_strong_buy: builtins.int,
        analyst_ratings_buy: builtins.int,
        analyst_ratings_hold: builtins.int,
        analyst_ratings_sell: builtins.int,
        analyst_ratings_strong_sell: builtins.int,
    ) -> HistoricalStockGrade: ...
    def __getnewargs_ex__(self) -> tuple[tuple, dict]: ...
    def __repr__(self) -> builtins.str: ...
    def to_dict(self) -> builtins.dict[builtins.str, typing.Any]:
        r"""
        Returns the row as a `dict` keyed by attribute name; nested models become
        dicts and lists of models become lists of dicts.
        """


@typing.final
class PriceTargetConsensus:
    __hash__: typing.ClassVar[None]  # type: ignore[assignment]
    __match_args__: tuple[
        typing.Literal["symbol"],
        typing.Literal["target_high"],
        typing.Literal["target_low"],
        typing.Literal["target_consensus"],
        typing.Literal["target_median"],
    ]

    @property
    def symbol(self) -> builtins.str: ...
    @property
    def target_high(self) -> builtins.float: ...
    @property
    def target_low(self) -> builtins.float: ...
    @property
    def target_consensus(self) -> builtins.float: ...
    @property
    def target_median(self) -> builtins.float: ...
    def __eq__(self, other: builtins.object, /) -> builtins.bool: ...
    def __new__(
        cls,
        *,
        symbol: builtins.str,
        target_high: builtins.float,
        target_low: builtins.float,
        target_consensus: builtins.float,
        target_median: builtins.float,
    ) -> PriceTargetConsensus: ...
    def __getnewargs_ex__(self) -> tuple[tuple, dict]: ...
    def __repr__(self) -> builtins.str: ...
    def to_dict(self) -> builtins.dict[builtins.str, typing.Any]:
        r"""
        Returns the row as a `dict` keyed by attribute name; nested models become
        dicts and lists of models become lists of dicts.
        """


@typing.final
class PriceTargetSummary:
    __hash__: typing.ClassVar[None]  # type: ignore[assignment]
    __match_args__: tuple[
        typing.Literal["symbol"],
        typing.Literal["last_month_count"],
        typing.Literal["last_month_avg_price_target"],
        typing.Literal["last_quarter_count"],
        typing.Literal["last_quarter_avg_price_target"],
        typing.Literal["last_year_count"],
        typing.Literal["last_year_avg_price_target"],
        typing.Literal["all_time_count"],
        typing.Literal["all_time_avg_price_target"],
        typing.Literal["publishers"],
    ]

    @property
    def symbol(self) -> builtins.str: ...
    @property
    def last_month_count(self) -> builtins.int: ...
    @property
    def last_month_avg_price_target(self) -> builtins.float: ...
    @property
    def last_quarter_count(self) -> builtins.int: ...
    @property
    def last_quarter_avg_price_target(self) -> builtins.float: ...
    @property
    def last_year_count(self) -> builtins.int: ...
    @property
    def last_year_avg_price_target(self) -> builtins.float: ...
    @property
    def all_time_count(self) -> builtins.int: ...
    @property
    def all_time_avg_price_target(self) -> builtins.float: ...
    @property
    def publishers(self) -> builtins.str: ...
    def __eq__(self, other: builtins.object, /) -> builtins.bool: ...
    def __new__(
        cls,
        *,
        symbol: builtins.str,
        last_month_count: builtins.int,
        last_month_avg_price_target: builtins.float,
        last_quarter_count: builtins.int,
        last_quarter_avg_price_target: builtins.float,
        last_year_count: builtins.int,
        last_year_avg_price_target: builtins.float,
        all_time_count: builtins.int,
        all_time_avg_price_target: builtins.float,
        publishers: builtins.str,
    ) -> PriceTargetSummary: ...
    def __getnewargs_ex__(self) -> tuple[tuple, dict]: ...
    def __repr__(self) -> builtins.str: ...
    def to_dict(self) -> builtins.dict[builtins.str, typing.Any]:
        r"""
        Returns the row as a `dict` keyed by attribute name; nested models become
        dicts and lists of models become lists of dicts.
        """


@typing.final
class RatingSnapshot:
    __hash__: typing.ClassVar[None]  # type: ignore[assignment]
    __match_args__: tuple[
        typing.Literal["symbol"],
        typing.Literal["rating"],
        typing.Literal["overall_score"],
        typing.Literal["discounted_cash_flow_score"],
        typing.Literal["return_on_equity_score"],
        typing.Literal["return_on_assets_score"],
        typing.Literal["debt_to_equity_score"],
        typing.Literal["price_to_earnings_score"],
        typing.Literal["price_to_book_score"],
    ]

    @property
    def symbol(self) -> builtins.str: ...
    @property
    def rating(self) -> builtins.str: ...
    @property
    def overall_score(self) -> builtins.int: ...
    @property
    def discounted_cash_flow_score(self) -> builtins.int: ...
    @property
    def return_on_equity_score(self) -> builtins.int: ...
    @property
    def return_on_assets_score(self) -> builtins.int: ...
    @property
    def debt_to_equity_score(self) -> builtins.int: ...
    @property
    def price_to_earnings_score(self) -> builtins.int: ...
    @property
    def price_to_book_score(self) -> builtins.int: ...
    def __eq__(self, other: builtins.object, /) -> builtins.bool: ...
    def __new__(
        cls,
        *,
        symbol: builtins.str,
        rating: builtins.str,
        overall_score: builtins.int,
        discounted_cash_flow_score: builtins.int,
        return_on_equity_score: builtins.int,
        return_on_assets_score: builtins.int,
        debt_to_equity_score: builtins.int,
        price_to_earnings_score: builtins.int,
        price_to_book_score: builtins.int,
    ) -> RatingSnapshot: ...
    def __getnewargs_ex__(self) -> tuple[tuple, dict]: ...
    def __repr__(self) -> builtins.str: ...
    def to_dict(self) -> builtins.dict[builtins.str, typing.Any]:
        r"""
        Returns the row as a `dict` keyed by attribute name; nested models become
        dicts and lists of models become lists of dicts.
        """


@typing.final
class StockGrade:
    __hash__: typing.ClassVar[None]  # type: ignore[assignment]
    __match_args__: tuple[
        typing.Literal["symbol"],
        typing.Literal["date"],
        typing.Literal["grading_company"],
        typing.Literal["previous_grade"],
        typing.Literal["new_grade"],
        typing.Literal["action"],
    ]

    @property
    def symbol(self) -> builtins.str: ...
    @property
    def date(self) -> datetime.date: ...
    @property
    def grading_company(self) -> builtins.str: ...
    @property
    def previous_grade(self) -> builtins.str: ...
    @property
    def new_grade(self) -> builtins.str: ...
    @property
    def action(self) -> builtins.str: ...
    def __eq__(self, other: builtins.object, /) -> builtins.bool: ...
    def __new__(
        cls,
        *,
        symbol: builtins.str,
        date: datetime.date,
        grading_company: builtins.str,
        previous_grade: builtins.str,
        new_grade: builtins.str,
        action: builtins.str,
    ) -> StockGrade: ...
    def __getnewargs_ex__(self) -> tuple[tuple, dict]: ...
    def __repr__(self) -> builtins.str: ...
    def to_dict(self) -> builtins.dict[builtins.str, typing.Any]:
        r"""
        Returns the row as a `dict` keyed by attribute name; nested models become
        dicts and lists of models become lists of dicts.
        """


@typing.final
class StockGradesSummary:
    __hash__: typing.ClassVar[None]  # type: ignore[assignment]
    __match_args__: tuple[
        typing.Literal["symbol"],
        typing.Literal["strong_buy"],
        typing.Literal["buy"],
        typing.Literal["hold"],
        typing.Literal["sell"],
        typing.Literal["strong_sell"],
        typing.Literal["consensus"],
    ]

    @property
    def symbol(self) -> builtins.str: ...
    @property
    def strong_buy(self) -> builtins.int: ...
    @property
    def buy(self) -> builtins.int: ...
    @property
    def hold(self) -> builtins.int: ...
    @property
    def sell(self) -> builtins.int: ...
    @property
    def strong_sell(self) -> builtins.int: ...
    @property
    def consensus(self) -> builtins.str: ...
    def __eq__(self, other: builtins.object, /) -> builtins.bool: ...
    def __new__(
        cls,
        *,
        symbol: builtins.str,
        strong_buy: builtins.int,
        buy: builtins.int,
        hold: builtins.int,
        sell: builtins.int,
        strong_sell: builtins.int,
        consensus: builtins.str,
    ) -> StockGradesSummary: ...
    def __getnewargs_ex__(self) -> tuple[tuple, dict]: ...
    def __repr__(self) -> builtins.str: ...
    def to_dict(self) -> builtins.dict[builtins.str, typing.Any]:
        r"""
        Returns the row as a `dict` keyed by attribute name; nested models become
        dicts and lists of models become lists of dicts.
        """
