// @generated by gen_models; do not edit by hand.

use pyo3::IntoPyObjectExt;
use pyo3::prelude::*;
use pyo3::types::{PyDict, PyTuple};
use pyo3_stub_gen::derive::{gen_stub_pyclass, gen_stub_pymethods};

#[gen_stub_pyclass]
#[pyclass(module = "fmp._native.calendar", frozen, eq, from_py_object)]
#[derive(Clone, PartialEq)]
pub(crate) struct DividendEvent {
    #[pyo3(get)]
    pub symbol: String,
    #[pyo3(get)]
    pub date: ::chrono::NaiveDate,
    #[pyo3(get)]
    pub record_date: ::chrono::NaiveDate,
    #[pyo3(get)]
    pub payment_date: ::chrono::NaiveDate,
    #[pyo3(get)]
    pub declaration_date: Option<::chrono::NaiveDate>,
    #[pyo3(get)]
    pub adj_dividend: f64,
    #[pyo3(get)]
    pub dividend: f64,
    #[pyo3(get)]
    pub yield_: f64,
    #[pyo3(get)]
    pub frequency: String,
}

#[gen_stub_pymethods]
#[pymethods]
impl DividendEvent {
    #[new]
    #[allow(clippy::too_many_arguments)]
    #[allow(clippy::fn_params_excessive_bools)]
    #[pyo3(signature = (*, symbol, date, record_date, payment_date, declaration_date, adj_dividend, dividend, yield_, frequency))]
    fn new(
        symbol: String,
        date: ::chrono::NaiveDate,
        record_date: ::chrono::NaiveDate,
        payment_date: ::chrono::NaiveDate,
        declaration_date: Option<::chrono::NaiveDate>,
        adj_dividend: f64,
        dividend: f64,
        yield_: f64,
        frequency: String,
    ) -> Self {
        Self {
            symbol,
            date,
            record_date,
            payment_date,
            declaration_date,
            adj_dividend,
            dividend,
            yield_,
            frequency,
        }
    }

    #[classattr]
    const __hash__: Option<Py<PyAny>> = None;

    #[allow(clippy::clone_on_copy)]
    fn __getnewargs_ex__<'py>(
        &self,
        py: Python<'py>,
    ) -> PyResult<(Bound<'py, PyTuple>, Bound<'py, PyDict>)> {
        let kwargs = PyDict::new(py);
        kwargs.set_item("symbol", self.symbol.clone().into_bound_py_any(py)?)?;
        kwargs.set_item("date", self.date.clone().into_bound_py_any(py)?)?;
        kwargs.set_item(
            "record_date",
            self.record_date.clone().into_bound_py_any(py)?,
        )?;
        kwargs.set_item(
            "payment_date",
            self.payment_date.clone().into_bound_py_any(py)?,
        )?;
        kwargs.set_item(
            "declaration_date",
            self.declaration_date.clone().into_bound_py_any(py)?,
        )?;
        kwargs.set_item(
            "adj_dividend",
            self.adj_dividend.clone().into_bound_py_any(py)?,
        )?;
        kwargs.set_item("dividend", self.dividend.clone().into_bound_py_any(py)?)?;
        kwargs.set_item("yield_", self.yield_.clone().into_bound_py_any(py)?)?;
        kwargs.set_item("frequency", self.frequency.clone().into_bound_py_any(py)?)?;
        Ok((PyTuple::empty(py), kwargs))
    }
}

impl From<libfmp::responses::calendar::DividendEvent> for DividendEvent {
    fn from(value: libfmp::responses::calendar::DividendEvent) -> Self {
        Self {
            symbol: value.symbol.into_inner(),
            date: value.date.into_inner(),
            record_date: value.record_date.into_inner(),
            payment_date: value.payment_date.into_inner(),
            declaration_date: value.declaration_date.map(|value| value.into_inner()),
            adj_dividend: value.adj_dividend,
            dividend: value.dividend,
            yield_: value.r#yield,
            frequency: value.frequency,
        }
    }
}

#[gen_stub_pyclass]
#[pyclass(module = "fmp._native.calendar", frozen, eq, from_py_object)]
#[derive(Clone, PartialEq)]
pub(crate) struct EarningsEvent {
    #[pyo3(get)]
    pub symbol: String,
    #[pyo3(get)]
    pub date: ::chrono::NaiveDate,
    #[pyo3(get)]
    pub eps_actual: Option<f64>,
    #[pyo3(get)]
    pub eps_estimated: f64,
    #[pyo3(get)]
    pub revenue_actual: Option<f64>,
    #[pyo3(get)]
    pub revenue_estimated: f64,
    #[pyo3(get)]
    pub last_updated: ::chrono::NaiveDate,
}

#[gen_stub_pymethods]
#[pymethods]
impl EarningsEvent {
    #[new]
    #[allow(clippy::too_many_arguments)]
    #[allow(clippy::fn_params_excessive_bools)]
    #[pyo3(signature = (*, symbol, date, eps_actual, eps_estimated, revenue_actual, revenue_estimated, last_updated))]
    fn new(
        symbol: String,
        date: ::chrono::NaiveDate,
        eps_actual: Option<f64>,
        eps_estimated: f64,
        revenue_actual: Option<f64>,
        revenue_estimated: f64,
        last_updated: ::chrono::NaiveDate,
    ) -> Self {
        Self {
            symbol,
            date,
            eps_actual,
            eps_estimated,
            revenue_actual,
            revenue_estimated,
            last_updated,
        }
    }

    #[classattr]
    const __hash__: Option<Py<PyAny>> = None;

    #[allow(clippy::clone_on_copy)]
    fn __getnewargs_ex__<'py>(
        &self,
        py: Python<'py>,
    ) -> PyResult<(Bound<'py, PyTuple>, Bound<'py, PyDict>)> {
        let kwargs = PyDict::new(py);
        kwargs.set_item("symbol", self.symbol.clone().into_bound_py_any(py)?)?;
        kwargs.set_item("date", self.date.clone().into_bound_py_any(py)?)?;
        kwargs.set_item("eps_actual", self.eps_actual.clone().into_bound_py_any(py)?)?;
        kwargs.set_item(
            "eps_estimated",
            self.eps_estimated.clone().into_bound_py_any(py)?,
        )?;
        kwargs.set_item(
            "revenue_actual",
            self.revenue_actual.clone().into_bound_py_any(py)?,
        )?;
        kwargs.set_item(
            "revenue_estimated",
            self.revenue_estimated.clone().into_bound_py_any(py)?,
        )?;
        kwargs.set_item(
            "last_updated",
            self.last_updated.clone().into_bound_py_any(py)?,
        )?;
        Ok((PyTuple::empty(py), kwargs))
    }
}

impl From<libfmp::responses::calendar::EarningsEvent> for EarningsEvent {
    fn from(value: libfmp::responses::calendar::EarningsEvent) -> Self {
        Self {
            symbol: value.symbol.into_inner(),
            date: value.date.into_inner(),
            eps_actual: value.eps_actual,
            eps_estimated: value.eps_estimated,
            revenue_actual: value.revenue_actual,
            revenue_estimated: value.revenue_estimated,
            last_updated: value.last_updated.into_inner(),
        }
    }
}

#[gen_stub_pyclass]
#[pyclass(module = "fmp._native.calendar", frozen, eq, from_py_object)]
#[derive(Clone, PartialEq)]
pub(crate) struct IpoCalendarEvent {
    #[pyo3(get)]
    pub symbol: String,
    #[pyo3(get)]
    pub date: ::chrono::NaiveDate,
    #[pyo3(get)]
    pub daa: String,
    #[pyo3(get)]
    pub company: String,
    #[pyo3(get)]
    pub exchange: String,
    #[pyo3(get)]
    pub actions: String,
    shares: Option<::serde_json::Value>,
    price_range: Option<::serde_json::Value>,
    market_cap: Option<::serde_json::Value>,
}

#[gen_stub_pymethods]
#[pymethods]
impl IpoCalendarEvent {
    #[new]
    #[allow(clippy::too_many_arguments)]
    #[allow(clippy::fn_params_excessive_bools)]
    #[pyo3(signature = (*, symbol, date, daa, company, exchange, actions, shares, price_range, market_cap))]
    fn new(
        symbol: String,
        date: ::chrono::NaiveDate,
        daa: String,
        company: String,
        exchange: String,
        actions: String,
        shares: Option<String>,
        price_range: Option<String>,
        market_cap: Option<String>,
    ) -> PyResult<Self> {
        let shares = match shares {
            Some(text) => Some(
                ::serde_json::from_str::<::serde_json::Value>(&text).map_err(|error| {
                    ::pyo3::exceptions::PyValueError::new_err(format!(
                        "invalid JSON for field `shares`: {error}"
                    ))
                })?,
            ),
            None => None,
        };
        let price_range = match price_range {
            Some(text) => Some(
                ::serde_json::from_str::<::serde_json::Value>(&text).map_err(|error| {
                    ::pyo3::exceptions::PyValueError::new_err(format!(
                        "invalid JSON for field `price_range`: {error}"
                    ))
                })?,
            ),
            None => None,
        };
        let market_cap = match market_cap {
            Some(text) => Some(
                ::serde_json::from_str::<::serde_json::Value>(&text).map_err(|error| {
                    ::pyo3::exceptions::PyValueError::new_err(format!(
                        "invalid JSON for field `market_cap`: {error}"
                    ))
                })?,
            ),
            None => None,
        };
        Ok(Self {
            symbol,
            date,
            daa,
            company,
            exchange,
            actions,
            shares,
            price_range,
            market_cap,
        })
    }

    #[classattr]
    const __hash__: Option<Py<PyAny>> = None;

    #[allow(clippy::clone_on_copy)]
    fn __getnewargs_ex__<'py>(
        &self,
        py: Python<'py>,
    ) -> PyResult<(Bound<'py, PyTuple>, Bound<'py, PyDict>)> {
        let kwargs = PyDict::new(py);
        kwargs.set_item("symbol", self.symbol.clone().into_bound_py_any(py)?)?;
        kwargs.set_item("date", self.date.clone().into_bound_py_any(py)?)?;
        kwargs.set_item("daa", self.daa.clone().into_bound_py_any(py)?)?;
        kwargs.set_item("company", self.company.clone().into_bound_py_any(py)?)?;
        kwargs.set_item("exchange", self.exchange.clone().into_bound_py_any(py)?)?;
        kwargs.set_item("actions", self.actions.clone().into_bound_py_any(py)?)?;
        kwargs.set_item(
            "shares",
            self.shares
                .as_ref()
                .map(::serde_json::to_string)
                .transpose()
                .map_err(|error| {
                    ::pyo3::exceptions::PyValueError::new_err(format!(
                        "failed to serialize field `shares`: {error}"
                    ))
                })?
                .into_bound_py_any(py)?,
        )?;
        kwargs.set_item(
            "price_range",
            self.price_range
                .as_ref()
                .map(::serde_json::to_string)
                .transpose()
                .map_err(|error| {
                    ::pyo3::exceptions::PyValueError::new_err(format!(
                        "failed to serialize field `price_range`: {error}"
                    ))
                })?
                .into_bound_py_any(py)?,
        )?;
        kwargs.set_item(
            "market_cap",
            self.market_cap
                .as_ref()
                .map(::serde_json::to_string)
                .transpose()
                .map_err(|error| {
                    ::pyo3::exceptions::PyValueError::new_err(format!(
                        "failed to serialize field `market_cap`: {error}"
                    ))
                })?
                .into_bound_py_any(py)?,
        )?;
        Ok((PyTuple::empty(py), kwargs))
    }

    #[getter]
    fn shares<'py>(&self, py: Python<'py>) -> PyResult<Bound<'py, PyAny>> {
        match &self.shares {
            Some(value) => crate::models::convert::json_to_py(py, value),
            None => Ok(py.None().into_bound(py)),
        }
    }

    #[getter]
    fn price_range<'py>(&self, py: Python<'py>) -> PyResult<Bound<'py, PyAny>> {
        match &self.price_range {
            Some(value) => crate::models::convert::json_to_py(py, value),
            None => Ok(py.None().into_bound(py)),
        }
    }

    #[getter]
    fn market_cap<'py>(&self, py: Python<'py>) -> PyResult<Bound<'py, PyAny>> {
        match &self.market_cap {
            Some(value) => crate::models::convert::json_to_py(py, value),
            None => Ok(py.None().into_bound(py)),
        }
    }
}

impl From<libfmp::responses::calendar::IpoCalendarEvent> for IpoCalendarEvent {
    fn from(value: libfmp::responses::calendar::IpoCalendarEvent) -> Self {
        Self {
            symbol: value.symbol.into_inner(),
            date: value.date.into_inner(),
            daa: value.daa.as_str().to_owned(),
            company: value.company,
            exchange: value.exchange.into_inner(),
            actions: value.actions,
            shares: value.shares,
            price_range: value.price_range,
            market_cap: value.market_cap,
        }
    }
}

#[gen_stub_pyclass]
#[pyclass(module = "fmp._native.calendar", frozen, eq, from_py_object)]
#[derive(Clone, PartialEq)]
pub(crate) struct IpoDisclosure {
    #[pyo3(get)]
    pub symbol: String,
    #[pyo3(get)]
    pub filing_date: ::chrono::NaiveDate,
    #[pyo3(get)]
    pub accepted_date: ::chrono::NaiveDate,
    #[pyo3(get)]
    pub effectiveness_date: ::chrono::NaiveDate,
    #[pyo3(get)]
    pub cik: String,
    #[pyo3(get)]
    pub form: String,
    #[pyo3(get)]
    pub url: String,
}

#[gen_stub_pymethods]
#[pymethods]
impl IpoDisclosure {
    #[new]
    #[allow(clippy::too_many_arguments)]
    #[allow(clippy::fn_params_excessive_bools)]
    #[pyo3(signature = (*, symbol, filing_date, accepted_date, effectiveness_date, cik, form, url))]
    fn new(
        symbol: String,
        filing_date: ::chrono::NaiveDate,
        accepted_date: ::chrono::NaiveDate,
        effectiveness_date: ::chrono::NaiveDate,
        cik: String,
        form: String,
        url: String,
    ) -> Self {
        Self {
            symbol,
            filing_date,
            accepted_date,
            effectiveness_date,
            cik,
            form,
            url,
        }
    }

    #[classattr]
    const __hash__: Option<Py<PyAny>> = None;

    #[allow(clippy::clone_on_copy)]
    fn __getnewargs_ex__<'py>(
        &self,
        py: Python<'py>,
    ) -> PyResult<(Bound<'py, PyTuple>, Bound<'py, PyDict>)> {
        let kwargs = PyDict::new(py);
        kwargs.set_item("symbol", self.symbol.clone().into_bound_py_any(py)?)?;
        kwargs.set_item(
            "filing_date",
            self.filing_date.clone().into_bound_py_any(py)?,
        )?;
        kwargs.set_item(
            "accepted_date",
            self.accepted_date.clone().into_bound_py_any(py)?,
        )?;
        kwargs.set_item(
            "effectiveness_date",
            self.effectiveness_date.clone().into_bound_py_any(py)?,
        )?;
        kwargs.set_item("cik", self.cik.clone().into_bound_py_any(py)?)?;
        kwargs.set_item("form", self.form.clone().into_bound_py_any(py)?)?;
        kwargs.set_item("url", self.url.clone().into_bound_py_any(py)?)?;
        Ok((PyTuple::empty(py), kwargs))
    }
}

impl From<libfmp::responses::calendar::IpoDisclosure> for IpoDisclosure {
    fn from(value: libfmp::responses::calendar::IpoDisclosure) -> Self {
        Self {
            symbol: value.symbol.into_inner(),
            filing_date: value.filing_date.into_inner(),
            accepted_date: value.accepted_date.into_inner(),
            effectiveness_date: value.effectiveness_date.into_inner(),
            cik: value.cik.into_inner(),
            form: value.form,
            url: value.url,
        }
    }
}

#[gen_stub_pyclass]
#[pyclass(module = "fmp._native.calendar", frozen, eq, from_py_object)]
#[derive(Clone, PartialEq)]
pub(crate) struct IpoProspectus {
    #[pyo3(get)]
    pub symbol: String,
    #[pyo3(get)]
    pub accepted_date: ::chrono::NaiveDate,
    #[pyo3(get)]
    pub filing_date: ::chrono::NaiveDate,
    #[pyo3(get)]
    pub ipo_date: ::chrono::NaiveDate,
    #[pyo3(get)]
    pub cik: String,
    #[pyo3(get)]
    pub price_public_per_share: f64,
    #[pyo3(get)]
    pub price_public_total: f64,
    #[pyo3(get)]
    pub discounts_and_commissions_per_share: f64,
    #[pyo3(get)]
    pub discounts_and_commissions_total: f64,
    #[pyo3(get)]
    pub proceeds_before_expenses_per_share: f64,
    #[pyo3(get)]
    pub proceeds_before_expenses_total: f64,
    #[pyo3(get)]
    pub form: String,
    #[pyo3(get)]
    pub url: String,
}

#[gen_stub_pymethods]
#[pymethods]
impl IpoProspectus {
    #[new]
    #[allow(clippy::too_many_arguments)]
    #[allow(clippy::fn_params_excessive_bools)]
    #[pyo3(signature = (*, symbol, accepted_date, filing_date, ipo_date, cik, price_public_per_share, price_public_total, discounts_and_commissions_per_share, discounts_and_commissions_total, proceeds_before_expenses_per_share, proceeds_before_expenses_total, form, url))]
    fn new(
        symbol: String,
        accepted_date: ::chrono::NaiveDate,
        filing_date: ::chrono::NaiveDate,
        ipo_date: ::chrono::NaiveDate,
        cik: String,
        price_public_per_share: f64,
        price_public_total: f64,
        discounts_and_commissions_per_share: f64,
        discounts_and_commissions_total: f64,
        proceeds_before_expenses_per_share: f64,
        proceeds_before_expenses_total: f64,
        form: String,
        url: String,
    ) -> Self {
        Self {
            symbol,
            accepted_date,
            filing_date,
            ipo_date,
            cik,
            price_public_per_share,
            price_public_total,
            discounts_and_commissions_per_share,
            discounts_and_commissions_total,
            proceeds_before_expenses_per_share,
            proceeds_before_expenses_total,
            form,
            url,
        }
    }

    #[classattr]
    const __hash__: Option<Py<PyAny>> = None;

    #[allow(clippy::clone_on_copy)]
    fn __getnewargs_ex__<'py>(
        &self,
        py: Python<'py>,
    ) -> PyResult<(Bound<'py, PyTuple>, Bound<'py, PyDict>)> {
        let kwargs = PyDict::new(py);
        kwargs.set_item("symbol", self.symbol.clone().into_bound_py_any(py)?)?;
        kwargs.set_item(
            "accepted_date",
            self.accepted_date.clone().into_bound_py_any(py)?,
        )?;
        kwargs.set_item(
            "filing_date",
            self.filing_date.clone().into_bound_py_any(py)?,
        )?;
        kwargs.set_item("ipo_date", self.ipo_date.clone().into_bound_py_any(py)?)?;
        kwargs.set_item("cik", self.cik.clone().into_bound_py_any(py)?)?;
        kwargs.set_item(
            "price_public_per_share",
            self.price_public_per_share.clone().into_bound_py_any(py)?,
        )?;
        kwargs.set_item(
            "price_public_total",
            self.price_public_total.clone().into_bound_py_any(py)?,
        )?;
        kwargs.set_item(
            "discounts_and_commissions_per_share",
            self.discounts_and_commissions_per_share
                .clone()
                .into_bound_py_any(py)?,
        )?;
        kwargs.set_item(
            "discounts_and_commissions_total",
            self.discounts_and_commissions_total
                .clone()
                .into_bound_py_any(py)?,
        )?;
        kwargs.set_item(
            "proceeds_before_expenses_per_share",
            self.proceeds_before_expenses_per_share
                .clone()
                .into_bound_py_any(py)?,
        )?;
        kwargs.set_item(
            "proceeds_before_expenses_total",
            self.proceeds_before_expenses_total
                .clone()
                .into_bound_py_any(py)?,
        )?;
        kwargs.set_item("form", self.form.clone().into_bound_py_any(py)?)?;
        kwargs.set_item("url", self.url.clone().into_bound_py_any(py)?)?;
        Ok((PyTuple::empty(py), kwargs))
    }
}

impl From<libfmp::responses::calendar::IpoProspectus> for IpoProspectus {
    fn from(value: libfmp::responses::calendar::IpoProspectus) -> Self {
        Self {
            symbol: value.symbol.into_inner(),
            accepted_date: value.accepted_date.into_inner(),
            filing_date: value.filing_date.into_inner(),
            ipo_date: value.ipo_date.into_inner(),
            cik: value.cik.into_inner(),
            price_public_per_share: value.price_public_per_share,
            price_public_total: value.price_public_total,
            discounts_and_commissions_per_share: value.discounts_and_commissions_per_share,
            discounts_and_commissions_total: value.discounts_and_commissions_total,
            proceeds_before_expenses_per_share: value.proceeds_before_expenses_per_share,
            proceeds_before_expenses_total: value.proceeds_before_expenses_total,
            form: value.form,
            url: value.url,
        }
    }
}

#[gen_stub_pyclass]
#[pyclass(module = "fmp._native.calendar", frozen, eq, from_py_object)]
#[derive(Clone, PartialEq)]
pub(crate) struct StockSplitEvent {
    #[pyo3(get)]
    pub symbol: String,
    #[pyo3(get)]
    pub date: ::chrono::NaiveDate,
    #[pyo3(get)]
    pub numerator: f64,
    #[pyo3(get)]
    pub denominator: f64,
    #[pyo3(get)]
    pub split_type: String,
}

#[gen_stub_pymethods]
#[pymethods]
impl StockSplitEvent {
    #[new]
    #[allow(clippy::too_many_arguments)]
    #[allow(clippy::fn_params_excessive_bools)]
    #[pyo3(signature = (*, symbol, date, numerator, denominator, split_type))]
    fn new(
        symbol: String,
        date: ::chrono::NaiveDate,
        numerator: f64,
        denominator: f64,
        split_type: String,
    ) -> Self {
        Self {
            symbol,
            date,
            numerator,
            denominator,
            split_type,
        }
    }

    #[classattr]
    const __hash__: Option<Py<PyAny>> = None;

    #[allow(clippy::clone_on_copy)]
    fn __getnewargs_ex__<'py>(
        &self,
        py: Python<'py>,
    ) -> PyResult<(Bound<'py, PyTuple>, Bound<'py, PyDict>)> {
        let kwargs = PyDict::new(py);
        kwargs.set_item("symbol", self.symbol.clone().into_bound_py_any(py)?)?;
        kwargs.set_item("date", self.date.clone().into_bound_py_any(py)?)?;
        kwargs.set_item("numerator", self.numerator.clone().into_bound_py_any(py)?)?;
        kwargs.set_item(
            "denominator",
            self.denominator.clone().into_bound_py_any(py)?,
        )?;
        kwargs.set_item("split_type", self.split_type.clone().into_bound_py_any(py)?)?;
        Ok((PyTuple::empty(py), kwargs))
    }
}

impl From<libfmp::responses::calendar::StockSplitEvent> for StockSplitEvent {
    fn from(value: libfmp::responses::calendar::StockSplitEvent) -> Self {
        Self {
            symbol: value.symbol.into_inner(),
            date: value.date.into_inner(),
            numerator: value.numerator,
            denominator: value.denominator,
            split_type: value.split_type,
        }
    }
}
