// @generated by gen_models; do not edit by hand.

use pyo3::IntoPyObjectExt;
use pyo3::prelude::*;
use pyo3::types::PyTuple;
use pyo3_stub_gen::derive::{gen_stub_pyclass, gen_stub_pymethods};

#[gen_stub_pyclass]
#[pyclass(module = "fmp._native.tipranks", frozen, from_py_object)]
#[derive(Clone)]
pub(crate) struct TipRanksRatingSearchResult {
    #[pyo3(get)]
    pub symbol: String,
    #[pyo3(get)]
    pub date: String,
    #[pyo3(get)]
    pub recommendation_date: ::chrono::NaiveDate,
    #[pyo3(get)]
    pub expert_uid: String,
    #[pyo3(get)]
    pub analyst_name: String,
    #[pyo3(get)]
    pub firm_name: String,
    #[pyo3(get)]
    pub recommendation: String,
    #[pyo3(get)]
    pub analyst_action: String,
    #[pyo3(get)]
    pub article_title: String,
    #[pyo3(get)]
    pub article_site: String,
    price_target: ::serde_json::Number,
    #[pyo3(get)]
    pub price_target_currency: String,
    #[pyo3(get)]
    pub url: String,
}

#[gen_stub_pymethods]
#[pymethods]
impl TipRanksRatingSearchResult {
    #[new]
    #[allow(clippy::too_many_arguments)]
    #[allow(clippy::fn_params_excessive_bools)]
    #[pyo3(signature = (symbol, date, recommendation_date, expert_uid, analyst_name, firm_name, recommendation, analyst_action, article_title, article_site, price_target, price_target_currency, url))]
    fn new(
        symbol: String,
        date: String,
        recommendation_date: ::chrono::NaiveDate,
        expert_uid: String,
        analyst_name: String,
        firm_name: String,
        recommendation: String,
        analyst_action: String,
        article_title: String,
        article_site: String,
        price_target: String,
        price_target_currency: String,
        url: String,
    ) -> PyResult<Self> {
        let price_target =
            ::serde_json::from_str::<::serde_json::Number>(&price_target).map_err(|error| {
                ::pyo3::exceptions::PyValueError::new_err(format!(
                    "invalid JSON for field `price_target`: {error}"
                ))
            })?;
        Ok(Self {
            symbol,
            date,
            recommendation_date,
            expert_uid,
            analyst_name,
            firm_name,
            recommendation,
            analyst_action,
            article_title,
            article_site,
            price_target,
            price_target_currency,
            url,
        })
    }

    #[allow(clippy::clone_on_copy)]
    fn __getnewargs__<'py>(&self, py: Python<'py>) -> PyResult<Bound<'py, PyTuple>> {
        let members: Vec<Bound<'py, PyAny>> = vec![
            self.symbol.clone().into_bound_py_any(py)?,
            self.date.clone().into_bound_py_any(py)?,
            self.recommendation_date.clone().into_bound_py_any(py)?,
            self.expert_uid.clone().into_bound_py_any(py)?,
            self.analyst_name.clone().into_bound_py_any(py)?,
            self.firm_name.clone().into_bound_py_any(py)?,
            self.recommendation.clone().into_bound_py_any(py)?,
            self.analyst_action.clone().into_bound_py_any(py)?,
            self.article_title.clone().into_bound_py_any(py)?,
            self.article_site.clone().into_bound_py_any(py)?,
            ::serde_json::to_string(&self.price_target)
                .map_err(|error| {
                    ::pyo3::exceptions::PyValueError::new_err(format!(
                        "failed to serialize field `price_target`: {error}"
                    ))
                })?
                .into_bound_py_any(py)?,
            self.price_target_currency.clone().into_bound_py_any(py)?,
            self.url.clone().into_bound_py_any(py)?,
        ];
        PyTuple::new(py, members)
    }

    #[getter]
    fn price_target<'py>(&self, py: Python<'py>) -> PyResult<Bound<'py, PyAny>> {
        crate::models::convert::number_to_py(py, &self.price_target)
    }
}

impl From<libfmp::responses::tipranks::TipRanksRatingSearchResult> for TipRanksRatingSearchResult {
    fn from(value: libfmp::responses::tipranks::TipRanksRatingSearchResult) -> Self {
        Self {
            symbol: value.symbol.into_inner(),
            date: value.date.as_str().to_owned(),
            recommendation_date: value.recommendation_date.into_inner(),
            expert_uid: value.expert_uid.into_inner(),
            analyst_name: value.analyst_name,
            firm_name: value.firm_name,
            recommendation: value.recommendation,
            analyst_action: value.analyst_action,
            article_title: value.article_title,
            article_site: value.article_site,
            price_target: value.price_target,
            price_target_currency: value.price_target_currency.into_inner(),
            url: value.url,
        }
    }
}

#[gen_stub_pyclass]
#[pyclass(module = "fmp._native.tipranks", frozen, from_py_object)]
#[derive(Clone)]
pub(crate) struct TipRanksPointInTimeRating {
    #[pyo3(get)]
    pub symbol: String,
    #[pyo3(get)]
    pub date: String,
    #[pyo3(get)]
    pub expert_uid: String,
    #[pyo3(get)]
    pub analyst_name: String,
    stock_success_rate: ::serde_json::Number,
    #[pyo3(get)]
    pub firm_name: String,
    #[pyo3(get)]
    pub last_recommendation: String,
    #[pyo3(get)]
    pub last_recommendation_date: ::chrono::NaiveDate,
    #[pyo3(get)]
    pub article_title: String,
    #[pyo3(get)]
    pub article_site: String,
    price_target: Option<::serde_json::Number>,
    #[pyo3(get)]
    pub price_target_currency: Option<String>,
    #[pyo3(get)]
    pub url: String,
    #[pyo3(get)]
    pub last_analyst_action: String,
    stock_return: Option<::serde_json::Number>,
    #[pyo3(get)]
    pub beat_target: Option<bool>,
}

#[gen_stub_pymethods]
#[pymethods]
impl TipRanksPointInTimeRating {
    #[new]
    #[allow(clippy::too_many_arguments)]
    #[allow(clippy::fn_params_excessive_bools)]
    #[pyo3(signature = (symbol, date, expert_uid, analyst_name, stock_success_rate, firm_name, last_recommendation, last_recommendation_date, article_title, article_site, price_target, price_target_currency, url, last_analyst_action, stock_return, beat_target))]
    fn new(
        symbol: String,
        date: String,
        expert_uid: String,
        analyst_name: String,
        stock_success_rate: String,
        firm_name: String,
        last_recommendation: String,
        last_recommendation_date: ::chrono::NaiveDate,
        article_title: String,
        article_site: String,
        price_target: Option<String>,
        price_target_currency: Option<String>,
        url: String,
        last_analyst_action: String,
        stock_return: Option<String>,
        beat_target: Option<bool>,
    ) -> PyResult<Self> {
        let stock_success_rate = ::serde_json::from_str::<::serde_json::Number>(
            &stock_success_rate,
        )
        .map_err(|error| {
            ::pyo3::exceptions::PyValueError::new_err(format!(
                "invalid JSON for field `stock_success_rate`: {error}"
            ))
        })?;
        let price_target = match price_target {
            Some(text) => Some(
                ::serde_json::from_str::<::serde_json::Number>(&text).map_err(|error| {
                    ::pyo3::exceptions::PyValueError::new_err(format!(
                        "invalid JSON for field `price_target`: {error}"
                    ))
                })?,
            ),
            None => None,
        };
        let stock_return = match stock_return {
            Some(text) => Some(
                ::serde_json::from_str::<::serde_json::Number>(&text).map_err(|error| {
                    ::pyo3::exceptions::PyValueError::new_err(format!(
                        "invalid JSON for field `stock_return`: {error}"
                    ))
                })?,
            ),
            None => None,
        };
        Ok(Self {
            symbol,
            date,
            expert_uid,
            analyst_name,
            stock_success_rate,
            firm_name,
            last_recommendation,
            last_recommendation_date,
            article_title,
            article_site,
            price_target,
            price_target_currency,
            url,
            last_analyst_action,
            stock_return,
            beat_target,
        })
    }

    #[allow(clippy::clone_on_copy)]
    fn __getnewargs__<'py>(&self, py: Python<'py>) -> PyResult<Bound<'py, PyTuple>> {
        let members: Vec<Bound<'py, PyAny>> = vec![
            self.symbol.clone().into_bound_py_any(py)?,
            self.date.clone().into_bound_py_any(py)?,
            self.expert_uid.clone().into_bound_py_any(py)?,
            self.analyst_name.clone().into_bound_py_any(py)?,
            ::serde_json::to_string(&self.stock_success_rate)
                .map_err(|error| {
                    ::pyo3::exceptions::PyValueError::new_err(format!(
                        "failed to serialize field `stock_success_rate`: {error}"
                    ))
                })?
                .into_bound_py_any(py)?,
            self.firm_name.clone().into_bound_py_any(py)?,
            self.last_recommendation.clone().into_bound_py_any(py)?,
            self.last_recommendation_date
                .clone()
                .into_bound_py_any(py)?,
            self.article_title.clone().into_bound_py_any(py)?,
            self.article_site.clone().into_bound_py_any(py)?,
            self.price_target
                .as_ref()
                .map(::serde_json::to_string)
                .transpose()
                .map_err(|error| {
                    ::pyo3::exceptions::PyValueError::new_err(format!(
                        "failed to serialize field `price_target`: {error}"
                    ))
                })?
                .into_bound_py_any(py)?,
            self.price_target_currency.clone().into_bound_py_any(py)?,
            self.url.clone().into_bound_py_any(py)?,
            self.last_analyst_action.clone().into_bound_py_any(py)?,
            self.stock_return
                .as_ref()
                .map(::serde_json::to_string)
                .transpose()
                .map_err(|error| {
                    ::pyo3::exceptions::PyValueError::new_err(format!(
                        "failed to serialize field `stock_return`: {error}"
                    ))
                })?
                .into_bound_py_any(py)?,
            self.beat_target.clone().into_bound_py_any(py)?,
        ];
        PyTuple::new(py, members)
    }

    #[getter]
    fn stock_success_rate<'py>(&self, py: Python<'py>) -> PyResult<Bound<'py, PyAny>> {
        crate::models::convert::number_to_py(py, &self.stock_success_rate)
    }

    #[getter]
    fn price_target<'py>(&self, py: Python<'py>) -> PyResult<Bound<'py, PyAny>> {
        match &self.price_target {
            Some(value) => crate::models::convert::number_to_py(py, value),
            None => Ok(py.None().into_bound(py)),
        }
    }

    #[getter]
    fn stock_return<'py>(&self, py: Python<'py>) -> PyResult<Bound<'py, PyAny>> {
        match &self.stock_return {
            Some(value) => crate::models::convert::number_to_py(py, value),
            None => Ok(py.None().into_bound(py)),
        }
    }
}

impl From<libfmp::responses::tipranks::TipRanksPointInTimeRating> for TipRanksPointInTimeRating {
    fn from(value: libfmp::responses::tipranks::TipRanksPointInTimeRating) -> Self {
        Self {
            symbol: value.symbol.into_inner(),
            date: value.date.as_str().to_owned(),
            expert_uid: value.expert_uid.into_inner(),
            analyst_name: value.analyst_name,
            stock_success_rate: value.stock_success_rate,
            firm_name: value.firm_name,
            last_recommendation: value.last_recommendation,
            last_recommendation_date: value.last_recommendation_date.into_inner(),
            article_title: value.article_title,
            article_site: value.article_site,
            price_target: value.price_target,
            price_target_currency: value.price_target_currency.map(|value| value.into_inner()),
            url: value.url,
            last_analyst_action: value.last_analyst_action,
            stock_return: value.stock_return,
            beat_target: value.beat_target,
        }
    }
}

#[gen_stub_pyclass]
#[pyclass(module = "fmp._native.tipranks", frozen, from_py_object)]
#[derive(Clone)]
pub(crate) struct TipRanksRecommendationCounts {
    #[pyo3(get)]
    pub buy: u64,
    #[pyo3(get)]
    pub hold: u64,
    #[pyo3(get)]
    pub sell: u64,
}

#[gen_stub_pymethods]
#[pymethods]
impl TipRanksRecommendationCounts {
    #[new]
    #[allow(clippy::too_many_arguments)]
    #[allow(clippy::fn_params_excessive_bools)]
    #[pyo3(signature = (buy, hold, sell))]
    fn new(buy: u64, hold: u64, sell: u64) -> Self {
        Self { buy, hold, sell }
    }

    #[allow(clippy::clone_on_copy)]
    fn __getnewargs__<'py>(&self, py: Python<'py>) -> PyResult<Bound<'py, PyTuple>> {
        let members: Vec<Bound<'py, PyAny>> = vec![
            self.buy.clone().into_bound_py_any(py)?,
            self.hold.clone().into_bound_py_any(py)?,
            self.sell.clone().into_bound_py_any(py)?,
        ];
        PyTuple::new(py, members)
    }
}

impl From<libfmp::responses::tipranks::TipRanksRecommendationCounts>
    for TipRanksRecommendationCounts
{
    fn from(value: libfmp::responses::tipranks::TipRanksRecommendationCounts) -> Self {
        Self {
            buy: value.buy,
            hold: value.hold,
            sell: value.sell,
        }
    }
}

#[gen_stub_pyclass]
#[pyclass(module = "fmp._native.tipranks", frozen, from_py_object)]
#[derive(Clone)]
pub(crate) struct TipRanksAnalystActionCounts {
    #[pyo3(get)]
    pub initiated: u64,
    #[pyo3(get)]
    pub maintained: u64,
    #[pyo3(get)]
    pub upgraded: u64,
    #[pyo3(get)]
    pub downgraded: u64,
    #[pyo3(get)]
    pub reiterated: u64,
    #[pyo3(get)]
    pub resumed: u64,
}

#[gen_stub_pymethods]
#[pymethods]
impl TipRanksAnalystActionCounts {
    #[new]
    #[allow(clippy::too_many_arguments)]
    #[allow(clippy::fn_params_excessive_bools)]
    #[pyo3(signature = (initiated, maintained, upgraded, downgraded, reiterated, resumed))]
    fn new(
        initiated: u64,
        maintained: u64,
        upgraded: u64,
        downgraded: u64,
        reiterated: u64,
        resumed: u64,
    ) -> Self {
        Self {
            initiated,
            maintained,
            upgraded,
            downgraded,
            reiterated,
            resumed,
        }
    }

    #[allow(clippy::clone_on_copy)]
    fn __getnewargs__<'py>(&self, py: Python<'py>) -> PyResult<Bound<'py, PyTuple>> {
        let members: Vec<Bound<'py, PyAny>> = vec![
            self.initiated.clone().into_bound_py_any(py)?,
            self.maintained.clone().into_bound_py_any(py)?,
            self.upgraded.clone().into_bound_py_any(py)?,
            self.downgraded.clone().into_bound_py_any(py)?,
            self.reiterated.clone().into_bound_py_any(py)?,
            self.resumed.clone().into_bound_py_any(py)?,
        ];
        PyTuple::new(py, members)
    }
}

impl From<libfmp::responses::tipranks::TipRanksAnalystActionCounts>
    for TipRanksAnalystActionCounts
{
    fn from(value: libfmp::responses::tipranks::TipRanksAnalystActionCounts) -> Self {
        Self {
            initiated: value.initiated,
            maintained: value.maintained,
            upgraded: value.upgraded,
            downgraded: value.downgraded,
            reiterated: value.reiterated,
            resumed: value.resumed,
        }
    }
}

#[gen_stub_pyclass]
#[pyclass(module = "fmp._native.tipranks", frozen, from_py_object)]
#[derive(Clone)]
pub(crate) struct TipRanksSymbolSummary {
    #[pyo3(get)]
    pub symbol: String,
    #[pyo3(get)]
    pub from_: ::chrono::NaiveDate,
    #[pyo3(get)]
    pub to: ::chrono::NaiveDate,
    #[pyo3(get)]
    pub total_recommendations: u64,
    #[pyo3(get)]
    pub distinct_symbols: u64,
    #[pyo3(get)]
    pub distinct_analysts: u64,
    #[pyo3(get)]
    pub valid_price_targets: u64,
    #[pyo3(get)]
    pub recommendations: crate::models::tipranks::TipRanksRecommendationCounts,
    #[pyo3(get)]
    pub analyst_action: crate::models::tipranks::TipRanksAnalystActionCounts,
    #[pyo3(get)]
    pub compared_price_targets: u64,
    #[pyo3(get)]
    pub beats: u64,
    #[pyo3(get)]
    pub misses: u64,
    average_return: ::serde_json::Number,
    top_return: ::serde_json::Number,
    worst_return: ::serde_json::Number,
}

#[gen_stub_pymethods]
#[pymethods]
impl TipRanksSymbolSummary {
    #[new]
    #[allow(clippy::too_many_arguments)]
    #[allow(clippy::fn_params_excessive_bools)]
    #[pyo3(signature = (symbol, from_, to, total_recommendations, distinct_symbols, distinct_analysts, valid_price_targets, recommendations, analyst_action, compared_price_targets, beats, misses, average_return, top_return, worst_return))]
    fn new(
        symbol: String,
        from_: ::chrono::NaiveDate,
        to: ::chrono::NaiveDate,
        total_recommendations: u64,
        distinct_symbols: u64,
        distinct_analysts: u64,
        valid_price_targets: u64,
        recommendations: crate::models::tipranks::TipRanksRecommendationCounts,
        analyst_action: crate::models::tipranks::TipRanksAnalystActionCounts,
        compared_price_targets: u64,
        beats: u64,
        misses: u64,
        average_return: String,
        top_return: String,
        worst_return: String,
    ) -> PyResult<Self> {
        let average_return = ::serde_json::from_str::<::serde_json::Number>(&average_return)
            .map_err(|error| {
                ::pyo3::exceptions::PyValueError::new_err(format!(
                    "invalid JSON for field `average_return`: {error}"
                ))
            })?;
        let top_return =
            ::serde_json::from_str::<::serde_json::Number>(&top_return).map_err(|error| {
                ::pyo3::exceptions::PyValueError::new_err(format!(
                    "invalid JSON for field `top_return`: {error}"
                ))
            })?;
        let worst_return =
            ::serde_json::from_str::<::serde_json::Number>(&worst_return).map_err(|error| {
                ::pyo3::exceptions::PyValueError::new_err(format!(
                    "invalid JSON for field `worst_return`: {error}"
                ))
            })?;
        Ok(Self {
            symbol,
            from_,
            to,
            total_recommendations,
            distinct_symbols,
            distinct_analysts,
            valid_price_targets,
            recommendations,
            analyst_action,
            compared_price_targets,
            beats,
            misses,
            average_return,
            top_return,
            worst_return,
        })
    }

    #[allow(clippy::clone_on_copy)]
    fn __getnewargs__<'py>(&self, py: Python<'py>) -> PyResult<Bound<'py, PyTuple>> {
        let members: Vec<Bound<'py, PyAny>> = vec![
            self.symbol.clone().into_bound_py_any(py)?,
            self.from_.clone().into_bound_py_any(py)?,
            self.to.clone().into_bound_py_any(py)?,
            self.total_recommendations.clone().into_bound_py_any(py)?,
            self.distinct_symbols.clone().into_bound_py_any(py)?,
            self.distinct_analysts.clone().into_bound_py_any(py)?,
            self.valid_price_targets.clone().into_bound_py_any(py)?,
            self.recommendations.clone().into_bound_py_any(py)?,
            self.analyst_action.clone().into_bound_py_any(py)?,
            self.compared_price_targets.clone().into_bound_py_any(py)?,
            self.beats.clone().into_bound_py_any(py)?,
            self.misses.clone().into_bound_py_any(py)?,
            ::serde_json::to_string(&self.average_return)
                .map_err(|error| {
                    ::pyo3::exceptions::PyValueError::new_err(format!(
                        "failed to serialize field `average_return`: {error}"
                    ))
                })?
                .into_bound_py_any(py)?,
            ::serde_json::to_string(&self.top_return)
                .map_err(|error| {
                    ::pyo3::exceptions::PyValueError::new_err(format!(
                        "failed to serialize field `top_return`: {error}"
                    ))
                })?
                .into_bound_py_any(py)?,
            ::serde_json::to_string(&self.worst_return)
                .map_err(|error| {
                    ::pyo3::exceptions::PyValueError::new_err(format!(
                        "failed to serialize field `worst_return`: {error}"
                    ))
                })?
                .into_bound_py_any(py)?,
        ];
        PyTuple::new(py, members)
    }

    #[getter]
    fn average_return<'py>(&self, py: Python<'py>) -> PyResult<Bound<'py, PyAny>> {
        crate::models::convert::number_to_py(py, &self.average_return)
    }

    #[getter]
    fn top_return<'py>(&self, py: Python<'py>) -> PyResult<Bound<'py, PyAny>> {
        crate::models::convert::number_to_py(py, &self.top_return)
    }

    #[getter]
    fn worst_return<'py>(&self, py: Python<'py>) -> PyResult<Bound<'py, PyAny>> {
        crate::models::convert::number_to_py(py, &self.worst_return)
    }
}

impl From<libfmp::responses::tipranks::TipRanksSymbolSummary> for TipRanksSymbolSummary {
    fn from(value: libfmp::responses::tipranks::TipRanksSymbolSummary) -> Self {
        Self {
            symbol: value.symbol.into_inner(),
            from_: value.from.into_inner(),
            to: value.to.into_inner(),
            total_recommendations: value.total_recommendations,
            distinct_symbols: value.distinct_symbols,
            distinct_analysts: value.distinct_analysts,
            valid_price_targets: value.valid_price_targets,
            recommendations: crate::models::tipranks::TipRanksRecommendationCounts::from(
                value.recommendations,
            ),
            analyst_action: crate::models::tipranks::TipRanksAnalystActionCounts::from(
                value.analyst_action,
            ),
            compared_price_targets: value.compared_price_targets,
            beats: value.beats,
            misses: value.misses,
            average_return: value.average_return,
            top_return: value.top_return,
            worst_return: value.worst_return,
        }
    }
}

#[gen_stub_pyclass]
#[pyclass(module = "fmp._native.tipranks", frozen, from_py_object)]
#[derive(Clone)]
pub(crate) struct TipRanksAnalystSummary {
    #[pyo3(get)]
    pub expert_uid: String,
    #[pyo3(get)]
    pub from_: ::chrono::NaiveDate,
    #[pyo3(get)]
    pub to: ::chrono::NaiveDate,
    #[pyo3(get)]
    pub total_recommendations: u64,
    #[pyo3(get)]
    pub distinct_symbols: u64,
    #[pyo3(get)]
    pub distinct_analysts: u64,
    #[pyo3(get)]
    pub valid_price_targets: u64,
    #[pyo3(get)]
    pub recommendations: crate::models::tipranks::TipRanksRecommendationCounts,
    #[pyo3(get)]
    pub analyst_action: crate::models::tipranks::TipRanksAnalystActionCounts,
    #[pyo3(get)]
    pub compared_price_targets: u64,
    #[pyo3(get)]
    pub beats: u64,
    #[pyo3(get)]
    pub misses: u64,
    average_return: ::serde_json::Number,
    top_return: ::serde_json::Number,
    worst_return: ::serde_json::Number,
}

#[gen_stub_pymethods]
#[pymethods]
impl TipRanksAnalystSummary {
    #[new]
    #[allow(clippy::too_many_arguments)]
    #[allow(clippy::fn_params_excessive_bools)]
    #[pyo3(signature = (expert_uid, from_, to, total_recommendations, distinct_symbols, distinct_analysts, valid_price_targets, recommendations, analyst_action, compared_price_targets, beats, misses, average_return, top_return, worst_return))]
    fn new(
        expert_uid: String,
        from_: ::chrono::NaiveDate,
        to: ::chrono::NaiveDate,
        total_recommendations: u64,
        distinct_symbols: u64,
        distinct_analysts: u64,
        valid_price_targets: u64,
        recommendations: crate::models::tipranks::TipRanksRecommendationCounts,
        analyst_action: crate::models::tipranks::TipRanksAnalystActionCounts,
        compared_price_targets: u64,
        beats: u64,
        misses: u64,
        average_return: String,
        top_return: String,
        worst_return: String,
    ) -> PyResult<Self> {
        let average_return = ::serde_json::from_str::<::serde_json::Number>(&average_return)
            .map_err(|error| {
                ::pyo3::exceptions::PyValueError::new_err(format!(
                    "invalid JSON for field `average_return`: {error}"
                ))
            })?;
        let top_return =
            ::serde_json::from_str::<::serde_json::Number>(&top_return).map_err(|error| {
                ::pyo3::exceptions::PyValueError::new_err(format!(
                    "invalid JSON for field `top_return`: {error}"
                ))
            })?;
        let worst_return =
            ::serde_json::from_str::<::serde_json::Number>(&worst_return).map_err(|error| {
                ::pyo3::exceptions::PyValueError::new_err(format!(
                    "invalid JSON for field `worst_return`: {error}"
                ))
            })?;
        Ok(Self {
            expert_uid,
            from_,
            to,
            total_recommendations,
            distinct_symbols,
            distinct_analysts,
            valid_price_targets,
            recommendations,
            analyst_action,
            compared_price_targets,
            beats,
            misses,
            average_return,
            top_return,
            worst_return,
        })
    }

    #[allow(clippy::clone_on_copy)]
    fn __getnewargs__<'py>(&self, py: Python<'py>) -> PyResult<Bound<'py, PyTuple>> {
        let members: Vec<Bound<'py, PyAny>> = vec![
            self.expert_uid.clone().into_bound_py_any(py)?,
            self.from_.clone().into_bound_py_any(py)?,
            self.to.clone().into_bound_py_any(py)?,
            self.total_recommendations.clone().into_bound_py_any(py)?,
            self.distinct_symbols.clone().into_bound_py_any(py)?,
            self.distinct_analysts.clone().into_bound_py_any(py)?,
            self.valid_price_targets.clone().into_bound_py_any(py)?,
            self.recommendations.clone().into_bound_py_any(py)?,
            self.analyst_action.clone().into_bound_py_any(py)?,
            self.compared_price_targets.clone().into_bound_py_any(py)?,
            self.beats.clone().into_bound_py_any(py)?,
            self.misses.clone().into_bound_py_any(py)?,
            ::serde_json::to_string(&self.average_return)
                .map_err(|error| {
                    ::pyo3::exceptions::PyValueError::new_err(format!(
                        "failed to serialize field `average_return`: {error}"
                    ))
                })?
                .into_bound_py_any(py)?,
            ::serde_json::to_string(&self.top_return)
                .map_err(|error| {
                    ::pyo3::exceptions::PyValueError::new_err(format!(
                        "failed to serialize field `top_return`: {error}"
                    ))
                })?
                .into_bound_py_any(py)?,
            ::serde_json::to_string(&self.worst_return)
                .map_err(|error| {
                    ::pyo3::exceptions::PyValueError::new_err(format!(
                        "failed to serialize field `worst_return`: {error}"
                    ))
                })?
                .into_bound_py_any(py)?,
        ];
        PyTuple::new(py, members)
    }

    #[getter]
    fn average_return<'py>(&self, py: Python<'py>) -> PyResult<Bound<'py, PyAny>> {
        crate::models::convert::number_to_py(py, &self.average_return)
    }

    #[getter]
    fn top_return<'py>(&self, py: Python<'py>) -> PyResult<Bound<'py, PyAny>> {
        crate::models::convert::number_to_py(py, &self.top_return)
    }

    #[getter]
    fn worst_return<'py>(&self, py: Python<'py>) -> PyResult<Bound<'py, PyAny>> {
        crate::models::convert::number_to_py(py, &self.worst_return)
    }
}

impl From<libfmp::responses::tipranks::TipRanksAnalystSummary> for TipRanksAnalystSummary {
    fn from(value: libfmp::responses::tipranks::TipRanksAnalystSummary) -> Self {
        Self {
            expert_uid: value.expert_uid.into_inner(),
            from_: value.from.into_inner(),
            to: value.to.into_inner(),
            total_recommendations: value.total_recommendations,
            distinct_symbols: value.distinct_symbols,
            distinct_analysts: value.distinct_analysts,
            valid_price_targets: value.valid_price_targets,
            recommendations: crate::models::tipranks::TipRanksRecommendationCounts::from(
                value.recommendations,
            ),
            analyst_action: crate::models::tipranks::TipRanksAnalystActionCounts::from(
                value.analyst_action,
            ),
            compared_price_targets: value.compared_price_targets,
            beats: value.beats,
            misses: value.misses,
            average_return: value.average_return,
            top_return: value.top_return,
            worst_return: value.worst_return,
        }
    }
}

#[gen_stub_pyclass]
#[pyclass(module = "fmp._native.tipranks", frozen, from_py_object)]
#[derive(Clone)]
pub(crate) struct TipRanksFirmSummary {
    #[pyo3(get)]
    pub firm_name: String,
    #[pyo3(get)]
    pub from_: ::chrono::NaiveDate,
    #[pyo3(get)]
    pub to: ::chrono::NaiveDate,
    #[pyo3(get)]
    pub total_recommendations: u64,
    #[pyo3(get)]
    pub distinct_symbols: u64,
    #[pyo3(get)]
    pub distinct_analysts: u64,
    #[pyo3(get)]
    pub valid_price_targets: u64,
    #[pyo3(get)]
    pub recommendations: crate::models::tipranks::TipRanksRecommendationCounts,
    #[pyo3(get)]
    pub analyst_action: crate::models::tipranks::TipRanksAnalystActionCounts,
    #[pyo3(get)]
    pub compared_price_targets: u64,
    #[pyo3(get)]
    pub beats: u64,
    #[pyo3(get)]
    pub misses: u64,
    average_return: ::serde_json::Number,
    top_return: ::serde_json::Number,
    worst_return: ::serde_json::Number,
}

#[gen_stub_pymethods]
#[pymethods]
impl TipRanksFirmSummary {
    #[new]
    #[allow(clippy::too_many_arguments)]
    #[allow(clippy::fn_params_excessive_bools)]
    #[pyo3(signature = (firm_name, from_, to, total_recommendations, distinct_symbols, distinct_analysts, valid_price_targets, recommendations, analyst_action, compared_price_targets, beats, misses, average_return, top_return, worst_return))]
    fn new(
        firm_name: String,
        from_: ::chrono::NaiveDate,
        to: ::chrono::NaiveDate,
        total_recommendations: u64,
        distinct_symbols: u64,
        distinct_analysts: u64,
        valid_price_targets: u64,
        recommendations: crate::models::tipranks::TipRanksRecommendationCounts,
        analyst_action: crate::models::tipranks::TipRanksAnalystActionCounts,
        compared_price_targets: u64,
        beats: u64,
        misses: u64,
        average_return: String,
        top_return: String,
        worst_return: String,
    ) -> PyResult<Self> {
        let average_return = ::serde_json::from_str::<::serde_json::Number>(&average_return)
            .map_err(|error| {
                ::pyo3::exceptions::PyValueError::new_err(format!(
                    "invalid JSON for field `average_return`: {error}"
                ))
            })?;
        let top_return =
            ::serde_json::from_str::<::serde_json::Number>(&top_return).map_err(|error| {
                ::pyo3::exceptions::PyValueError::new_err(format!(
                    "invalid JSON for field `top_return`: {error}"
                ))
            })?;
        let worst_return =
            ::serde_json::from_str::<::serde_json::Number>(&worst_return).map_err(|error| {
                ::pyo3::exceptions::PyValueError::new_err(format!(
                    "invalid JSON for field `worst_return`: {error}"
                ))
            })?;
        Ok(Self {
            firm_name,
            from_,
            to,
            total_recommendations,
            distinct_symbols,
            distinct_analysts,
            valid_price_targets,
            recommendations,
            analyst_action,
            compared_price_targets,
            beats,
            misses,
            average_return,
            top_return,
            worst_return,
        })
    }

    #[allow(clippy::clone_on_copy)]
    fn __getnewargs__<'py>(&self, py: Python<'py>) -> PyResult<Bound<'py, PyTuple>> {
        let members: Vec<Bound<'py, PyAny>> = vec![
            self.firm_name.clone().into_bound_py_any(py)?,
            self.from_.clone().into_bound_py_any(py)?,
            self.to.clone().into_bound_py_any(py)?,
            self.total_recommendations.clone().into_bound_py_any(py)?,
            self.distinct_symbols.clone().into_bound_py_any(py)?,
            self.distinct_analysts.clone().into_bound_py_any(py)?,
            self.valid_price_targets.clone().into_bound_py_any(py)?,
            self.recommendations.clone().into_bound_py_any(py)?,
            self.analyst_action.clone().into_bound_py_any(py)?,
            self.compared_price_targets.clone().into_bound_py_any(py)?,
            self.beats.clone().into_bound_py_any(py)?,
            self.misses.clone().into_bound_py_any(py)?,
            ::serde_json::to_string(&self.average_return)
                .map_err(|error| {
                    ::pyo3::exceptions::PyValueError::new_err(format!(
                        "failed to serialize field `average_return`: {error}"
                    ))
                })?
                .into_bound_py_any(py)?,
            ::serde_json::to_string(&self.top_return)
                .map_err(|error| {
                    ::pyo3::exceptions::PyValueError::new_err(format!(
                        "failed to serialize field `top_return`: {error}"
                    ))
                })?
                .into_bound_py_any(py)?,
            ::serde_json::to_string(&self.worst_return)
                .map_err(|error| {
                    ::pyo3::exceptions::PyValueError::new_err(format!(
                        "failed to serialize field `worst_return`: {error}"
                    ))
                })?
                .into_bound_py_any(py)?,
        ];
        PyTuple::new(py, members)
    }

    #[getter]
    fn average_return<'py>(&self, py: Python<'py>) -> PyResult<Bound<'py, PyAny>> {
        crate::models::convert::number_to_py(py, &self.average_return)
    }

    #[getter]
    fn top_return<'py>(&self, py: Python<'py>) -> PyResult<Bound<'py, PyAny>> {
        crate::models::convert::number_to_py(py, &self.top_return)
    }

    #[getter]
    fn worst_return<'py>(&self, py: Python<'py>) -> PyResult<Bound<'py, PyAny>> {
        crate::models::convert::number_to_py(py, &self.worst_return)
    }
}

impl From<libfmp::responses::tipranks::TipRanksFirmSummary> for TipRanksFirmSummary {
    fn from(value: libfmp::responses::tipranks::TipRanksFirmSummary) -> Self {
        Self {
            firm_name: value.firm_name,
            from_: value.from.into_inner(),
            to: value.to.into_inner(),
            total_recommendations: value.total_recommendations,
            distinct_symbols: value.distinct_symbols,
            distinct_analysts: value.distinct_analysts,
            valid_price_targets: value.valid_price_targets,
            recommendations: crate::models::tipranks::TipRanksRecommendationCounts::from(
                value.recommendations,
            ),
            analyst_action: crate::models::tipranks::TipRanksAnalystActionCounts::from(
                value.analyst_action,
            ),
            compared_price_targets: value.compared_price_targets,
            beats: value.beats,
            misses: value.misses,
            average_return: value.average_return,
            top_return: value.top_return,
            worst_return: value.worst_return,
        }
    }
}

#[gen_stub_pyclass]
#[pyclass(module = "fmp._native.tipranks", frozen, from_py_object)]
#[derive(Clone)]
pub(crate) struct TipRanksAnalystProfile {
    #[pyo3(get)]
    pub expert_uid: String,
    #[pyo3(get)]
    pub analyst_name: String,
    #[pyo3(get)]
    pub firm_name: String,
    success_rate: ::serde_json::Number,
    excess_return: ::serde_json::Number,
    #[pyo3(get)]
    pub total_recommendations: u64,
    #[pyo3(get)]
    pub good_recommendations: u64,
    #[pyo3(get)]
    pub analyst_rank: u64,
    #[pyo3(get)]
    pub num_of_stars: u64,
}

#[gen_stub_pymethods]
#[pymethods]
impl TipRanksAnalystProfile {
    #[new]
    #[allow(clippy::too_many_arguments)]
    #[allow(clippy::fn_params_excessive_bools)]
    #[pyo3(signature = (expert_uid, analyst_name, firm_name, success_rate, excess_return, total_recommendations, good_recommendations, analyst_rank, num_of_stars))]
    fn new(
        expert_uid: String,
        analyst_name: String,
        firm_name: String,
        success_rate: String,
        excess_return: String,
        total_recommendations: u64,
        good_recommendations: u64,
        analyst_rank: u64,
        num_of_stars: u64,
    ) -> PyResult<Self> {
        let success_rate =
            ::serde_json::from_str::<::serde_json::Number>(&success_rate).map_err(|error| {
                ::pyo3::exceptions::PyValueError::new_err(format!(
                    "invalid JSON for field `success_rate`: {error}"
                ))
            })?;
        let excess_return = ::serde_json::from_str::<::serde_json::Number>(&excess_return)
            .map_err(|error| {
                ::pyo3::exceptions::PyValueError::new_err(format!(
                    "invalid JSON for field `excess_return`: {error}"
                ))
            })?;
        Ok(Self {
            expert_uid,
            analyst_name,
            firm_name,
            success_rate,
            excess_return,
            total_recommendations,
            good_recommendations,
            analyst_rank,
            num_of_stars,
        })
    }

    #[allow(clippy::clone_on_copy)]
    fn __getnewargs__<'py>(&self, py: Python<'py>) -> PyResult<Bound<'py, PyTuple>> {
        let members: Vec<Bound<'py, PyAny>> = vec![
            self.expert_uid.clone().into_bound_py_any(py)?,
            self.analyst_name.clone().into_bound_py_any(py)?,
            self.firm_name.clone().into_bound_py_any(py)?,
            ::serde_json::to_string(&self.success_rate)
                .map_err(|error| {
                    ::pyo3::exceptions::PyValueError::new_err(format!(
                        "failed to serialize field `success_rate`: {error}"
                    ))
                })?
                .into_bound_py_any(py)?,
            ::serde_json::to_string(&self.excess_return)
                .map_err(|error| {
                    ::pyo3::exceptions::PyValueError::new_err(format!(
                        "failed to serialize field `excess_return`: {error}"
                    ))
                })?
                .into_bound_py_any(py)?,
            self.total_recommendations.clone().into_bound_py_any(py)?,
            self.good_recommendations.clone().into_bound_py_any(py)?,
            self.analyst_rank.clone().into_bound_py_any(py)?,
            self.num_of_stars.clone().into_bound_py_any(py)?,
        ];
        PyTuple::new(py, members)
    }

    #[getter]
    fn success_rate<'py>(&self, py: Python<'py>) -> PyResult<Bound<'py, PyAny>> {
        crate::models::convert::number_to_py(py, &self.success_rate)
    }

    #[getter]
    fn excess_return<'py>(&self, py: Python<'py>) -> PyResult<Bound<'py, PyAny>> {
        crate::models::convert::number_to_py(py, &self.excess_return)
    }
}

impl From<libfmp::responses::tipranks::TipRanksAnalystProfile> for TipRanksAnalystProfile {
    fn from(value: libfmp::responses::tipranks::TipRanksAnalystProfile) -> Self {
        Self {
            expert_uid: value.expert_uid.into_inner(),
            analyst_name: value.analyst_name,
            firm_name: value.firm_name,
            success_rate: value.success_rate,
            excess_return: value.excess_return,
            total_recommendations: value.total_recommendations,
            good_recommendations: value.good_recommendations,
            analyst_rank: value.analyst_rank,
            num_of_stars: value.num_of_stars,
        }
    }
}
