// @generated by gen_models; do not edit by hand.

use pyo3::IntoPyObjectExt;
use pyo3::prelude::*;
use pyo3::types::{PyDict, PyTuple};
use pyo3_stub_gen::derive::{gen_stub_pyclass, gen_stub_pymethods};

#[gen_stub_pyclass]
#[pyclass(module = "fmp._native.transcripts", frozen, eq, from_py_object)]
#[derive(Clone, PartialEq)]
pub(crate) struct LatestEarningsTranscript {
    #[pyo3(get)]
    pub symbol: String,
    #[pyo3(get)]
    pub period: String,
    #[pyo3(get)]
    pub fiscal_year: u32,
    #[pyo3(get)]
    pub date: ::chrono::NaiveDate,
}

#[gen_stub_pymethods]
#[pymethods]
impl LatestEarningsTranscript {
    #[new]
    #[allow(clippy::too_many_arguments)]
    #[allow(clippy::fn_params_excessive_bools)]
    #[pyo3(signature = (*, symbol, period, fiscal_year, date))]
    fn new(symbol: String, period: String, fiscal_year: u32, date: ::chrono::NaiveDate) -> Self {
        Self {
            symbol,
            period,
            fiscal_year,
            date,
        }
    }

    #[classattr]
    const __hash__: Option<Py<PyAny>> = None;

    #[allow(clippy::clone_on_copy)]
    fn __getnewargs_ex__<'py>(
        &self,
        py: Python<'py>,
    ) -> PyResult<(Bound<'py, PyTuple>, Bound<'py, PyDict>)> {
        let kwargs = PyDict::new(py);
        kwargs.set_item("symbol", self.symbol.clone().into_bound_py_any(py)?)?;
        kwargs.set_item("period", self.period.clone().into_bound_py_any(py)?)?;
        kwargs.set_item(
            "fiscal_year",
            self.fiscal_year.clone().into_bound_py_any(py)?,
        )?;
        kwargs.set_item("date", self.date.clone().into_bound_py_any(py)?)?;
        Ok((PyTuple::empty(py), kwargs))
    }
}

impl From<libfmp::responses::transcripts::LatestEarningsTranscript> for LatestEarningsTranscript {
    fn from(value: libfmp::responses::transcripts::LatestEarningsTranscript) -> Self {
        Self {
            symbol: value.symbol.into_inner(),
            period: value.period.to_string(),
            fiscal_year: value.fiscal_year.get(),
            date: value.date.into_inner(),
        }
    }
}

#[gen_stub_pyclass]
#[pyclass(module = "fmp._native.transcripts", frozen, eq, from_py_object)]
#[derive(Clone, PartialEq)]
pub(crate) struct EarningsTranscript {
    #[pyo3(get)]
    pub symbol: String,
    #[pyo3(get)]
    pub period: String,
    #[pyo3(get)]
    pub year: u32,
    #[pyo3(get)]
    pub date: ::chrono::NaiveDate,
    #[pyo3(get)]
    pub content: String,
}

#[gen_stub_pymethods]
#[pymethods]
impl EarningsTranscript {
    #[new]
    #[allow(clippy::too_many_arguments)]
    #[allow(clippy::fn_params_excessive_bools)]
    #[pyo3(signature = (*, symbol, period, year, date, content))]
    fn new(
        symbol: String,
        period: String,
        year: u32,
        date: ::chrono::NaiveDate,
        content: String,
    ) -> Self {
        Self {
            symbol,
            period,
            year,
            date,
            content,
        }
    }

    #[classattr]
    const __hash__: Option<Py<PyAny>> = None;

    #[allow(clippy::clone_on_copy)]
    fn __getnewargs_ex__<'py>(
        &self,
        py: Python<'py>,
    ) -> PyResult<(Bound<'py, PyTuple>, Bound<'py, PyDict>)> {
        let kwargs = PyDict::new(py);
        kwargs.set_item("symbol", self.symbol.clone().into_bound_py_any(py)?)?;
        kwargs.set_item("period", self.period.clone().into_bound_py_any(py)?)?;
        kwargs.set_item("year", self.year.clone().into_bound_py_any(py)?)?;
        kwargs.set_item("date", self.date.clone().into_bound_py_any(py)?)?;
        kwargs.set_item("content", self.content.clone().into_bound_py_any(py)?)?;
        Ok((PyTuple::empty(py), kwargs))
    }
}

impl From<libfmp::responses::transcripts::EarningsTranscript> for EarningsTranscript {
    fn from(value: libfmp::responses::transcripts::EarningsTranscript) -> Self {
        Self {
            symbol: value.symbol.into_inner(),
            period: value.period.to_string(),
            year: value.year.get(),
            date: value.date.into_inner(),
            content: value.content,
        }
    }
}

#[gen_stub_pyclass]
#[pyclass(module = "fmp._native.transcripts", frozen, eq, from_py_object)]
#[derive(Clone, PartialEq)]
pub(crate) struct EarningsTranscriptDate {
    #[pyo3(get)]
    pub quarter: u8,
    #[pyo3(get)]
    pub fiscal_year: u32,
    #[pyo3(get)]
    pub date: ::chrono::NaiveDate,
}

#[gen_stub_pymethods]
#[pymethods]
impl EarningsTranscriptDate {
    #[new]
    #[allow(clippy::too_many_arguments)]
    #[allow(clippy::fn_params_excessive_bools)]
    #[pyo3(signature = (*, quarter, fiscal_year, date))]
    fn new(quarter: u8, fiscal_year: u32, date: ::chrono::NaiveDate) -> Self {
        Self {
            quarter,
            fiscal_year,
            date,
        }
    }

    #[classattr]
    const __hash__: Option<Py<PyAny>> = None;

    #[allow(clippy::clone_on_copy)]
    fn __getnewargs_ex__<'py>(
        &self,
        py: Python<'py>,
    ) -> PyResult<(Bound<'py, PyTuple>, Bound<'py, PyDict>)> {
        let kwargs = PyDict::new(py);
        kwargs.set_item("quarter", self.quarter.clone().into_bound_py_any(py)?)?;
        kwargs.set_item(
            "fiscal_year",
            self.fiscal_year.clone().into_bound_py_any(py)?,
        )?;
        kwargs.set_item("date", self.date.clone().into_bound_py_any(py)?)?;
        Ok((PyTuple::empty(py), kwargs))
    }
}

impl From<libfmp::responses::transcripts::EarningsTranscriptDate> for EarningsTranscriptDate {
    fn from(value: libfmp::responses::transcripts::EarningsTranscriptDate) -> Self {
        Self {
            quarter: value.quarter.get(),
            fiscal_year: value.fiscal_year.get(),
            date: value.date.into_inner(),
        }
    }
}
