// @generated by gen_models; do not edit by hand.

use pyo3::IntoPyObjectExt;
use pyo3::prelude::*;
use pyo3::types::{PyDict, PyTuple};
use pyo3_stub_gen::derive::{gen_stub_pyclass, gen_stub_pymethods};

#[gen_stub_pyclass]
#[pyclass(
    module = "fmp._native.statements.growth.income",
    frozen,
    eq,
    from_py_object
)]
#[derive(Clone, PartialEq)]
pub(crate) struct IncomeStatementGrowth {
    #[pyo3(get)]
    pub symbol: String,
    #[pyo3(get)]
    pub date: ::chrono::NaiveDate,
    #[pyo3(get)]
    pub fiscal_year: String,
    #[pyo3(get)]
    pub period: String,
    #[pyo3(get)]
    pub reported_currency: String,
    #[pyo3(get)]
    pub growth_revenue: f64,
    #[pyo3(get)]
    pub growth_cost_of_revenue: f64,
    #[pyo3(get)]
    pub growth_gross_profit: f64,
    #[pyo3(get)]
    pub growth_gross_profit_ratio: f64,
    #[pyo3(get)]
    pub growth_research_and_development_expenses: f64,
    #[pyo3(get)]
    pub growth_general_and_administrative_expenses: f64,
    #[pyo3(get)]
    pub growth_selling_and_marketing_expenses: f64,
    #[pyo3(get)]
    pub growth_other_expenses: f64,
    #[pyo3(get)]
    pub growth_operating_expenses: f64,
    #[pyo3(get)]
    pub growth_cost_and_expenses: f64,
    #[pyo3(get)]
    pub growth_interest_income: f64,
    #[pyo3(get)]
    pub growth_interest_expense: f64,
    #[pyo3(get)]
    pub growth_depreciation_and_amortization: f64,
    #[pyo3(get)]
    pub growth_ebitda: f64,
    #[pyo3(get)]
    pub growth_operating_income: f64,
    #[pyo3(get)]
    pub growth_income_before_tax: f64,
    #[pyo3(get)]
    pub growth_income_tax_expense: f64,
    #[pyo3(get)]
    pub growth_net_income: f64,
    #[pyo3(get)]
    pub growth_eps: f64,
    #[pyo3(get)]
    pub growth_eps_diluted: f64,
    #[pyo3(get)]
    pub growth_weighted_average_shs_out: f64,
    #[pyo3(get)]
    pub growth_weighted_average_shs_out_dil: f64,
    #[pyo3(get)]
    pub growth_ebit: f64,
    #[pyo3(get)]
    pub growth_non_operating_income_excluding_interest: f64,
    #[pyo3(get)]
    pub growth_net_interest_income: f64,
    #[pyo3(get)]
    pub growth_total_other_income_expenses_net: f64,
    #[pyo3(get)]
    pub growth_net_income_from_continuing_operations: f64,
    #[pyo3(get)]
    pub growth_other_adjustments_to_net_income: f64,
    #[pyo3(get)]
    pub growth_net_income_deductions: f64,
}

#[gen_stub_pymethods]
#[pymethods]
impl IncomeStatementGrowth {
    #[new]
    #[allow(clippy::too_many_arguments)]
    #[allow(clippy::fn_params_excessive_bools)]
    #[pyo3(signature = (*, symbol, date, fiscal_year, period, reported_currency, growth_revenue, growth_cost_of_revenue, growth_gross_profit, growth_gross_profit_ratio, growth_research_and_development_expenses, growth_general_and_administrative_expenses, growth_selling_and_marketing_expenses, growth_other_expenses, growth_operating_expenses, growth_cost_and_expenses, growth_interest_income, growth_interest_expense, growth_depreciation_and_amortization, growth_ebitda, growth_operating_income, growth_income_before_tax, growth_income_tax_expense, growth_net_income, growth_eps, growth_eps_diluted, growth_weighted_average_shs_out, growth_weighted_average_shs_out_dil, growth_ebit, growth_non_operating_income_excluding_interest, growth_net_interest_income, growth_total_other_income_expenses_net, growth_net_income_from_continuing_operations, growth_other_adjustments_to_net_income, growth_net_income_deductions))]
    fn new(
        symbol: String,
        date: ::chrono::NaiveDate,
        fiscal_year: String,
        period: String,
        reported_currency: String,
        growth_revenue: f64,
        growth_cost_of_revenue: f64,
        growth_gross_profit: f64,
        growth_gross_profit_ratio: f64,
        growth_research_and_development_expenses: f64,
        growth_general_and_administrative_expenses: f64,
        growth_selling_and_marketing_expenses: f64,
        growth_other_expenses: f64,
        growth_operating_expenses: f64,
        growth_cost_and_expenses: f64,
        growth_interest_income: f64,
        growth_interest_expense: f64,
        growth_depreciation_and_amortization: f64,
        growth_ebitda: f64,
        growth_operating_income: f64,
        growth_income_before_tax: f64,
        growth_income_tax_expense: f64,
        growth_net_income: f64,
        growth_eps: f64,
        growth_eps_diluted: f64,
        growth_weighted_average_shs_out: f64,
        growth_weighted_average_shs_out_dil: f64,
        growth_ebit: f64,
        growth_non_operating_income_excluding_interest: f64,
        growth_net_interest_income: f64,
        growth_total_other_income_expenses_net: f64,
        growth_net_income_from_continuing_operations: f64,
        growth_other_adjustments_to_net_income: f64,
        growth_net_income_deductions: f64,
    ) -> Self {
        Self {
            symbol,
            date,
            fiscal_year,
            period,
            reported_currency,
            growth_revenue,
            growth_cost_of_revenue,
            growth_gross_profit,
            growth_gross_profit_ratio,
            growth_research_and_development_expenses,
            growth_general_and_administrative_expenses,
            growth_selling_and_marketing_expenses,
            growth_other_expenses,
            growth_operating_expenses,
            growth_cost_and_expenses,
            growth_interest_income,
            growth_interest_expense,
            growth_depreciation_and_amortization,
            growth_ebitda,
            growth_operating_income,
            growth_income_before_tax,
            growth_income_tax_expense,
            growth_net_income,
            growth_eps,
            growth_eps_diluted,
            growth_weighted_average_shs_out,
            growth_weighted_average_shs_out_dil,
            growth_ebit,
            growth_non_operating_income_excluding_interest,
            growth_net_interest_income,
            growth_total_other_income_expenses_net,
            growth_net_income_from_continuing_operations,
            growth_other_adjustments_to_net_income,
            growth_net_income_deductions,
        }
    }

    #[classattr]
    const __hash__: Option<Py<PyAny>> = None;

    #[allow(clippy::clone_on_copy)]
    fn __getnewargs_ex__<'py>(
        &self,
        py: Python<'py>,
    ) -> PyResult<(Bound<'py, PyTuple>, Bound<'py, PyDict>)> {
        let kwargs = PyDict::new(py);
        kwargs.set_item("symbol", self.symbol.clone().into_bound_py_any(py)?)?;
        kwargs.set_item("date", self.date.clone().into_bound_py_any(py)?)?;
        kwargs.set_item(
            "fiscal_year",
            self.fiscal_year.clone().into_bound_py_any(py)?,
        )?;
        kwargs.set_item("period", self.period.clone().into_bound_py_any(py)?)?;
        kwargs.set_item(
            "reported_currency",
            self.reported_currency.clone().into_bound_py_any(py)?,
        )?;
        kwargs.set_item(
            "growth_revenue",
            self.growth_revenue.clone().into_bound_py_any(py)?,
        )?;
        kwargs.set_item(
            "growth_cost_of_revenue",
            self.growth_cost_of_revenue.clone().into_bound_py_any(py)?,
        )?;
        kwargs.set_item(
            "growth_gross_profit",
            self.growth_gross_profit.clone().into_bound_py_any(py)?,
        )?;
        kwargs.set_item(
            "growth_gross_profit_ratio",
            self.growth_gross_profit_ratio
                .clone()
                .into_bound_py_any(py)?,
        )?;
        kwargs.set_item(
            "growth_research_and_development_expenses",
            self.growth_research_and_development_expenses
                .clone()
                .into_bound_py_any(py)?,
        )?;
        kwargs.set_item(
            "growth_general_and_administrative_expenses",
            self.growth_general_and_administrative_expenses
                .clone()
                .into_bound_py_any(py)?,
        )?;
        kwargs.set_item(
            "growth_selling_and_marketing_expenses",
            self.growth_selling_and_marketing_expenses
                .clone()
                .into_bound_py_any(py)?,
        )?;
        kwargs.set_item(
            "growth_other_expenses",
            self.growth_other_expenses.clone().into_bound_py_any(py)?,
        )?;
        kwargs.set_item(
            "growth_operating_expenses",
            self.growth_operating_expenses
                .clone()
                .into_bound_py_any(py)?,
        )?;
        kwargs.set_item(
            "growth_cost_and_expenses",
            self.growth_cost_and_expenses
                .clone()
                .into_bound_py_any(py)?,
        )?;
        kwargs.set_item(
            "growth_interest_income",
            self.growth_interest_income.clone().into_bound_py_any(py)?,
        )?;
        kwargs.set_item(
            "growth_interest_expense",
            self.growth_interest_expense.clone().into_bound_py_any(py)?,
        )?;
        kwargs.set_item(
            "growth_depreciation_and_amortization",
            self.growth_depreciation_and_amortization
                .clone()
                .into_bound_py_any(py)?,
        )?;
        kwargs.set_item(
            "growth_ebitda",
            self.growth_ebitda.clone().into_bound_py_any(py)?,
        )?;
        kwargs.set_item(
            "growth_operating_income",
            self.growth_operating_income.clone().into_bound_py_any(py)?,
        )?;
        kwargs.set_item(
            "growth_income_before_tax",
            self.growth_income_before_tax
                .clone()
                .into_bound_py_any(py)?,
        )?;
        kwargs.set_item(
            "growth_income_tax_expense",
            self.growth_income_tax_expense
                .clone()
                .into_bound_py_any(py)?,
        )?;
        kwargs.set_item(
            "growth_net_income",
            self.growth_net_income.clone().into_bound_py_any(py)?,
        )?;
        kwargs.set_item("growth_eps", self.growth_eps.clone().into_bound_py_any(py)?)?;
        kwargs.set_item(
            "growth_eps_diluted",
            self.growth_eps_diluted.clone().into_bound_py_any(py)?,
        )?;
        kwargs.set_item(
            "growth_weighted_average_shs_out",
            self.growth_weighted_average_shs_out
                .clone()
                .into_bound_py_any(py)?,
        )?;
        kwargs.set_item(
            "growth_weighted_average_shs_out_dil",
            self.growth_weighted_average_shs_out_dil
                .clone()
                .into_bound_py_any(py)?,
        )?;
        kwargs.set_item(
            "growth_ebit",
            self.growth_ebit.clone().into_bound_py_any(py)?,
        )?;
        kwargs.set_item(
            "growth_non_operating_income_excluding_interest",
            self.growth_non_operating_income_excluding_interest
                .clone()
                .into_bound_py_any(py)?,
        )?;
        kwargs.set_item(
            "growth_net_interest_income",
            self.growth_net_interest_income
                .clone()
                .into_bound_py_any(py)?,
        )?;
        kwargs.set_item(
            "growth_total_other_income_expenses_net",
            self.growth_total_other_income_expenses_net
                .clone()
                .into_bound_py_any(py)?,
        )?;
        kwargs.set_item(
            "growth_net_income_from_continuing_operations",
            self.growth_net_income_from_continuing_operations
                .clone()
                .into_bound_py_any(py)?,
        )?;
        kwargs.set_item(
            "growth_other_adjustments_to_net_income",
            self.growth_other_adjustments_to_net_income
                .clone()
                .into_bound_py_any(py)?,
        )?;
        kwargs.set_item(
            "growth_net_income_deductions",
            self.growth_net_income_deductions
                .clone()
                .into_bound_py_any(py)?,
        )?;
        Ok((PyTuple::empty(py), kwargs))
    }
}

impl From<libfmp::responses::statements::growth::income::IncomeStatementGrowth>
    for IncomeStatementGrowth
{
    fn from(value: libfmp::responses::statements::growth::income::IncomeStatementGrowth) -> Self {
        Self {
            symbol: value.symbol.into_inner(),
            date: value.date.into_inner(),
            fiscal_year: value.fiscal_year.as_str().to_owned(),
            period: value.period.to_string(),
            reported_currency: value.reported_currency.into_inner(),
            growth_revenue: value.growth_revenue,
            growth_cost_of_revenue: value.growth_cost_of_revenue,
            growth_gross_profit: value.growth_gross_profit,
            growth_gross_profit_ratio: value.growth_gross_profit_ratio,
            growth_research_and_development_expenses: value
                .growth_research_and_development_expenses,
            growth_general_and_administrative_expenses: value
                .growth_general_and_administrative_expenses,
            growth_selling_and_marketing_expenses: value.growth_selling_and_marketing_expenses,
            growth_other_expenses: value.growth_other_expenses,
            growth_operating_expenses: value.growth_operating_expenses,
            growth_cost_and_expenses: value.growth_cost_and_expenses,
            growth_interest_income: value.growth_interest_income,
            growth_interest_expense: value.growth_interest_expense,
            growth_depreciation_and_amortization: value.growth_depreciation_and_amortization,
            growth_ebitda: value.growth_ebitda,
            growth_operating_income: value.growth_operating_income,
            growth_income_before_tax: value.growth_income_before_tax,
            growth_income_tax_expense: value.growth_income_tax_expense,
            growth_net_income: value.growth_net_income,
            growth_eps: value.growth_eps,
            growth_eps_diluted: value.growth_eps_diluted,
            growth_weighted_average_shs_out: value.growth_weighted_average_shs_out,
            growth_weighted_average_shs_out_dil: value.growth_weighted_average_shs_out_dil,
            growth_ebit: value.growth_ebit,
            growth_non_operating_income_excluding_interest: value
                .growth_non_operating_income_excluding_interest,
            growth_net_interest_income: value.growth_net_interest_income,
            growth_total_other_income_expenses_net: value.growth_total_other_income_expenses_net,
            growth_net_income_from_continuing_operations: value
                .growth_net_income_from_continuing_operations,
            growth_other_adjustments_to_net_income: value.growth_other_adjustments_to_net_income,
            growth_net_income_deductions: value.growth_net_income_deductions,
        }
    }
}
